using System.Text.Json;
using OpenCode.Workspace.Core.Models;

namespace OpenCode.Workspace.Core.Workspaces;

public sealed class WorkspaceAiRuntimeContextService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
    };

    public WorkspaceAiRuntimeContext Build(WorkspaceSnapshot snapshot)
    {
        var applications = snapshot.Health.Services
            .Where(item => string.Equals(item.Category, "Application", StringComparison.OrdinalIgnoreCase))
            .Select(item => new WorkspaceAiApplicationAvailability
            {
                Name = item.Name,
                ServiceId = item.ServiceId,
                Status = item.Status.ToString(),
                Summary = item.Summary,
                Url = string.IsNullOrWhiteSpace(item.OpenUrl) ? item.PrimaryUrl : item.OpenUrl,
                Confidence = item.Confidence,
            })
            .ToList();

        return new WorkspaceAiRuntimeContext
        {
            Metadata = new WorkspaceAiContextMetadata
            {
                GeneratedBy = "OpenCode Workspace Manager",
                Source = "Workspace Health, Runtime Resources, and workspace runtime state",
                UserEdits = "Do not edit this file. It is regenerated from live workspace health.",
                GeneratedUtc = DateTimeOffset.UtcNow,
            },
            InspectionPolicy = new WorkspaceAiInspectionPolicy
            {
                Authority = "Workspace Health is the authoritative runtime context for this workspace.",
                DefaultBehavior = "Consult this context before running generic shell commands. If confidence is HIGH and the context answers the question, do not contradict it with generic process-based guesses.",
                ManualOverridePhrase = "Verify independently",
                AvoidShellConclusions =
                [
                    "Do not use systemctl, ps, lsof, or generic Linux process inspection to conclude Docker Compose service health when this context already has provider-aware evidence.",
                    "Do not guess Oracle, ORDS, APEX, or SQL Developer Web process names from inside the workspace container.",
                ],
                ProviderAwareChecks =
                [
                    "Oracle provider evidence includes listener, XDB, ORDS, SQL Developer Web, Oracle APEX, and container identities when available.",
                    "Only run raw shell verification if the user explicitly says `Verify independently` or this context lacks sufficient evidence.",
                ],
            },
            Workspace = new WorkspaceAiWorkspaceState
            {
                Name = snapshot.Definition.Workspace.Name,
                RootPath = snapshot.Paths.RootPath,
                ConfigurationPath = snapshot.ConfigurationPath,
                CurrentBranch = snapshot.Safety.AdvancedGit.CurrentBranch,
                RuntimeState = snapshot.RuntimeState.ToString(),
                SessionState = snapshot.Session.State.ToString(),
                UpdateRequired = snapshot.UpdateRequired,
            },
            Runtime = new WorkspaceAiRuntimeState
            {
                Engine = snapshot.LocalRuntimeState?.ResolvedEngine ?? snapshot.ResolvedRuntimePlan?.Runtime ?? string.Empty,
                TargetPlatform = snapshot.LocalRuntimeState?.ResolvedPlatform ?? snapshot.ResolvedRuntimePlan?.TargetPlatform ?? string.Empty,
                HealthStatus = snapshot.Health.OverallStatus.ToString(),
                Confidence = snapshot.Health.Confidence,
                Summary = snapshot.Health.Summary,
                Recommendation = snapshot.Health.Recommendation,
            },
            Applications = applications,
            Services = snapshot.Health.Services.Select(item => new WorkspaceAiServiceContext
            {
                ServiceId = item.ServiceId,
                Name = item.Name,
                Category = item.Category,
                Status = item.Status.ToString(),
                Summary = item.Summary,
                Recommendation = item.Recommendation,
                Endpoint = item.Endpoint,
                PrimaryUrl = item.PrimaryUrl,
                OpenUrl = item.OpenUrl,
                Confidence = item.Confidence,
                LastProbeUtc = item.Timestamp,
                Highlights = item.Highlights,
                Evidence = item.Evidence,
            }).ToList(),
            Resources = new WorkspaceAiRuntimeResources
            {
                Ports = snapshot.LocalRuntimeState?.Resources.Ports is { } ports ? ports : Array.Empty<WorkspacePortAllocationRecord>(),
                ServiceEndpoints = snapshot.LocalRuntimeState?.Resources.ServiceEndpoints is { } serviceEndpoints ? serviceEndpoints : Array.Empty<WorkspaceServiceEndpointRecord>(),
                RuntimeIdentifiers = snapshot.LocalRuntimeState?.Resources.RuntimeIdentifiers is { } runtimeIdentifiers ? runtimeIdentifiers : Array.Empty<WorkspaceRuntimeIdentifierRecord>(),
                Conflicts = snapshot.LocalRuntimeState?.Resources.Conflicts is { } conflicts ? conflicts : Array.Empty<WorkspaceResourceConflictRecord>(),
            },
            Providers = snapshot.Health.Providers.Select(item => new WorkspaceAiProviderContext
            {
                ProviderKey = item.ProviderKey,
                DisplayName = item.DisplayName,
                Status = item.Status.ToString(),
                Summary = item.Summary,
                WorkspaceImpact = item.WorkspaceImpact,
                RecommendedAction = item.RecommendedAction,
                Confidence = item.Confidence,
                LastProbeUtc = item.Timestamp,
                Evidence = item.Evidence,
            }).ToList(),
        };
    }

    public void Write(WorkspaceSnapshot snapshot)
    {
        var context = Build(snapshot);
        Directory.CreateDirectory(snapshot.Paths.OpencodeLocalPath);
        var path = GetContextFilePath(snapshot.Paths);
        File.WriteAllText(path, JsonSerializer.Serialize(context, JsonOptions).Replace("\r\n", "\n", StringComparison.Ordinal));
    }

    public static string GetContextFilePath(WorkspacePaths paths)
        => Path.Combine(paths.OpencodeLocalPath, "workspace-health.json");
}
