using System.Runtime.InteropServices;
using OpenCode.Workspace.Core.Models;

namespace OpenCode.Workspace.Core.Generation;

public sealed class GeneratedArtifactRuntimeMetadata
{
    public required string HostOperatingSystem { get; init; }
    public required string HostArchitecture { get; init; }
    public required string Runtime { get; init; }
    public required string TargetPlatform { get; init; }
    public required string Compatibility { get; init; }
    public required DateTimeOffset GeneratedUtc { get; init; }
}

public static class GeneratedArtifactRuntimeMetadataBuilder
{
    private const string GeneratedFileLineEnding = "\n";

    public static GeneratedArtifactRuntimeMetadata Create(ResolvedRuntimePlan? plan, DateTimeOffset? generatedUtc = null)
    {
        var hostOperatingSystem = FormatHostOperatingSystem(plan?.HostPlatform.OperatingSystem ?? DetectOperatingSystem());
        var hostArchitecture = FormatHostArchitecture(plan?.HostPlatform.Architecture ?? DetectArchitecture());
        var nativePlatform = !string.IsNullOrWhiteSpace(plan?.HostPlatform.NativeContainerPlatform)
            ? plan!.HostPlatform.NativeContainerPlatform
            : MapNativeContainerPlatform(DetectArchitecture());

        return new GeneratedArtifactRuntimeMetadata
        {
            HostOperatingSystem = hostOperatingSystem,
            HostArchitecture = hostArchitecture,
            Runtime = string.IsNullOrWhiteSpace(plan?.Runtime) ? "unresolved" : plan.Runtime,
            TargetPlatform = string.IsNullOrWhiteSpace(plan?.TargetPlatform) ? "unresolved" : plan.TargetPlatform,
            Compatibility = FormatCompatibility(plan?.CompatibilityMode, plan?.TargetPlatform, nativePlatform),
            GeneratedUtc = generatedUtc ?? DateTimeOffset.UtcNow,
        };
    }

    public static GeneratedArtifactRuntimeMetadata Create(WorkspaceRuntimeStateRecord? state, DateTimeOffset? generatedUtc = null)
    {
        var hostOperatingSystem = FormatHostOperatingSystem(DetectOperatingSystem());
        var hostArchitecture = FormatHostArchitecture(DetectArchitecture());
        var nativePlatform = MapNativeContainerPlatform(DetectArchitecture());
        var compatibilityMode = Enum.TryParse<RuntimeCompatibilityMode>(state?.CompatibilityMode, ignoreCase: true, out var parsedCompatibility)
            ? parsedCompatibility
            : (RuntimeCompatibilityMode?)null;

        return new GeneratedArtifactRuntimeMetadata
        {
            HostOperatingSystem = hostOperatingSystem,
            HostArchitecture = hostArchitecture,
            Runtime = string.IsNullOrWhiteSpace(state?.ResolvedEngine) ? "unresolved" : state.ResolvedEngine,
            TargetPlatform = string.IsNullOrWhiteSpace(state?.ResolvedPlatform) ? "unresolved" : state.ResolvedPlatform,
            Compatibility = FormatCompatibility(compatibilityMode, state?.ResolvedPlatform, nativePlatform),
            GeneratedUtc = generatedUtc ?? state?.GeneratedArtifactsUtc ?? state?.LastSuccessfulProvision ?? DateTimeOffset.UtcNow,
        };
    }

    public static GeneratedArtifactRuntimeMetadata WithGeneratedUtc(GeneratedArtifactRuntimeMetadata metadata, DateTimeOffset generatedUtc)
        => new()
        {
            HostOperatingSystem = metadata.HostOperatingSystem,
            HostArchitecture = metadata.HostArchitecture,
            Runtime = metadata.Runtime,
            TargetPlatform = metadata.TargetPlatform,
            Compatibility = metadata.Compatibility,
            GeneratedUtc = generatedUtc,
        };

    public static string BuildCommentHeader(GeneratedArtifactRuntimeMetadata? metadata, params string[] sourceLines)
    {
        var effectiveMetadata = metadata ?? Create((WorkspaceRuntimeStateRecord?)null);
        var lines = new List<string>
        {
            "Generated by OpenCode Workspace Manager",
            string.Empty,
            $"Host OS: {effectiveMetadata.HostOperatingSystem}",
            $"Host Architecture: {effectiveMetadata.HostArchitecture}",
            string.Empty,
            $"Runtime: {effectiveMetadata.Runtime}",
            $"Target Platform: {effectiveMetadata.TargetPlatform}",
            $"Compatibility: {effectiveMetadata.Compatibility}",
            string.Empty,
            $"Generated: {effectiveMetadata.GeneratedUtc:O}",
        };

        if (sourceLines.Length > 0)
        {
            lines.Add(string.Empty);
            lines.AddRange(sourceLines.Where(line => !string.IsNullOrWhiteSpace(line)));
        }

        lines.Add(string.Empty);
        lines.Add("Do not edit manually.");
        lines.Add("Re-run reprovision to regenerate.");

        return string.Join(GeneratedFileLineEnding, lines.Select(line => string.IsNullOrEmpty(line) ? "#" : $"# {line}"));
    }

    private static string FormatCompatibility(RuntimeCompatibilityMode? compatibilityMode, string? targetPlatform, string nativePlatform)
    {
        if (!string.IsNullOrWhiteSpace(targetPlatform) && string.Equals(targetPlatform, nativePlatform, StringComparison.OrdinalIgnoreCase))
        {
            return "native";
        }

        return compatibilityMode switch
        {
            RuntimeCompatibilityMode.MultiArchitecture => "multi-architecture fallback",
            RuntimeCompatibilityMode.Emulated => "fallback",
            RuntimeCompatibilityMode.Unavailable => "unavailable",
            RuntimeCompatibilityMode.Native when !string.IsNullOrWhiteSpace(targetPlatform) => "fallback",
            _ => "unresolved",
        };
    }

    private static string FormatHostOperatingSystem(HostOperatingSystem operatingSystem)
        => operatingSystem switch
        {
            HostOperatingSystem.Windows => "Windows",
            HostOperatingSystem.Linux => "Linux",
            HostOperatingSystem.MacOS => "macOS",
            _ => "Unknown",
        };

    private static string FormatHostArchitecture(HostArchitecture architecture)
        => architecture switch
        {
            HostArchitecture.X64 => "x64",
            HostArchitecture.Arm64 => "arm64",
            _ => "unknown",
        };

    private static HostOperatingSystem DetectOperatingSystem()
    {
        if (OperatingSystem.IsWindows())
        {
            return HostOperatingSystem.Windows;
        }

        if (OperatingSystem.IsLinux())
        {
            return HostOperatingSystem.Linux;
        }

        if (OperatingSystem.IsMacOS())
        {
            return HostOperatingSystem.MacOS;
        }

        return HostOperatingSystem.Unknown;
    }

    private static HostArchitecture DetectArchitecture()
        => RuntimeInformation.OSArchitecture switch
        {
            Architecture.X64 => HostArchitecture.X64,
            Architecture.Arm64 => HostArchitecture.Arm64,
            _ => HostArchitecture.Unknown,
        };

    private static string MapNativeContainerPlatform(HostArchitecture architecture)
        => architecture switch
        {
            HostArchitecture.X64 => "linux/amd64",
            HostArchitecture.Arm64 => "linux/arm64",
            _ => string.Empty,
        };
}
