using System.Text;
using OpenCode.Workspace.Core.Models;
using OpenCode.Workspace.Core.Workspaces;

namespace OpenCode.Workspace.Core.Generation;

/// <summary>
/// Generates a provisioning script instead of baking custom images so the full
/// installation plan stays readable and reproducible from official Ubuntu images.
/// </summary>
public sealed class ProvisioningScriptGenerator
{
    private const string BashRcManagedStart = "# >>> OpenCode Workspace Manager managed block >>>";
    private const string BashRcManagedEnd = "# <<< OpenCode Workspace Manager managed block <<<";

    public string Generate(ResolvedWorkspace workspace, GeneratedArtifactRuntimeMetadata? runtimeMetadata = null)
    {
        var builder = new StringBuilder();
        // Ubuntu 24.04 renamed the old libaio1 package to libaio1t64, so Oracle-related
        // provisioning must not hardcode libaio1 in the generic apt package plan.
        var oracleWorkspaceKind = OracleWorkspaceFamily.Detect(workspace.Definition);
        var isOracleDemoWorkspace = oracleWorkspaceKind != OracleWorkspaceKind.None;
        var hasOracleApex = oracleWorkspaceKind is OracleWorkspaceKind.Apex or OracleWorkspaceKind.ApexLang;
        var hasOracleApexLang = oracleWorkspaceKind == OracleWorkspaceKind.ApexLang;
        var aptPackages = workspace.AptPackages
            .Where(packageName => !isOracleDemoWorkspace || !string.Equals(packageName, "libaio1", StringComparison.OrdinalIgnoreCase))
            .ToList();

        builder.AppendLine("#!/usr/bin/env bash");
        builder.AppendLine(GeneratedArtifactRuntimeMetadataBuilder.BuildCommentHeader(
            runtimeMetadata,
            "Source inputs: workspace.yaml and catalog manifests under catalog/.",
            "User edits are not preserved. Edit workspace.yaml or catalog manifests instead."));
        builder.AppendLine("set -euo pipefail");
        builder.AppendLine();
        builder.AppendLine("export DEBIAN_FRONTEND=noninteractive");
        builder.AppendLine("export HOME=/home/opencode");
        builder.AppendLine("if [ -f /workspace/.env ]; then");
        builder.AppendLine("  while IFS= read -r env_line || [ -n \"${env_line}\" ]; do");
        builder.AppendLine("    env_line=${env_line%$'\\r'}");
        builder.AppendLine("    case \"${env_line}\" in");
        builder.AppendLine("      ''|'#'*) continue ;;");
        builder.AppendLine("    esac");
        builder.AppendLine("    if [[ \"${env_line}\" != *=* ]]; then");
        builder.AppendLine("      echo \"[runtime] Skipping invalid .env line: ${env_line}\" >&2");
        builder.AppendLine("      continue");
        builder.AppendLine("    fi");
        builder.AppendLine("    env_key=${env_line%%=*}");
        builder.AppendLine("    env_value=${env_line#*=}");
        builder.AppendLine("    export \"${env_key}=${env_value}\"");
        builder.AppendLine("  done < /workspace/.env");
        builder.AppendLine("fi");
        builder.AppendLine();
        builder.AppendLine("stage_name='' ");
        builder.AppendLine("stage_started_at=0");
        builder.AppendLine("stage_active=0");
        builder.AppendLine("timestamp_utc() {");
        builder.AppendLine("  date -u +'%Y-%m-%dT%H:%M:%SZ'");
        builder.AppendLine("}");
        builder.AppendLine("begin_stage() {");
        builder.AppendLine("  stage_name=\"$1\"");
        builder.AppendLine("  stage_started_at=$(date +%s)");
        builder.AppendLine("  stage_active=1");
        builder.AppendLine("  echo \"[stage] name=${stage_name} status=started started_at=$(timestamp_utc)\"");
        builder.AppendLine("}");
        builder.AppendLine("complete_stage() {");
        builder.AppendLine("  if [ \"${stage_active:-0}\" -ne 1 ]; then");
        builder.AppendLine("    return 0");
        builder.AppendLine("  fi");
        builder.AppendLine("  local completed_at elapsed_seconds");
        builder.AppendLine("  completed_at=$(timestamp_utc)");
        builder.AppendLine("  elapsed_seconds=$(( $(date +%s) - stage_started_at ))");
        builder.AppendLine("  echo \"[stage] name=${stage_name} status=completed completed_at=${completed_at} elapsed_seconds=${elapsed_seconds}\"");
        builder.AppendLine("  stage_active=0");
        builder.AppendLine("}");
        builder.AppendLine("fail_stage() {");
        builder.AppendLine("  local failure_point=\"$1\"");
        builder.AppendLine("  local evidence=\"${2:-}\"");
        builder.AppendLine("  local recommendation=\"${3:-Inspect the provisioning log and retry reprovision.}\"");
        builder.AppendLine("  local failed_at elapsed_seconds active_stage");
        builder.AppendLine("  failed_at=$(timestamp_utc)");
        builder.AppendLine("  elapsed_seconds=0");
        builder.AppendLine("  active_stage=${stage_name:-Provisioning}");
        builder.AppendLine("  if [ \"${stage_started_at:-0}\" -gt 0 ]; then");
        builder.AppendLine("    elapsed_seconds=$(( $(date +%s) - stage_started_at ))");
        builder.AppendLine("  fi");
        builder.AppendLine("  echo \"[stage] name=${active_stage} status=failed failed_at=${failed_at} elapsed_seconds=${elapsed_seconds}\" >&2");
        builder.AppendLine("  echo \"Failure point: ${failure_point}\" >&2");
        builder.AppendLine("  if [ -n \"${evidence}\" ]; then echo \"Last observed status: ${evidence}\" >&2; fi");
        builder.AppendLine("  if [ -n \"${recommendation}\" ]; then echo \"Suggested next action: ${recommendation}\" >&2; fi");
        builder.AppendLine("  exit 1");
        builder.AppendLine("}");
        builder.AppendLine("run_with_timeout() {");
        builder.AppendLine("  local timeout_seconds=\"$1\"");
        builder.AppendLine("  local description=\"$2\"");
        builder.AppendLine("  local recommendation=\"$3\"");
        builder.AppendLine("  shift 3");
        builder.AppendLine("  local output_file=/tmp/opencode-timeout-$$.log");
        builder.AppendLine("  if timeout --foreground \"${timeout_seconds}s\" \"$@\" >\"${output_file}\" 2>&1; then");
        builder.AppendLine("    cat \"${output_file}\"");
        builder.AppendLine("    rm -f \"${output_file}\"");
        builder.AppendLine("    return 0");
        builder.AppendLine("  fi");
        builder.AppendLine("  local exit_code=$?");
        builder.AppendLine("  local last_status='' ");
        builder.AppendLine("  if [ -f \"${output_file}\" ]; then");
        builder.AppendLine("    last_status=$(tr '\\n' ' ' < \"${output_file}\" | xargs || true)");
        builder.AppendLine("  fi");
        builder.AppendLine("  rm -f \"${output_file}\"");
        builder.AppendLine("  if [ \"${exit_code}\" -eq 124 ]; then");
        builder.AppendLine("    fail_stage \"${description} timed out after ${timeout_seconds}s.\" \"${last_status}\" \"${recommendation}\"");
        builder.AppendLine("  fi");
        builder.AppendLine("  fail_stage \"${description} failed.\" \"${last_status}\" \"${recommendation}\"");
        builder.AppendLine("}");
        builder.AppendLine("wait_for_command() {");
        builder.AppendLine("  local timeout_seconds=\"$1\"");
        builder.AppendLine("  local interval_seconds=\"$2\"");
        builder.AppendLine("  local description=\"$3\"");
        builder.AppendLine("  local recommendation=\"$4\"");
        builder.AppendLine("  shift 4");
        builder.AppendLine("  local started_at current_elapsed last_status output_file");
        builder.AppendLine("  started_at=$(date +%s)");
        builder.AppendLine("  output_file=/tmp/opencode-wait-$$.log");
        builder.AppendLine("  while true; do");
        builder.AppendLine("    if \"$@\" >\"${output_file}\" 2>&1; then");
        builder.AppendLine("      cat \"${output_file}\"");
        builder.AppendLine("      rm -f \"${output_file}\"");
        builder.AppendLine("      return 0");
        builder.AppendLine("    fi");
        builder.AppendLine("    current_elapsed=$(( $(date +%s) - started_at ))");
        builder.AppendLine("    last_status=$(tr '\\n' ' ' < \"${output_file}\" | xargs || true)");
        builder.AppendLine("    if [ \"${current_elapsed}\" -ge \"${timeout_seconds}\" ]; then");
        builder.AppendLine("      rm -f \"${output_file}\"");
        builder.AppendLine("      fail_stage \"${description} timed out after ${timeout_seconds}s.\" \"${last_status}\" \"${recommendation}\"");
        builder.AppendLine("    fi");
        builder.AppendLine("    echo \"[stage] name=${stage_name:-Provisioning} status=waiting waiting_for=${description} elapsed_seconds=${current_elapsed} timeout_seconds=${timeout_seconds}\" >&2");
        builder.AppendLine("    sleep \"${interval_seconds}\"");
        builder.AppendLine("  done");
        builder.AppendLine("}");
        builder.AppendLine("trap 'fail_stage \"Provisioning command failed.\" \"Last command: ${BASH_COMMAND}\" \"Inspect the stage log and retry reprovision.\"' ERR");
        builder.AppendLine();
        builder.AppendLine("# Create the durable workspace user that owns the interactive OpenCode session.");
        builder.AppendLine("begin_stage 'Initialize workspace user'");
        builder.AppendLine("if ! id -u opencode >/dev/null 2>&1; then");
        builder.AppendLine("  useradd -m -d /home/opencode -s /bin/bash opencode");
        builder.AppendLine("fi");
        builder.AppendLine("mkdir -p \"$HOME\"");
        builder.AppendLine("chown -R opencode:opencode \"$HOME\"");
        builder.AppendLine("touch \"$HOME/.bashrc\"");
        builder.AppendLine();
        builder.AppendLine("# Initialize OpenCode user directories before the first interactive launch.");
        builder.AppendLine("mkdir -p /home/opencode/.local/share/opencode/log");
        builder.AppendLine("mkdir -p /home/opencode/.config/opencode");
        builder.AppendLine("mkdir -p /home/opencode/.cache/opencode");
        builder.AppendLine("chown -R opencode:opencode /home/opencode/.local");
        builder.AppendLine("chown -R opencode:opencode /home/opencode/.config");
        builder.AppendLine("chown -R opencode:opencode /home/opencode/.cache");
        builder.AppendLine("su -s /bin/bash -c 'test -d /home/opencode/.local/share/opencode/log && test -w /home/opencode/.local/share/opencode/log' opencode");
        builder.AppendLine("complete_stage");
        builder.AppendLine();
        builder.AppendLine("# Install the apt package plan resolved from selected features.");
        builder.AppendLine("begin_stage 'Install base packages'");
        builder.AppendLine("apt-get update");

        if (aptPackages.Count > 0)
        {
            builder.AppendLine($"apt-get install -y {string.Join(" ", aptPackages)}");
        }
        builder.AppendLine("complete_stage");

        builder.AppendLine();
        builder.AppendLine("# Install the requested Node.js runtime from NodeSource so modern npm packages use a consistent LTS baseline.");
        builder.AppendLine("begin_stage 'Install Node.js runtime'");
        builder.AppendLine($"echo \"[runtime] Requested Node.js major version: {workspace.Definition.Runtime.GetEffectiveNodeMajorVersion()}\"");
        builder.AppendLine("apt-get remove -y nodejs npm || true");
        builder.AppendLine($"curl -fsSL https://deb.nodesource.com/setup_{workspace.Definition.Runtime.GetEffectiveNodeMajorVersion()}.x | bash -");
        builder.AppendLine("apt-get install -y nodejs");
        builder.AppendLine("apt-cache policy nodejs | sed -n '1,20p'");
        builder.AppendLine("complete_stage");

        if (isOracleDemoWorkspace)
        {
            builder.AppendLine();
            if (hasOracleApex)
            {
                builder.AppendLine("echo \"[oracle-apex] Stage: Preparing Workspace\"");
                builder.AppendLine("echo \"[oracle-apex] Stage: Downloading Dependencies\"");
            }

            builder.AppendLine("# Oracle SQLcl still needs libaio, but Ubuntu 24.04 renamed the package to libaio1t64.");
            builder.AppendLine(". /etc/os-release && echo \"[oracle] Detected Ubuntu version: ${VERSION_ID:-unknown} (${ID:-unknown})\"");
            builder.AppendLine("if apt-cache policy libaio1 | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then");
            builder.AppendLine("  oracle_libaio_pkg=libaio1");
            builder.AppendLine("elif apt-cache policy libaio1t64 | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then");
            builder.AppendLine("  oracle_libaio_pkg=libaio1t64");
            builder.AppendLine("else");
            builder.AppendLine("  echo \"[oracle] No compatible libaio package found for this Ubuntu image.\" >&2");
            builder.AppendLine("  exit 1");
            builder.AppendLine("fi");
            builder.AppendLine("echo \"[oracle] Selected libaio package: ${oracle_libaio_pkg}\"");
            builder.AppendLine("apt-get install -y \"${oracle_libaio_pkg}\"");
            builder.AppendLine("dpkg -L \"${oracle_libaio_pkg}\"");
            builder.AppendLine("if [ \"${oracle_libaio_pkg}\" = \"libaio1t64\" ] && [ -f /usr/lib/x86_64-linux-gnu/libaio.so.1t64 ] && [ ! -e /usr/lib/x86_64-linux-gnu/libaio.so.1 ]; then");
            builder.AppendLine("  ln -sf /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1");
            builder.AppendLine("fi");
            builder.AppendLine("ldconfig");
            builder.AppendLine();
            builder.AppendLine("# SQLcl requires Java 11+, and Ubuntu images may expose different OpenJDK package names.");
            builder.AppendLine("if apt-cache policy openjdk-21-jre-headless | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then");
            builder.AppendLine("  oracle_java_pkg=openjdk-21-jre-headless");
            builder.AppendLine("elif apt-cache policy openjdk-17-jre-headless | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then");
            builder.AppendLine("  oracle_java_pkg=openjdk-17-jre-headless");
            builder.AppendLine("else");
            builder.AppendLine("  echo \"[oracle] No compatible Java runtime package found for SQLcl.\" >&2");
            builder.AppendLine("  exit 1");
            builder.AppendLine("fi");
            builder.AppendLine("echo \"[oracle] Selected Java package: ${oracle_java_pkg}\"");
            builder.AppendLine("apt-get install -y \"${oracle_java_pkg}\"");
            builder.AppendLine("JAVA_BIN=$(command -v java)");
            builder.AppendLine("if [ -z \"${JAVA_BIN}\" ]; then");
            builder.AppendLine("  echo \"[oracle] Java runtime is still unavailable after installation.\" >&2");
            builder.AppendLine("  exit 1");
            builder.AppendLine("fi");
            builder.AppendLine("export JAVA_HOME=$(dirname \"$(dirname \"$(readlink -f \"${JAVA_BIN}\")\")\")");
            builder.AppendLine("echo \"[oracle] JAVA_HOME=${JAVA_HOME}\"");
            builder.AppendLine("java -version");
            builder.AppendLine();
            builder.AppendLine("# Install Oracle Instant Client SQL*Plus so demo verification works from the workspace terminal even if SQLcl is unavailable.");
            builder.AppendLine("apt-get install -y libnsl2");
            builder.AppendLine("oracle_sqlplus_root=/opt/oracle/instantclient");
            builder.AppendLine("oracle_sqlplus_stage=/tmp/oracle-instantclient-stage");
            builder.AppendLine("oracle_sqlplus_basic_url=https://download.oracle.com/otn_software/linux/instantclient/2390000/instantclient-basiclite-linux.x64-23.9.0.25.07.zip");
            builder.AppendLine("oracle_sqlplus_package_url=https://download.oracle.com/otn_software/linux/instantclient/2390000/instantclient-sqlplus-linux.x64-23.9.0.25.07.zip");
            builder.AppendLine("# Reuse a healthy SQLcl install when possible, and only replace it after a staged reinstall validates successfully.");
            builder.AppendLine("mkdir -p /workspace/.local/oracle/network/admin");
            builder.AppendLine("oracle_connection='demo_user/demo_password@//oracle-demo:1521/FREEPDB1'");
            if (hasOracleApex)
            {
                builder.AppendLine("echo \"[oracle-apex] Stage: Starting Oracle Database\"");
                builder.AppendLine("echo \"[oracle-apex] Stage: Waiting for Database Readiness\"");
            }

            builder.AppendLine("oracle_probe_script=/tmp/sqlcl-probe.sql");
            builder.AppendLine("cat > \"${oracle_probe_script}\" <<'SQL'");
            builder.AppendLine("SET HEADING OFF");
            builder.AppendLine("SET FEEDBACK OFF");
            builder.AppendLine("SET PAGESIZE 0");
            builder.AppendLine("SET VERIFY OFF");
            builder.AppendLine("SELECT 'Connection OK' AS status FROM dual;");
            builder.AppendLine("EXIT");
            builder.AppendLine("SQL");
            builder.AppendLine("oracle_sqlplus_probe_script=/tmp/sqlplus-probe.sql");
            builder.AppendLine("cat > \"${oracle_sqlplus_probe_script}\" <<'SQL'");
            builder.AppendLine("SELECT 'Connection OK' AS status FROM dual;");
            builder.AppendLine("EXIT;");
            builder.AppendLine("SQL");
            builder.AppendLine("oracle_demo_user_setup_script=/tmp/oracle-demo-user-setup.sql");
            builder.AppendLine("cat > \"${oracle_demo_user_setup_script}\" <<'SQL'");
            builder.AppendLine("ALTER SESSION SET CONTAINER = FREEPDB1;");
            builder.AppendLine("DECLARE");
            builder.AppendLine("  l_exists NUMBER := 0;");
            builder.AppendLine("BEGIN");
            builder.AppendLine("  SELECT COUNT(*) INTO l_exists FROM dba_users WHERE username = 'DEMO_USER';");
            builder.AppendLine("  IF l_exists = 0 THEN");
            builder.AppendLine("    EXECUTE IMMEDIATE 'CREATE USER demo_user IDENTIFIED BY \"demo_password\" QUOTA UNLIMITED ON USERS';");
            builder.AppendLine("  ELSE");
            builder.AppendLine("    EXECUTE IMMEDIATE 'ALTER USER demo_user IDENTIFIED BY \"demo_password\" ACCOUNT UNLOCK';");
            builder.AppendLine("  END IF;");
            builder.AppendLine("END;");
            builder.AppendLine("/");
            builder.AppendLine("GRANT CREATE SESSION TO demo_user;");
            builder.AppendLine("GRANT CREATE TABLE TO demo_user;");
            builder.AppendLine("GRANT CREATE VIEW TO demo_user;");
            builder.AppendLine("GRANT CREATE PROCEDURE TO demo_user;");
            builder.AppendLine("GRANT CREATE TRIGGER TO demo_user;");
            builder.AppendLine("GRANT CREATE SEQUENCE TO demo_user;");
            builder.AppendLine("GRANT UNLIMITED TABLESPACE TO demo_user;");
            builder.AppendLine("EXIT");
            builder.AppendLine("SQL");
                builder.AppendLine("ensure_demo_user_ready() {");
                builder.AppendLine("  local setup_script=/tmp/oracle-demo-user-setup.sql");
                builder.AppendLine("  local sysdba_connection=\"sys/${ORACLE_PASSWORD}@//oracle-demo:1521/FREEPDB1 as sysdba\"");
                builder.AppendLine("  local setup_output");
            builder.AppendLine("  setup_output=$(sqlplus -L -S \"${sysdba_connection}\" @\"${setup_script}\" 2>&1) || {");
            builder.AppendLine("    echo \"[oracle] Oracle administrator password does not match the running database.\" >&2");
            builder.AppendLine("    printf '%s\\n' \"${setup_output}\" >&2");
            builder.AppendLine("    echo \"[oracle] Recommended action: Rebuild Runtime.\" >&2");
            builder.AppendLine("    exit 1");
                builder.AppendLine("  }");
                builder.AppendLine("  printf '%s\n' \"${setup_output}\"");
                builder.AppendLine("}");
                builder.AppendLine("ensure_ords_public_user_ready() {");
                builder.AppendLine("  local sysdba_connection=\"sys/${ORACLE_PASSWORD}@//oracle-demo:1521/FREEPDB1 as sysdba\"");
                builder.AppendLine("  local ords_public_password=\"change-on-first-demo\"");
                builder.AppendLine("  local setup_output");
                builder.AppendLine("  setup_output=$(sqlplus -L -S \"${sysdba_connection}\" <<SQL 2>&1");
                builder.AppendLine("ALTER SESSION SET CONTAINER = FREEPDB1;");
                builder.AppendLine("DECLARE");
                builder.AppendLine("  l_exists NUMBER := 0;");
                builder.AppendLine("BEGIN");
                builder.AppendLine("  SELECT COUNT(*) INTO l_exists FROM dba_users WHERE username = 'ORDS_PUBLIC_USER';");
                builder.AppendLine("  IF l_exists = 0 THEN");
                builder.AppendLine("    RAISE_APPLICATION_ERROR(-20001, 'ORDS_PUBLIC_USER is missing');");
                builder.AppendLine("  END IF;");
                builder.AppendLine("END;");
                builder.AppendLine("/");
                builder.AppendLine("ALTER USER ords_public_user IDENTIFIED BY \"${ords_public_password}\" ACCOUNT UNLOCK;");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("  ) || {");
                builder.AppendLine("    oracle_fail \"Oracle REST Data Services database user could not be synchronized.\" \"${setup_output}\" \"Reset Runtime to recreate the Oracle data volume, or manually reset ORDS_PUBLIC_USER to the managed password before retrying.\" high");
                builder.AppendLine("  }");
                builder.AppendLine("  printf '%s\n' \"${setup_output}\"");
                builder.AppendLine("}");
                builder.AppendLine("validate_ords_installation() {");
                builder.AppendLine("  local ords_public_user_count ords_metadata_count");
                builder.AppendLine("  ords_public_user_count=$(query_ords_public_user_count | tr -d '\r' | xargs || true)");
                builder.AppendLine("  ords_metadata_count=$(query_ords_metadata_count | tr -d '\r' | xargs || true)");
                builder.AppendLine("  if [ \"${ords_public_user_count:-0}\" = '0' ] || [ \"${ords_metadata_count:-0}\" = '0' ]; then");
                builder.AppendLine("    oracle_fail \"Oracle REST Data Services is not installed in the database.\" \"ORDS_PUBLIC_USER count = ${ords_public_user_count:-0}; ORDS_METADATA count = ${ords_metadata_count:-0}\" \"The official ORDS container does not become usable until 'ords install' creates ORDS_PUBLIC_USER and ORDS_METADATA in the database. Rebuild Runtime or inspect ORDS installation logs before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("}");
                builder.AppendLine("sqlplus_demo_probe() {");
                builder.AppendLine("  sqlplus -S \"${oracle_connection}\" @\"${oracle_sqlplus_probe_script}\" > /tmp/sqlplus-probe.out 2>&1 && grep -Fq 'Connection OK' /tmp/sqlplus-probe.out");
                builder.AppendLine("}");
            builder.AppendLine("activate_sqlplus_install() {");
            builder.AppendLine("  local instantclient_root=\"$1\"");
            builder.AppendLine("  local sqlplus_launcher=\"${instantclient_root}/sqlplus\"");
            builder.AppendLine("  if [ ! -f \"${sqlplus_launcher}\" ]; then");
            builder.AppendLine("    return 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  chmod +x \"${sqlplus_launcher}\"");
            builder.AppendLine("  export LD_LIBRARY_PATH=\"${instantclient_root}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}\"");
            builder.AppendLine("  export PATH=\"${instantclient_root}:${PATH}\"");
            builder.AppendLine("  ln -sf \"${sqlplus_launcher}\" /usr/local/bin/sqlplus");
            builder.AppendLine("  ldd \"${sqlplus_launcher}\"");
            builder.AppendLine("}");
            builder.AppendLine("if command -v sqlplus >/dev/null 2>&1 && sqlplus -v; then");
            builder.AppendLine("  echo \"[oracle] SQL*Plus already installed and valid; skipping reinstall.\"");
            builder.AppendLine("elif activate_sqlplus_install \"${oracle_sqlplus_root}/current\" && sqlplus -v; then");
            builder.AppendLine("  echo \"[oracle] SQL*Plus already installed and valid; skipping reinstall.\"");
            builder.AppendLine("else");
            builder.AppendLine("  rm -rf \"${oracle_sqlplus_stage}\"");
            builder.AppendLine("  mkdir -p \"${oracle_sqlplus_stage}\"");
            builder.AppendLine("  if ! curl -fsSL \"${oracle_sqlplus_basic_url}\" -o /tmp/instantclient-basiclite.zip; then");
            builder.AppendLine("    echo \"[oracle] Failed to download Oracle Instant Client Basic Light.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if ! curl -fsSL \"${oracle_sqlplus_package_url}\" -o /tmp/instantclient-sqlplus.zip; then");
            builder.AppendLine("    echo \"[oracle] Failed to download Oracle Instant Client SQL*Plus.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if ! unzip -oq /tmp/instantclient-basiclite.zip -d \"${oracle_sqlplus_stage}\"; then");
            builder.AppendLine("    echo \"[oracle] Failed to extract Oracle Instant Client Basic Light.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if ! unzip -oq /tmp/instantclient-sqlplus.zip -d \"${oracle_sqlplus_stage}\"; then");
            builder.AppendLine("    echo \"[oracle] Failed to extract Oracle Instant Client SQL*Plus.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  oracle_sqlplus_candidate=$(find \"${oracle_sqlplus_stage}\" -maxdepth 1 -mindepth 1 -type d -name 'instantclient_*' | head -n 1)");
            builder.AppendLine("  if [ -z \"${oracle_sqlplus_candidate}\" ]; then");
            builder.AppendLine("    echo \"[oracle] Oracle Instant Client extract did not produce an instantclient directory.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if ! activate_sqlplus_install \"${oracle_sqlplus_candidate}\" || ! sqlplus -v; then");
            builder.AppendLine("    echo \"[oracle] Staged SQL*Plus install failed version validation.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  rm -rf \"${oracle_sqlplus_root}\"");
            builder.AppendLine("  mkdir -p \"${oracle_sqlplus_root}\"");
            builder.AppendLine("  cp -a \"${oracle_sqlplus_candidate}\" \"${oracle_sqlplus_root}/\"");
            builder.AppendLine("  ln -sfn \"${oracle_sqlplus_root}/$(basename \"${oracle_sqlplus_candidate}\")\" \"${oracle_sqlplus_root}/current\"");
            builder.AppendLine("  if ! activate_sqlplus_install \"${oracle_sqlplus_root}/current\" || ! sqlplus -v; then");
            builder.AppendLine("    echo \"[oracle] Reinstalled SQL*Plus failed version validation after activation.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("fi");
            builder.AppendLine("oracle_client_home=$(find \"${oracle_sqlplus_root}\" -maxdepth 2 -type f -name 'libsqlplus.so' -printf '%h\n' 2>/dev/null | while read -r dir; do if ls \"$dir\"/libclntsh.so* >/dev/null 2>&1; then printf '%s\n' \"$dir\"; break; fi; done)");
            builder.AppendLine("if [ -n \"${oracle_client_home}\" ] && [ -d \"${oracle_client_home}\" ]; then");
            builder.AppendLine("  printf '%s\n' \"${oracle_client_home}\" > /etc/ld.so.conf.d/oracle-instantclient.conf");
            builder.AppendLine("  ldconfig");
            builder.AppendLine("  export ORACLE_CLIENT_HOME=${oracle_client_home}");
            builder.AppendLine("  export LD_LIBRARY_PATH=${oracle_client_home}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}");
            builder.AppendLine("  export PATH=${oracle_client_home}:${PATH}");
            builder.AppendLine("fi");
            builder.AppendLine("begin_stage 'Validate Oracle client connectivity'");
            builder.AppendLine("run_with_timeout 120 'Oracle demo user setup' 'Rebuild Runtime if the Oracle data volume contains stale credentials.' bash -lc \"$(declare -f ensure_demo_user_ready); ensure_demo_user_ready\"");
            builder.AppendLine("wait_for_command 300 10 'Oracle SQL*Plus readiness' 'Wait for Oracle startup to finish or Rebuild Runtime if the Oracle data volume contains stale credentials.' sqlplus_demo_probe");
            builder.AppendLine("validate_sqlcl_install() {");
            builder.AppendLine("  local sqlcl_root=\"$1\"");
            builder.AppendLine("  local sqlcl_launcher=\"${sqlcl_root}/sqlcl/bin/sql\"");
            builder.AppendLine("  if [ ! -f \"${sqlcl_launcher}\" ]; then");
            builder.AppendLine("    return 1");
            builder.AppendLine("  fi");
                builder.AppendLine("  chmod +x \"${sqlcl_launcher}\"");
                builder.AppendLine("  ln -sf \"${sqlcl_launcher}\" /usr/local/bin/sql");
                builder.AppendLine("  ln -sf \"${sqlcl_launcher}\" /usr/local/bin/sqlcl");
                builder.AppendLine("  if ! \"${sqlcl_launcher}\" -v; then");
                builder.AppendLine("    return 1");
                builder.AppendLine("  fi");
                builder.AppendLine("  if ! sql -v; then");
                builder.AppendLine("    return 1");
                builder.AppendLine("  fi");
                builder.AppendLine("  if ! sqlcl -v; then");
                builder.AppendLine("    return 1");
                builder.AppendLine("  fi");
                builder.AppendLine("  wait_for_command 300 10 'Oracle SQLcl readiness' 'Wait for Oracle startup to finish or Rebuild Runtime if the Oracle data volume contains stale credentials.' bash -lc \"sql -S '${oracle_connection}' @'${oracle_probe_script}' > /tmp/sqlcl-probe.out 2>&1 && grep -Fq 'Connection OK' /tmp/sqlcl-probe.out\"");
                builder.AppendLine("  cat /tmp/sqlcl-probe.out");
                builder.AppendLine("  return 0");
            builder.AppendLine("}");
            builder.AppendLine("if validate_sqlcl_install /opt/sqlcl; then");
            builder.AppendLine("  echo \"[oracle] SQLcl already installed and valid; skipping reinstall.\"");
            builder.AppendLine("else");
            builder.AppendLine("  echo \"[oracle] Existing SQLcl install missing or invalid. Reinstalling.\" >&2");
            builder.AppendLine("  oracle_sqlcl_download=/tmp/sqlcl.zip");
            builder.AppendLine("  oracle_sqlcl_extract=/tmp/sqlcl-extract");
            builder.AppendLine("  rm -rf \"${oracle_sqlcl_extract}\"");
            builder.AppendLine("  mkdir -p \"${oracle_sqlcl_extract}\"");
            builder.AppendLine("  if ! curl -fsSL https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip -o \"${oracle_sqlcl_download}\"; then");
            builder.AppendLine("    echo \"[oracle] Failed to download the official SQLcl zip archive.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if ! unzip -oq \"${oracle_sqlcl_download}\" -d \"${oracle_sqlcl_extract}\"; then");
            builder.AppendLine("    echo \"[oracle] Failed to extract the SQLcl archive into the staging directory.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if [ ! -f \"${oracle_sqlcl_extract}/sqlcl/bin/sql\" ]; then");
            builder.AppendLine("    echo \"[oracle] Unexpected SQLcl layout: staged sqlcl/bin/sql was not created.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if [ ! -f \"${oracle_sqlcl_extract}/sqlcl/lib/dbtools-sqlcl.jar\" ]; then");
            builder.AppendLine("    echo \"[oracle] Unexpected SQLcl layout: staged dbtools-sqlcl.jar is missing.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("  if ! unzip -l \"${oracle_sqlcl_extract}/sqlcl/lib/dbtools-sqlcl.jar\" | grep -q 'oracle/dbtools/raptor/scriptrunner/cmdline/SqlCli.class'; then");
            builder.AppendLine("    echo \"[oracle] Diagnostic only: SqlCli.class was not found in staged dbtools-sqlcl.jar. Continuing with runtime validation.\" >&2");
            builder.AppendLine("  fi");
            builder.AppendLine("  if ! validate_sqlcl_install \"${oracle_sqlcl_extract}\"; then");
            builder.AppendLine("    echo \"[oracle] Staged SQLcl install failed runtime validation.\" >&2");
            builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
                builder.AppendLine("  rm -rf /opt/sqlcl");
                builder.AppendLine("  mkdir -p /opt/sqlcl");
                builder.AppendLine("  cp -a \"${oracle_sqlcl_extract}/.\" /opt/sqlcl/");
                builder.AppendLine("  ln -sf /opt/sqlcl/sqlcl/bin/sql /usr/local/bin/sql");
                builder.AppendLine("  ln -sf /opt/sqlcl/sqlcl/bin/sql /usr/local/bin/sqlcl");
                builder.AppendLine("  if ! validate_sqlcl_install /opt/sqlcl; then");
                builder.AppendLine("    echo \"[oracle] Reinstalled SQLcl failed runtime validation after activation.\" >&2");
                builder.AppendLine("    exit 1");
            builder.AppendLine("  fi");
            builder.AppendLine("fi");
            builder.AppendLine("complete_stage");
            if (hasOracleApex)
            {
                builder.AppendLine("echo \"[oracle-apex] Stage: Installing ORDS\"");
                builder.AppendLine("echo \"[oracle-apex] Stage: Installing APEX\"");
                builder.AppendLine("echo \"[oracle-apex] Stage: Configuring Workspace\"");
                builder.AppendLine("echo \"[oracle-apex] Stage: Creating Sample Application\"");
                builder.AppendLine("echo \"[oracle-apex] Stage: Running Validation\"");
                builder.AppendLine($"oracle_apex_media_dir={OracleWorkspaceSettings.ApexDownloadsDirectory}");
                builder.AppendLine($"oracle_apex_media_preferred={OracleWorkspaceSettings.ApexPreferredZipName}");
                builder.AppendLine("oracle_apex_extract_root=/tmp/oracle-apex-install");
                builder.AppendLine("oracle_apex_extract_dir=${oracle_apex_extract_root}/apex");
                builder.AppendLine("oracle_apex_admin_email=admin@example.local");
                builder.AppendLine("oracle_apex_admin_password=${ORACLE_PASSWORD}");
                builder.AppendLine("find_apex_media() {");
                builder.AppendLine("  if [ -f \"${oracle_apex_media_dir}/${oracle_apex_media_preferred}\" ]; then");
                builder.AppendLine("    printf '%s\n' \"${oracle_apex_media_dir}/${oracle_apex_media_preferred}\"");
                builder.AppendLine("    return 0");
                builder.AppendLine("  fi");
                builder.AppendLine("  for candidate in \"${oracle_apex_media_dir}\"/apex_*.zip \"${oracle_apex_media_dir}\"/apex*.zip; do");
                builder.AppendLine("    if [ -f \"${candidate}\" ]; then");
                builder.AppendLine("      printf '%s\n' \"${candidate}\"");
                builder.AppendLine("      return 0");
                builder.AppendLine("    fi");
                builder.AppendLine("  done");
                builder.AppendLine("  return 1");
                builder.AppendLine("}");
                builder.AppendLine("query_apex_registry() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT comp_id || '|' || version || '|' || status FROM dba_registry WHERE comp_id = 'APEX';");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("query_apex_version() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT version_no FROM apex_release;");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("query_apex_schema_count() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT COUNT(*) FROM dba_users WHERE username LIKE 'APEX\\_%' ESCAPE '\\';");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("query_ords_public_user_count() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT COUNT(*) FROM dba_users WHERE username = 'ORDS_PUBLIC_USER';");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("query_ords_metadata_count() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT COUNT(*) FROM dba_users WHERE username = 'ORDS_METADATA';");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("query_database_open_mode() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT open_mode FROM v$database;");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("query_pdb_open_mode() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT open_mode FROM v$pdbs WHERE name = 'FREEPDB1';");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("query_xdb_status() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SET TRIMSPOOL ON");
                builder.AppendLine("SELECT status FROM dba_registry WHERE comp_id = 'XDB';");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("recompile_invalid_oracle_components() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("ALTER SESSION SET CONTAINER = CDB$ROOT;");
                builder.AppendLine("BEGIN");
                builder.AppendLine("  utl_recomp.recomp_parallel(0);");
                builder.AppendLine("END;");
                builder.AppendLine("/");
                builder.AppendLine("EXECUTE dbms_registry_sys.validate_components;");
                builder.AppendLine("ALTER SESSION SET CONTAINER = FREEPDB1;");
                builder.AppendLine("BEGIN");
                builder.AppendLine("  utl_recomp.recomp_parallel(0);");
                builder.AppendLine("END;");
                builder.AppendLine("/");
                builder.AppendLine("EXECUTE dbms_registry_sys.validate_components;");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("oracle_set_stage() {");
                builder.AppendLine("  complete_stage || true");
                builder.AppendLine("  oracle_stage=\"$1\"");
                builder.AppendLine("  begin_stage \"Oracle: ${oracle_stage}\"");
                builder.AppendLine("}");
                builder.AppendLine("oracle_fail() {");
                builder.AppendLine("  local reason=\"$1\"");
                builder.AppendLine("  local evidence=\"$2\"");
                builder.AppendLine("  local recommendation=\"$3\"");
                builder.AppendLine("  local confidence=\"${4:-high}\"");
                builder.AppendLine("  echo \"Workspace provisioning stopped.\" >&2");
                builder.AppendLine("  echo \"Stage: ${oracle_stage}\" >&2");
                builder.AppendLine("  echo \"Reason: ${reason}\" >&2");
                builder.AppendLine("  if [ -n \"${evidence}\" ]; then echo \"Evidence: ${evidence}\" >&2; fi");
                builder.AppendLine("  if [ -n \"${recommendation}\" ]; then echo \"Recommended action: ${recommendation}\" >&2; fi");
                builder.AppendLine("  echo \"Confidence: ${confidence}\" >&2");
                builder.AppendLine("  exit 1");
                builder.AppendLine("}");
                builder.AppendLine("validate_oracle_environment() {");
                builder.AppendLine("  local workspace_available_kb sysdba_probe");
                builder.AppendLine("  workspace_available_kb=$(df -Pk /workspace | awk 'NR==2 {print $4}')");
                builder.AppendLine("  if [ -z \"${workspace_available_kb}\" ] || [ \"${workspace_available_kb}\" -lt 1048576 ]; then");
                builder.AppendLine("    oracle_fail \"Workspace disk space is too low for Oracle provisioning.\" \"Available KB = ${workspace_available_kb:-unknown}\" \"Free disk space in the workspace volume and try Recover Workspace again.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  if ! getent hosts oracle-demo >/dev/null 2>&1; then");
                builder.AppendLine("    oracle_fail \"Oracle database host is not reachable from the workspace container.\" \"Host lookup for oracle-demo failed\" \"Start the Oracle database container or repair Docker networking before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  sysdba_probe=$(sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL' 2>&1 || true");
                builder.AppendLine("SET PAGESIZE 0");
                builder.AppendLine("SET FEEDBACK OFF");
                builder.AppendLine("SET HEADING OFF");
                builder.AppendLine("SET VERIFY OFF");
                builder.AppendLine("SELECT 'SYSDBA OK' FROM dual;");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("  )");
                builder.AppendLine("  if ! printf '%s' \"${sysdba_probe}\" | grep -Fq 'SYSDBA OK'; then");
                builder.AppendLine("    oracle_fail \"SYSDBA connection to Oracle failed.\" \"${sysdba_probe}\" \"Recreate the Oracle database container or restore a clean Oracle data volume before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("}");
                builder.AppendLine("validate_oracle_prerequisites() {");
                builder.AppendLine("  local database_open_mode pdb_open_mode xdb_status");
                builder.AppendLine("  database_open_mode=$(query_database_open_mode | tr -d '\r' | xargs || true)");
                builder.AppendLine("  if [ \"${database_open_mode}\" != 'READ WRITE' ]; then");
                builder.AppendLine("    oracle_fail \"Oracle database is not open for writes.\" \"open_mode = ${database_open_mode:-missing}\" \"Wait for the Oracle database to finish opening or recreate the Oracle data volume if it remains stuck.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  pdb_open_mode=$(query_pdb_open_mode | tr -d '\r' | xargs || true)");
                builder.AppendLine("  if [ \"${pdb_open_mode}\" != 'READ WRITE' ]; then");
                builder.AppendLine("    oracle_fail \"Required pluggable database FREEPDB1 is not open.\" \"FREEPDB1 open_mode = ${pdb_open_mode:-missing}\" \"Open FREEPDB1 or recreate the Oracle database container before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  xdb_status=$(query_xdb_status | tr -d '\r' | xargs || true)");
                builder.AppendLine("  if [ \"${xdb_status}\" != 'VALID' ]; then");
                builder.AppendLine("    echo \"[oracle] XDB status is ${xdb_status:-missing}. Attempting Oracle component recompile...\" >&2");
                builder.AppendLine("    recompile_invalid_oracle_components >/tmp/oracle-utlrp.out 2>&1 || true");
                builder.AppendLine("    cat /tmp/oracle-utlrp.out >&2 || true");
                builder.AppendLine("    xdb_status=$(query_xdb_status | tr -d '\r' | xargs || true)");
                builder.AppendLine("  fi");
                builder.AppendLine("  if [ \"${xdb_status}\" != 'VALID' ]; then");
                builder.AppendLine("    oracle_fail \"Oracle XML Database (XDB) is invalid.\" \"XDB status = ${xdb_status:-missing}\" \"Recreate the Oracle database container or restore a clean Oracle data volume.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("}");
                builder.AppendLine("configure_apex_cdn() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("BEGIN");
                builder.AppendLine("  FOR c1 IN (SELECT version_no FROM apex_release) LOOP");
                builder.AppendLine("    APEX_INSTANCE_ADMIN.set_parameter(");
                builder.AppendLine("      p_parameter => 'IMAGE_PREFIX',");
                builder.AppendLine("      p_value => 'https://static.oracle.com/cdn/apex/' || c1.version_no || '/');");
                builder.AppendLine("  END LOOP;");
                builder.AppendLine("  COMMIT;");
                builder.AppendLine("END;");
                builder.AppendLine("/");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("prepare_apex_extract_dir() {");
                builder.AppendLine("  local apex_zip");
                builder.AppendLine("  mkdir -p \"${oracle_apex_media_dir}\"");
                builder.AppendLine("  if ! apex_zip=$(find_apex_media); then");
                builder.AppendLine("    echo \"OracleRuntimeFailure: APEX installation media missing\" >&2");
                builder.AppendLine("    echo \"Expected path: ${oracle_apex_media_dir}/${oracle_apex_media_preferred}\" >&2");
                builder.AppendLine("    echo \"Supported filename patterns: ${oracle_apex_media_dir}/apex.zip, ${oracle_apex_media_dir}/apex_*.zip, ${oracle_apex_media_dir}/apex*.zip\" >&2");
                builder.AppendLine("    echo \"Download Oracle APEX ZIP from https://www.oracle.com/tools/downloads/apex-downloads.html and place it under ${oracle_apex_media_dir}.\" >&2");
                builder.AppendLine("    echo \"This repository does not include Oracle APEX media.\" >&2");
                builder.AppendLine("    exit 1");
                builder.AppendLine("  fi");
                builder.AppendLine("  echo \"[oracle-apex] Using APEX media: ${apex_zip}\"");
                builder.AppendLine("  rm -rf \"${oracle_apex_extract_root}\"");
                builder.AppendLine("  mkdir -p \"${oracle_apex_extract_root}\"");
                builder.AppendLine("  unzip -oq \"${apex_zip}\" -d \"${oracle_apex_extract_root}\"");
                builder.AppendLine("  if [ ! -f \"${oracle_apex_extract_dir}/apexins.sql\" ]; then");
                builder.AppendLine("    echo \"OracleRuntimeFailure: APEX installation media missing apexins.sql after extraction\" >&2");
                builder.AppendLine("    exit 1");
                builder.AppendLine("  fi");
                builder.AppendLine("}");
                builder.AppendLine("ensure_apex_admin_ready() {");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<SQL");
                builder.AppendLine("ALTER SESSION SET CONTAINER = FREEPDB1;");
                builder.AppendLine("BEGIN");
                builder.AppendLine("  APEX_INSTANCE_ADMIN.SET_PARAMETER('STRONG_SITE_ADMIN_PASSWORD', 'N');");
                builder.AppendLine("  APEX_INSTANCE_ADMIN.SET_PARAMETER('EXPIRE_FND_USER_ACCOUNTS', 'N');");
                builder.AppendLine("  APEX_INSTANCE_ADMIN.CREATE_OR_UPDATE_ADMIN_USER(");
                builder.AppendLine("    p_username => 'ADMIN',");
                builder.AppendLine("    p_email => '${oracle_apex_admin_email}',");
                builder.AppendLine("    p_password => '${oracle_apex_admin_password}');");
                builder.AppendLine("  APEX_INSTANCE_ADMIN.UNLOCK_USER(");
                builder.AppendLine("    p_workspace => 'INTERNAL',");
                builder.AppendLine("    p_username => 'ADMIN',");
                builder.AppendLine("    p_password => '${oracle_apex_admin_password}');");
                builder.AppendLine("  UPDATE apex_260100.wwv_flow_fnd_user");
                builder.AppendLine("     SET account_locked = 'N',");
                builder.AppendLine("         account_expiry = NULL,");
                builder.AppendLine("         change_password_on_first_use = 'N',");
                builder.AppendLine("         first_password_use_occurred = 'Y',");
                builder.AppendLine("         password_date = SYSDATE,");
                builder.AppendLine("         email_address = '${oracle_apex_admin_email}'");
                builder.AppendLine("   WHERE user_name = 'ADMIN';");
                builder.AppendLine("  COMMIT;");
                builder.AppendLine("END;");
                builder.AppendLine("/");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("}");
                builder.AppendLine("install_apex_media() {");
                builder.AppendLine("  local apex_zip apex_registry apex_schema_count apex_version apex_registry_status apex_registry_version");
                builder.AppendLine("  apex_registry=$(query_apex_registry | tr -d '\r' | xargs || true)");
                builder.AppendLine("  apex_schema_count=$(query_apex_schema_count | tr -d '\r' | xargs || true)");
                builder.AppendLine("  apex_registry_status=$(printf '%s' \"${apex_registry}\" | awk -F'|' '{print $3}')");
                builder.AppendLine("  apex_registry_version=$(printf '%s' \"${apex_registry}\" | awk -F'|' '{print $2}')");
                builder.AppendLine("  if [ -n \"${apex_registry}\" ] && [ \"${apex_registry_status}\" = 'VALID' ] && [ -n \"${apex_schema_count}\" ] && [ \"${apex_schema_count}\" != '0' ]; then");
                builder.AppendLine("    echo \"[oracle-apex] APEX already installed: ${apex_registry}\"");
                builder.AppendLine("    configure_apex_cdn");
                builder.AppendLine("    ensure_apex_admin_ready");
                builder.AppendLine("    return 0");
                builder.AppendLine("  fi");
                builder.AppendLine("  if [ -n \"${apex_registry}\" ] || { [ -n \"${apex_schema_count}\" ] && [ \"${apex_schema_count}\" != '0' ]; }; then");
                builder.AppendLine("    oracle_fail \"Oracle APEX is partially installed or inconsistent.\" \"APEX registry = ${apex_registry:-missing}; schema count = ${apex_schema_count:-0}; installed version = ${apex_registry_version:-missing}; registry status = ${apex_registry_status:-missing}\" \"Rebuild Runtime to recreate the Oracle data volume, or manually repair the Oracle APEX registry before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  prepare_apex_extract_dir");
                builder.AppendLine("  (cd \"${oracle_apex_extract_dir}\" && sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("@apexins.sql SYSAUX SYSAUX TEMP /i/");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("  )");
                builder.AppendLine("  (cd \"${oracle_apex_extract_dir}\" && sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<SQL");
                builder.AppendLine("@apex_rest_config.sql");
                builder.AppendLine("${oracle_apex_admin_password}");
                builder.AppendLine("${oracle_apex_admin_password}");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("  )");
                builder.AppendLine("  ensure_apex_admin_ready");
                builder.AppendLine("  configure_apex_cdn");
                builder.AppendLine("  sqlplus -S \"sys/change-on-first-demo@//oracle-demo:1521/FREEPDB1 as sysdba\" <<'SQL'");
                builder.AppendLine("BEGIN");
                builder.AppendLine("  sys.validate_apex;");
                builder.AppendLine("END;");
                builder.AppendLine("/");
                builder.AppendLine("EXIT");
                builder.AppendLine("SQL");
                builder.AppendLine("  apex_registry=$(query_apex_registry | tr -d '\r' | xargs || true)");
                builder.AppendLine("  apex_schema_count=$(query_apex_schema_count | tr -d '\r' | xargs || true)");
                builder.AppendLine("  apex_version=$(query_apex_version | tr -d '\r' | xargs || true)");
                builder.AppendLine("  apex_registry_status=$(printf '%s' \"${apex_registry}\" | awk -F'|' '{print $3}')");
                builder.AppendLine("  if [ -z \"${apex_registry}\" ]; then");
                builder.AppendLine("    oracle_fail \"Oracle APEX did not register in the database.\" \"APEX registry entry was missing after installation.\" \"Rebuild Runtime to recreate the Oracle data volume, or inspect the Oracle APEX installation log before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  if [ \"${apex_registry_status}\" != 'VALID' ]; then");
                builder.AppendLine("    oracle_fail \"Oracle APEX registry is not valid after installation.\" \"Registry state = ${apex_registry:-missing}\" \"Rebuild Runtime to recreate the Oracle data volume, or manually repair the Oracle APEX registry before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  if [ -z \"${apex_schema_count}\" ] || [ \"${apex_schema_count}\" = \"0\" ]; then");
                builder.AppendLine("    oracle_fail \"Oracle APEX schema users were not created.\" \"APEX schema count = ${apex_schema_count:-0}\" \"Rebuild Runtime to recreate the Oracle data volume, or inspect the Oracle APEX installation log before retrying.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  echo \"[oracle-apex] APEX installed: ${apex_registry}\"");
                builder.AppendLine("  echo \"[oracle-apex] APEX version: ${apex_version}\"");
                builder.AppendLine("}");
                builder.AppendLine("wait_for_ords_runtime() {");
                builder.AppendLine($"oracle_ords_url=http://oracle-ords:{OracleWorkspaceSettings.ContainerOrdsPort}/ords");
                builder.AppendLine($"oracle_apex_url=http://oracle-ords:{OracleWorkspaceSettings.ContainerOrdsPort}/ords/apex");
                builder.AppendLine($"oracle_ords_landing_url=http://oracle-ords:{OracleWorkspaceSettings.ContainerOrdsPort}/ords/_/landing");
                builder.AppendLine("  local started_at current_elapsed ords_http_status ords_body_excerpt ords_redirect_location");
                builder.AppendLine("  if [ ! -f /opt/opencode-workspace/config/ords/global/settings.xml ] || [ ! -f /opt/opencode-workspace/config/ords/databases/default/pool.xml ]; then");
                builder.AppendLine("    oracle_fail \"Oracle REST Data Services (ORDS) config did not initialize.\" \"Managed ORDS config files were not created under /opt/opencode-workspace/config/ords\" \"Inspect the oracle-ords container logs and regenerate the managed ORDS config before retrying.\" medium");
                builder.AppendLine("  fi");
                builder.AppendLine("  if ! grep -Fq '<entry key=\"db.username\">ORDS_PUBLIC_USER</entry>' /opt/opencode-workspace/config/ords/databases/default/pool.xml; then");
                builder.AppendLine("    oracle_fail \"Oracle REST Data Services pool configuration is invalid.\" \"pool.xml does not use ORDS_PUBLIC_USER for db.username\" \"Regenerate the managed ORDS config and retry provisioning.\" high");
                builder.AppendLine("  fi");
                builder.AppendLine("  validate_ords_installation");
                builder.AppendLine("  started_at=$(date +%s)");
                builder.AppendLine("  while true; do");
                builder.AppendLine("    ords_http_status=$(curl -sS -D /tmp/ords-health-headers.txt -o /tmp/ords-health-body.txt -w '%{http_code}' \"${oracle_ords_landing_url}\" || true)");
                builder.AppendLine("    ords_body_excerpt=$(tr '\n' ' ' < /tmp/ords-health-body.txt | xargs || true)");
                builder.AppendLine("    ords_redirect_location=$(grep -i '^Location:' /tmp/ords-health-headers.txt | tail -n 1 | cut -d' ' -f2- | tr -d '\r' | xargs || true)");
                builder.AppendLine("    if [ \"${ords_http_status}\" = '200' ]; then");
                builder.AppendLine("      rm -f /tmp/ords-health-body.txt /tmp/ords-health-headers.txt");
                builder.AppendLine("      return 0");
                builder.AppendLine("    fi");
                builder.AppendLine("    if [ \"${ords_http_status}\" = '302' ] && printf '%s' \"${ords_redirect_location}\" | grep -Fq '/ords/_/landing'; then");
                builder.AppendLine("      rm -f /tmp/ords-health-body.txt");
                builder.AppendLine("      rm -f /tmp/ords-health-headers.txt");
                builder.AppendLine("      return 0");
                builder.AppendLine("    fi");
                builder.AppendLine("    if [ \"${ords_http_status}\" = '574' ] && printf '%s' \"${ords_body_excerpt}\" | grep -Fq 'DatabaseCredentialError'; then");
                builder.AppendLine("      rm -f /tmp/ords-health-body.txt /tmp/ords-health-headers.txt");
                builder.AppendLine("      oracle_fail \"Oracle REST Data Services database credentials are invalid.\" \"ORDS returned HTTP 574 DatabaseCredentialError for ORDS_PUBLIC_USER.\" \"Reset ORDS_PUBLIC_USER to the managed password and restart ORDS before retrying.\" high");
                builder.AppendLine("    fi");
                builder.AppendLine("    current_elapsed=$(( $(date +%s) - started_at ))");
                builder.AppendLine("    if [ \"${current_elapsed}\" -ge 180 ]; then");
                builder.AppendLine("      rm -f /tmp/ords-health-body.txt /tmp/ords-health-headers.txt");
                builder.AppendLine("      fail_stage \"ORDS landing endpoint timed out after 180s.\" \"HTTP ${ords_http_status:-missing}; redirect=${ords_redirect_location:-missing}; body=${ords_body_excerpt}\" \"Check the oracle-ords container logs and recreate the ORDS container if configuration did not complete.\"");
                builder.AppendLine("    fi");
                builder.AppendLine("    echo \"[stage] name=${stage_name:-Provisioning} status=waiting waiting_for=ORDS landing elapsed_seconds=${current_elapsed} timeout_seconds=180\" >&2");
                builder.AppendLine("    sleep 10");
                builder.AppendLine("  done");
                builder.AppendLine("}");
                builder.AppendLine("oracle_set_stage 'Validate environment'");
                builder.AppendLine("validate_oracle_environment");
                builder.AppendLine("oracle_set_stage 'Validate Oracle prerequisites'");
                builder.AppendLine("validate_oracle_prerequisites");
                builder.AppendLine("oracle_set_stage 'Install APEX'");
                builder.AppendLine("install_apex_media");
                builder.AppendLine("oracle_set_stage 'Validate ORDS installation'");
                builder.AppendLine("validate_ords_installation");
                builder.AppendLine("oracle_set_stage 'Synchronize ORDS credentials'");
                builder.AppendLine("ensure_ords_public_user_ready");
                builder.AppendLine("oracle_set_stage 'Configure ORDS'");
                builder.AppendLine("wait_for_ords_runtime");
                builder.AppendLine("oracle_set_stage 'Workspace configuration'");
                builder.AppendLine("configure_apex_cdn");
                if (hasOracleApexLang)
                {
                    builder.AppendLine("oracle_set_stage 'Provision Hello APEXlang'");
                    builder.AppendLine("if [ ! -x /workspace/scripts/apexlang-hello-world.sh ]; then");
                    builder.AppendLine("  fail_stage \"APEXlang Hello World provisioning script is missing.\" \"Expected /workspace/scripts/apexlang-hello-world.sh to exist and be executable.\" \"Regenerate the managed workspace files and retry provisioning.\"");
                    builder.AppendLine("fi");
                    builder.AppendLine("/workspace/scripts/apexlang-hello-world.sh");
                }
                builder.AppendLine("oracle_set_stage 'Final verification'");
                builder.AppendLine("complete_stage");
                builder.AppendLine("echo \"[oracle-apex] Stage: Ready\"");
            }

            builder.AppendLine("rm -f \"${oracle_probe_script}\" \"${oracle_sqlplus_probe_script}\" /tmp/sqlcl-probe.out /tmp/sqlplus-probe.out /tmp/sqlcl.zip /tmp/instantclient-basiclite.zip /tmp/instantclient-sqlplus.zip");
            builder.AppendLine("rm -rf /tmp/sqlcl-extract \"${oracle_sqlplus_stage}\"");
        }

        builder.AppendLine();
        builder.AppendLine("# Install OpenCode from the official npm package so the workspace stays close to upstream distribution.");
        builder.AppendLine("begin_stage 'Install OpenCode CLI'");
        builder.AppendLine("run_with_timeout 300 'OpenCode CLI installation' 'Check npm connectivity and retry reprovision.' npm install -g opencode-ai");
        builder.AppendLine("opencode_global_prefix=$(npm prefix -g 2>/dev/null || printf '')");
        builder.AppendLine("if [ -n \"${opencode_global_prefix}\" ] && [ -d \"${opencode_global_prefix}/bin\" ]; then");
        builder.AppendLine("  export PATH=\"${opencode_global_prefix}/bin:${PATH}\"");
        builder.AppendLine("fi");

        if (workspace.Definition.Terminal.InstallIfMissing && string.Equals(workspace.Definition.Terminal.Prompt.Provider, "starship", StringComparison.OrdinalIgnoreCase))
        {
            builder.AppendLine();
            builder.AppendLine("# Install Starship from the official installer when the workspace opts into the recommended prompt.");
            builder.AppendLine("curl -sS https://starship.rs/install.sh | sh -s -- -y");
        }

        if (workspace.NpmPackages.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("# Install additional npm dependencies declared by workspace features.");
            builder.AppendLine($"npm install -g {string.Join(" ", workspace.NpmPackages)}");
        }

        if (workspace.PipPackages.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("# Ubuntu 24.04 marks the system Python as externally managed, so disposable workspace runtimes must opt into global pip installs explicitly.");
            builder.AppendLine($"pip3 install --break-system-packages {string.Join(" ", workspace.PipPackages)}");
        }

        if (workspace.PostInstallCommands.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("# Run feature-specific post-install commands after base tooling is available.");
            foreach (var command in workspace.PostInstallCommands)
            {
                builder.AppendLine(command);
            }
        }

        builder.AppendLine();
        builder.AppendLine("# Add optional terminal utilities from official Ubuntu package repositories.");
        if (workspace.Definition.Terminal.InstallIfMissing && workspace.Definition.Terminal.Utilities.Zoxide)
        {
            builder.AppendLine("apt-get install -y zoxide");
        }

        if (workspace.Definition.Terminal.InstallIfMissing && workspace.Definition.Terminal.Utilities.Fzf)
        {
            builder.AppendLine("apt-get install -y fzf");
        }

        builder.AppendLine();
        builder.AppendLine("# Source the generated OpenCode shell initialization file through a clearly marked managed block.");
        builder.AppendLine("python3 - <<'PY'");
        builder.AppendLine("from pathlib import Path");
        builder.AppendLine($"start = {QuoteForPython(BashRcManagedStart)}");
        builder.AppendLine($"end = {QuoteForPython(BashRcManagedEnd)}");
        builder.AppendLine("block = start + '\\nsource /opt/opencode-workspace/config/opencode-shell-init.sh\\n' + end + '\\n'");
        builder.AppendLine("bashrc = Path('/home/opencode/.bashrc')");
        builder.AppendLine("text = bashrc.read_text() if bashrc.exists() else ''");
        builder.AppendLine("if start in text and end in text:");
        builder.AppendLine("    prefix = text.split(start, 1)[0]");
        builder.AppendLine("    suffix = text.split(end, 1)[1].lstrip('\\n')");
        builder.AppendLine("    bashrc.write_text(prefix + block + suffix)");
        builder.AppendLine("else:");
        builder.AppendLine("    if text and not text.endswith('\\n'):");
        builder.AppendLine("        text += '\\n'");
        builder.AppendLine("    bashrc.write_text(text + block)");
        builder.AppendLine("PY");

        builder.AppendLine();
        builder.AppendLine("# Verify the main tools that contributors expect to exist after provisioning.");
        builder.AppendLine("git --version");
        builder.AppendLine("python --version");
        builder.AppendLine("python3 --version");
        builder.AppendLine("which python");
        builder.AppendLine("which python3");
        builder.AppendLine("node --version");
        builder.AppendLine("node -e \"console.log(process.version)\"");
                builder.AppendLine("npm --version");
                builder.AppendLine("command -v sqlcl");
                builder.AppendLine("sqlcl -v");
                builder.AppendLine("command -v opencode");
        builder.AppendLine("opencode --version");
        builder.AppendLine("run_with_timeout 60 'Attach-user OpenCode validation' 'Rebuild Runtime or inspect the opencode user PATH before retrying.' su -s /bin/bash -c 'command -v opencode && opencode --version' opencode");
        builder.AppendLine("su -s /bin/bash -c 'screen --version' opencode");
        builder.AppendLine("complete_stage");

        if (workspace.Definition.Terminal.InstallIfMissing && string.Equals(workspace.Definition.Terminal.Prompt.Provider, "starship", StringComparison.OrdinalIgnoreCase))
        {
            builder.AppendLine("starship --version");
        }

        if (workspace.Definition.Terminal.InstallIfMissing && workspace.Definition.Terminal.Utilities.Zoxide)
        {
            builder.AppendLine("zoxide --version");
        }

        if (workspace.Definition.Terminal.InstallIfMissing && workspace.Definition.Terminal.Utilities.Fzf)
        {
            builder.AppendLine("fzf --version");
        }

        return builder.ToString();
    }

    private static string QuoteForPython(string value)
        => "'" + value.Replace("'", "\\'", StringComparison.Ordinal) + "'";
}
