namespace OpenCode.Workspace.RemoteBridge;

internal static class RemoteTerminalAssets
{
    public const string Html = """
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenCode Remote Terminal</title><link rel="stylesheet" href="/terminal/vendor/xterm.css"><link rel="stylesheet" href="/terminal/terminal.css"></head>
<body><main><header><div><p class="eyebrow">REMOTE WORKSPACE</p><h1 id="title">Interactive session</h1><small id="identity">{{identity}}</small></div><div id="state" class="state">Authenticated</div></header>
<section class="toolbar"><button id="attach">Attach</button><button id="takeover" class="secondary" hidden>Take over</button><button id="detach" class="secondary" disabled>Detach</button><button id="stop" class="danger" disabled>Stop runtime</button><span id="runtime"></span></section>
<section id="terminal" class="terminal"></section><p id="message">Closing this presentation leaves the LocalHost runtime running.</p></main>
<script src="/terminal/vendor/xterm.js"></script><script src="/terminal/terminal.js"></script></body></html>
""";

    public const string Style = """
:root{color-scheme:dark;font-family:Inter,"Segoe UI",sans-serif;background:#111714;color:#e7eee9}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#213b30 0,transparent 38%),#111714}main{width:min(1180px,100%);min-height:100vh;margin:auto;padding:32px clamp(16px,4vw,52px);display:grid;grid-template-rows:auto auto 1fr auto;gap:16px}header{display:flex;align-items:end;justify-content:space-between;gap:20px}.eyebrow{color:#8cbda5;font-size:11px;letter-spacing:.22em;margin:0 0 8px}h1{margin:0}small,#message,#runtime{color:#91a097}.state{font-size:13px;color:#68d391}.toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:8px;border-bottom:1px solid #35453c;padding-bottom:13px}button{border:1px solid #94c7ab;background:#b7e4cb;color:#102019;padding:8px 14px;border-radius:4px;font-weight:600}button.secondary,button.danger{color:#d8e5dd;background:transparent;border-color:#4d6457}button.danger{margin-left:auto;color:#fecaca}button:disabled{opacity:.4}.terminal{min-height:480px;padding:14px;border:1px solid #35453c;border-radius:6px;background:#080c0aee;overflow:hidden}.terminal .xterm{height:100%}@media(max-width:640px){main{padding-top:20px}header{align-items:start;flex-direction:column}.terminal{min-height:60vh}}
""";

    public const string Script = """
"use strict";
const sessionId=decodeURIComponent(location.pathname.split("/").filter(Boolean).at(-1)||"");
const state=document.querySelector("#state"),message=document.querySelector("#message"),terminal=document.querySelector("#terminal"),attachButton=document.querySelector("#attach"),takeoverButton=document.querySelector("#takeover"),detachButton=document.querySelector("#detach"),stopButton=document.querySelector("#stop"),encoder=new TextEncoder();
let socket,runtime,pendingOutput,afterSequence=0,sequenceKey="",detached=false;
globalThis.DotNet={invokeMethod(){return true},invokeMethodAsync(_a,m,_id,v){if(!socket||socket.readyState!==WebSocket.OPEN)return Promise.resolve();if(m==="OnData")socket.send(encoder.encode(v));if(m==="OnBinary")socket.send(Uint8Array.from(v,c=>c.charCodeAt(0)&255));if(m==="OnResize")socket.send(JSON.stringify({type:"resize",columns:v.columns,rows:v.rows}));return Promise.resolve()}};
XtermBlazor.registerTerminal("remote-terminal",terminal,{convertEol:false,cursorBlink:true,fontFamily:'"Cascadia Mono",Consolas,monospace',fontSize:14,scrollback:5000,theme:{background:"#080c0a",foreground:"#d9e8df"}},[]);const xterm=XtermBlazor.getTerminalById("remote-terminal");
function setState(value){state.textContent=value}async function api(path,options={}){const response=await fetch(`/api/v1/remote${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})},cache:"no-store"});const body=await response.json();if(!response.ok){const error=new Error(body.message||`HTTP ${response.status}`);error.code=body.code;throw error}return body}
async function refresh(){const session=await api(`/sessions/${encodeURIComponent(sessionId)}`);document.querySelector("#title").textContent=session.title||"Interactive session";runtime=await api(`/sessions/${encodeURIComponent(sessionId)}/terminal`);sequenceKey=`remote-terminal-sequence:${sessionId}:${runtime.runtimeId}`;afterSequence=Number(sessionStorage.getItem(sequenceKey)||0);document.querySelector("#runtime").textContent=`Runtime ${runtime.runtimeId}`}
async function attach(takeover=false){setState("Connecting");detached=false;try{await refresh();const grant=await api(`/sessions/${encodeURIComponent(sessionId)}/attachment-grants`,{method:"POST",body:JSON.stringify({takeover})});openSocket(grant,takeover)}catch(error){if(error.code==="already_attached"){setState("Takeover required");takeoverButton.hidden=false}else setState("Disconnected");message.textContent=error.message}}
function openSocket(grant,takeover){const scheme=location.protocol==="https:"?"wss":"ws";socket=new WebSocket(`${scheme}://${location.host}/api/v1/remote/sessions/${encodeURIComponent(sessionId)}/terminal/ws`,"opencode-terminal-v1");socket.binaryType="arraybuffer";socket.onopen=()=>socket.send(JSON.stringify({type:"hello",sessionId,runtimeId:runtime.runtimeId,afterSequence,takeover,grantToken:grant.grantToken}));socket.onmessage=e=>{if(typeof e.data==="string"){const c=JSON.parse(e.data);if(c.type==="attached"){setState("Attached");detachButton.disabled=false;stopButton.disabled=false;takeoverButton.hidden=true;message.textContent="Input is sent only to the active canonical attachment.";xterm.focus();socket.send(JSON.stringify({type:"resize",columns:xterm.cols,rows:xterm.rows}))}else if(c.type==="output")pendingOutput=c;else if(c.type==="gap"){afterSequence=Math.max(0,c.earliestAvailableSequence-1);xterm.writeln("\r\n[Earlier terminal output is no longer buffered.]")}else if(c.type==="runtime_state"){setState("Runtime exited");message.textContent=`Runtime state: ${c.runtimeStatus}`}else if(c.type==="detach"){detached=true;setState("Detached");message.textContent=c.message||"This presentation was detached."}else if(c.type==="error"){setState("Disconnected");message.textContent=c.message}}else if(pendingOutput){const output=pendingOutput;pendingOutput=undefined;xterm.write(new Uint8Array(e.data),()=>{afterSequence=output.sequence;sessionStorage.setItem(sequenceKey,String(afterSequence));if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:"ack",sequence:afterSequence}))})}};socket.onclose=()=>{detachButton.disabled=true;stopButton.disabled=true;pendingOutput=undefined;socket=undefined;runtime=undefined;if(detached)setState("Detached");else if(state.textContent!=="Runtime exited")setState("Disconnected")};socket.onerror=()=>setState("Disconnected")}
new ResizeObserver(entries=>{const box=entries[0].contentRect,columns=Math.max(20,Math.min(500,Math.floor((box.width-40)/8.4))),rows=Math.max(5,Math.min(300,Math.floor((box.height-40)/20.3)));if(columns!==xterm.cols||rows!==xterm.rows)xterm.resize(columns,rows)}).observe(terminal);
attachButton.onclick=()=>attach(false);takeoverButton.onclick=()=>attach(true);detachButton.onclick=()=>{if(socket?.readyState===WebSocket.OPEN){detached=true;setState("Detaching");socket.send(JSON.stringify({type:"detach"}))}};stopButton.onclick=()=>{if(confirm("Stop the terminal runtime?"))socket?.send(JSON.stringify({type:"stop"}))};refresh().catch(error=>{setState("Disconnected");message.textContent=error.message});
""";
}
