using OpenCode.Workspace.Core.Catalog;
using OpenCode.Workspace.Core.Generation;
using OpenCode.Workspace.Core.Models;
using OpenCode.Workspace.Core.Workspaces;
using Xunit;

namespace OpenCode.Workspace.Core.Tests;

public sealed class GeneratedArtifactsTests
{
    [Fact]
    public void ComposeGenerator_IncludesGeneratedHeaderAndServices()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Name = "demo-workspace",
                Image = "ubuntu:24.04",
            },
            Features = new List<string> { "core" },
            Services = new List<string> { "postgres", "pgadmin" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = new[]
            {
                new ServiceManifest
                {
                    Id = "postgres",
                    Image = "postgres:17",
                    HostPorts = new List<string> { "15432:5432" },
                    Environment = new Dictionary<string, string> { ["POSTGRES_DB"] = "app" },
                    Volumes = new List<string> { "postgres-data:/var/lib/postgresql/data" },
                },
                new ServiceManifest
                {
                    Id = "pgadmin",
                    Image = "dpage/pgadmin4:9",
                    HostPorts = new List<string> { "18080:80" },
                    DependsOn = new List<string> { "postgres" },
                },
            },
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "demo-workspace"));
        var compose = generator.Generate(resolved, paths);
        var header = ReadHeader(compose);

        Assert.Contains("# Generated by OpenCode Workspace Manager", header);
        Assert.Contains("container_name: demo-workspace-workspace", compose);
        Assert.Contains("  postgres:", compose);
        Assert.Contains("  pgadmin:", compose);
        Assert.Contains("volumes:", compose);
    }

    [Fact]
    public void ComposeGenerator_ForWorkspaceWithoutServices_OmitsWorkspaceDependsOn()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Id = "odip-analiza",
                Name = "Odip Analiza",
                Image = "ubuntu:24.04",
            },
            Provider = new WorkspaceProviderDefinition
            {
                Type = "git",
                Url = "git@ssh.dev.azure.com:v3/KOPA-Projects/ODIP/Analiza",
            },
            Runtime = new WorkspaceRuntimeDefinition
            {
                Default = "default",
            },
            Features = new List<string> { "core", "document-processing", "ocr-processing", "spellcheck" },
            Services = new List<string>(),
            Skills = new List<string>(),
            Mcp = new List<string>(),
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "odip-analiza"));
        var compose = generator.Generate(resolved, paths);

        Assert.DoesNotContain("depends_on:", compose);
    }

    [Fact]
    public void ComposeGenerator_ForSimpleWorkspaceDependencies_UsesArrayForm()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Name = "analiza-with-db",
                Image = "ubuntu:24.04",
            },
            Features = new List<string> { "core" },
            Services = new List<string> { "oracle" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = new[]
            {
                new ServiceManifest
                {
                    Id = "oracle",
                    Image = "gvenzl/oracle-free:23-slim-faststart",
                },
            },
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "analiza-with-db"));
        var compose = generator.Generate(resolved, paths);

        Assert.Contains("    depends_on:", compose);
        Assert.Contains("      - oracle", compose);
        Assert.DoesNotContain("condition:", compose);
    }

    [Fact]
    public void ComposeGenerator_ForConditionalWorkspaceDependencies_UsesObjectForm()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Name = "oracle-demo",
                Image = "ubuntu:24.04",
            },
            Features = new List<string> { "core", "oracle-demo" },
            Services = new List<string> { "oracle-demo" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = new[]
            {
                new ServiceManifest
                {
                    Id = "oracle-demo",
                    Image = "gvenzl/oracle-free:23-slim-faststart",
                    WorkspaceDependsOnCondition = "service_healthy",
                },
            },
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "oracle-demo"));
        var compose = generator.Generate(resolved, paths);

        Assert.Contains("    depends_on:", compose);
        Assert.Contains("      oracle-demo:", compose);
        Assert.Contains("        condition: service_healthy", compose);
    }

    [Fact]
    public void ComposeGenerator_ForWindowsBindMountServiceVolume_DoesNotDeclareDriveLetterAsNamedVolume()
    {
        var generator = new ComposeGenerator();
        var resolved = new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata
                {
                    Name = "windows-bind-demo",
                    Image = "ubuntu:24.04",
                },
                Features = new List<string> { "core" },
                Services = new List<string> { "files" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services =
            [
                new ServiceManifest
                {
                    Id = "files",
                    Image = "ubuntu:24.04",
                    Volumes = new List<string> { "C:/workspace/cache:/cache" },
                },
            ],
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var compose = generator.Generate(resolved, WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "windows-bind-demo")));

        Assert.DoesNotContain("\nvolumes:\n  C:\n", compose, StringComparison.Ordinal);
    }

    [Fact]
    public void ComposeGenerator_ForWindowsWorkspacePaths_DoesNotTreatDriveLetterAsNamedVolume()
    {
        var generator = new ComposeGenerator();
        var resolved = new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata
                {
                    Name = "windows-paths-demo",
                    Image = "ubuntu:24.04",
                },
                Features = new List<string> { "core" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = new WorkspacePaths
        {
            RootPath = "C:/workspaces/windows-paths-demo",
            GitIgnorePath = "C:/workspaces/windows-paths-demo/.gitignore",
            OpencodePath = "C:/workspaces/windows-paths-demo/.opencode",
            OpencodeLocalPath = "C:/workspaces/windows-paths-demo/.opencode/local",
            WorkspaceYamlRelativePath = "workspace.yaml",
            WorkspaceYamlPath = "C:/workspaces/windows-paths-demo/workspace.yaml",
            ComposePath = "C:/workspaces/windows-paths-demo/compose.yaml",
            EnvironmentFilePath = "C:/workspaces/windows-paths-demo/.env",
            MountsRootPath = "C:/workspaces/windows-paths-demo/mounts",
            InboxPath = "C:/workspaces/windows-paths-demo/mounts/inbox",
            WorkspacePath = "C:/workspaces/windows-paths-demo",
            UserPath = "C:/workspaces/windows-paths-demo/mounts/user",
            HomePath = "C:/workspaces/windows-paths-demo/mounts/home",
            ConfigPath = "C:/workspaces/windows-paths-demo/mounts/config",
            ProvisionScriptPath = "C:/workspaces/windows-paths-demo/mounts/config/provision.sh",
            StarshipConfigPath = "C:/workspaces/windows-paths-demo/mounts/config/starship.toml",
            ShellInitScriptPath = "C:/workspaces/windows-paths-demo/mounts/config/opencode-shell-init.sh",
            OpencodeWorkspaceShellPath = "C:/workspaces/windows-paths-demo/mounts/config/opencode-workspace-shell.sh",
            ScreenConfigPath = "C:/workspaces/windows-paths-demo/mounts/config/screenrc",
            AttachWrapperScriptPath = "C:/workspaces/windows-paths-demo/attach-workspace.ps1",
            AttachDiagnosticsLogPath = "C:/workspaces/windows-paths-demo/attach-diagnostics.log",
            TerminalDiagnosticsScriptPath = "C:/workspaces/windows-paths-demo/terminal-diagnostics.ps1",
            RuntimeStatePath = "C:/workspaces/windows-paths-demo/.opencode/local/runtime-state.yaml",
            AppliedStatePath = "C:/workspaces/windows-paths-demo/mounts/config/applied-state.yaml",
            HistoryPath = "C:/workspaces/windows-paths-demo/history",
            CheckpointsPath = "C:/workspaces/windows-paths-demo/history/checkpoints",
            CheckpointIndexPath = "C:/workspaces/windows-paths-demo/history/checkpoints/index.yaml",
            TimelinePath = "C:/workspaces/windows-paths-demo/history/timeline.yaml",
            RuntimesPath = "C:/workspaces/windows-paths-demo/runtimes",
            DefaultRuntimePath = "C:/workspaces/windows-paths-demo/runtimes/default.yaml",
            ArtifactsPath = "C:/workspaces/windows-paths-demo/artifacts",
            ArtifactRunsPath = "C:/workspaces/windows-paths-demo/artifacts/runs",
            ArtifactIndexPath = "C:/workspaces/windows-paths-demo/artifacts/index.json",
        };

        var compose = generator.Generate(resolved, paths);

        Assert.Contains("      - C:/workspaces/windows-paths-demo:/workspace", compose, StringComparison.Ordinal);
    }

    [Fact]
    public void EnvironmentFileGenerator_IncludesOracleDefaultsForOracleDemoWorkspaces()
    {
        var generator = new EnvironmentFileGenerator();
        var content = generator.Generate(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-demo" },
            Services = new List<string> { "oracle-demo" },
        });

        Assert.Contains("ORACLE_DEPLOYMENT_PROFILE=plsql", content);
        Assert.Contains("ORACLE_HOST=oracle-demo", content);
        Assert.Contains("ORACLE_PORT=1521", content);
        Assert.Contains("ORACLE_SERVICE_NAME=FREEPDB1", content);
        Assert.Contains("ORACLE_ADMIN_USER=SYS", content);
        Assert.Contains("ORACLE_PASSWORD=change-on-first-demo", content);
        Assert.Contains("ORACLE_DEMO_USERNAME=demo_user", content);
        Assert.Contains("ORACLE_DEMO_PASSWORD=demo_password", content);
        Assert.Contains("ORACLE_DEMO_CONNECTION=demo_user/demo_password@//oracle-demo:1521/FREEPDB1", content);
        Assert.Contains("ORACLE_HOST_PORT=1521", content);
        Assert.Contains("ORACLE_ORDS_BASE_URL=http://localhost:8181/ords", content);
    }

    [Fact]
    public void WorkspaceContentGenerator_OracleApexWorkspace_IncludesOrdsBootstrapScript()
    {
        var provider = new BuiltInCatalogProvider(TestPaths.CatalogRoot);
        var resolver = new WorkspaceResolver(provider.LoadFeatures(), provider.LoadServices(), provider.LoadCapabilities(), provider.LoadKnowledgePacks());
        var resolved = resolver.Resolve(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        });

        var files = new WorkspaceContentGenerator().Generate(resolved);

        Assert.True(files.TryGetValue(Path.Combine("mounts", "config", "ords", "init-ords-config.sh"), out var script));
        Assert.Contains("validate_required_ords_config", script, StringComparison.Ordinal);
        Assert.Contains("[ords] Effective user: uid=", script, StringComparison.Ordinal);
        Assert.Contains("[ords] Path state:", script, StringComparison.Ordinal);
        Assert.Contains("[ords] Logs directory writable: yes", script, StringComparison.Ordinal);
        Assert.Contains("ords --config \"${config_dir}\" install --config-only", script, StringComparison.Ordinal);
        Assert.Contains("--gateway-user \"${ORACLE_APEX_PUBLIC_USER:-APEX_PUBLIC_USER}\"", script, StringComparison.Ordinal);
        Assert.Contains("exec ords --config \"${config_dir}\" serve --port 8080", script, StringComparison.Ordinal);
        Assert.DoesNotContain("chmod -R 777", script, StringComparison.Ordinal);
        Assert.DoesNotContain("echo \"${ORACLE_PASSWORD}\"", script, StringComparison.Ordinal);
        Assert.DoesNotContain("echo \"${ords_public_password}\"", script, StringComparison.Ordinal);
    }

    [Fact]
    public void WorkspaceContentGenerator_GeneratesWorkspaceServicesGuide()
    {
        var provider = new BuiltInCatalogProvider(TestPaths.CatalogRoot);
        var resolver = new WorkspaceResolver(provider.LoadFeatures(), provider.LoadServices(), provider.LoadCapabilities(), provider.LoadKnowledgePacks());
        var resolved = resolver.Resolve(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        });

        var files = new WorkspaceContentGenerator().Generate(resolved);

        Assert.True(files.TryGetValue(Path.Combine("docs", "workspace-services.md"), out var guide));
        Assert.Contains("# Available Services", guide, StringComparison.Ordinal);
        Assert.Contains("APEX Builder", guide, StringComparison.Ordinal);
        Assert.Contains("ORDS Landing", guide, StringComparison.Ordinal);
        Assert.Contains("SQLcl", guide, StringComparison.Ordinal);
        Assert.Contains("Development Shell", guide, StringComparison.Ordinal);
    }

    [Fact]
    public void WorkspaceContentGenerator_GeneratesOracleApexWorkflowGuide()
    {
        var provider = new BuiltInCatalogProvider(TestPaths.CatalogRoot);
        var resolver = new WorkspaceResolver(provider.LoadFeatures(), provider.LoadServices(), provider.LoadCapabilities(), provider.LoadKnowledgePacks());
        var resolved = resolver.Resolve(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        });

        var files = new WorkspaceContentGenerator().Generate(resolved);

        Assert.True(files.TryGetValue(Path.Combine("docs", "oracle-apex-workflow.md"), out var guide));
        Assert.Contains("Connect Existing Application", guide, StringComparison.Ordinal);
        Assert.Contains("Validate", guide, StringComparison.Ordinal);
        Assert.Contains("Show Diff", guide, StringComparison.Ordinal);
        Assert.Contains("Pull", guide, StringComparison.Ordinal);
        Assert.Contains("Push", guide, StringComparison.Ordinal);
        Assert.Contains("Oracle Diagnostics", guide, StringComparison.Ordinal);
    }

    [Fact]
    public void WorkspaceServiceCatalog_OracleApexWorkspace_ExposesPolishedOracleServices()
    {
        var services = WorkspaceServiceCatalog.Build(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
            Oracle = new OracleWorkspacePreferences
            {
                Apex = new OracleApexWorkspacePreferences
                {
                    DefaultEnvironment = "dev",
                    Environments = new Dictionary<string, OracleApexEnvironmentPreferences>
                    {
                        ["dev"] = new() { Workspace = "TEST", ParsingSchema = "TESTSCHEMA", ApplicationId = 100, SourcePath = "src/apex" },
                    },
                },
            },
        });

        Assert.Contains(services, item => item.Name == "APEX Builder");
        Assert.Contains(services, item => item.Name == "App Home");
        Assert.Contains(services, item => item.Name == "SQL Workshop");
        Assert.Contains(services, item => item.Name == "REST Workshop");
        Assert.Contains(services, item => item.Name == "ORDS Landing");
        Assert.Contains(services, item => item.Name == "SQLcl Terminal");
        Assert.Contains(services, item => item.Name == "Oracle Diagnostics");
        Assert.Contains(services, item => item.Name == "Open Atlas");
        Assert.Contains(services, item => item.Name == "Browse Pages");
        Assert.Contains(services, item => item.Name == "Browse Shared Components");
        Assert.Contains(services, item => item.Name == "Search Application");
        Assert.Contains(services, item => item.Name == "Dependency Graph");
    }

    [Fact]
    public void WorkspaceServiceCatalog_GenericWorkspace_ExposesTerminalFolderAndCli()
    {
        var services = WorkspaceServiceCatalog.Build(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "general-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core" },
            Services = new List<string>(),
        }, workspaceRootPath: @"C:\workspaces\general-demo");

        Assert.Contains(services, item => item.Name == "Development Shell");
        Assert.Contains(services, item => item.Name == "Repository Folder");
        Assert.Contains(services, item => item.Name == "OpenCode CLI");
    }

    [Fact]
    public void ProvisioningScriptGenerator_OracleApexWorkspace_ReportsMissingOrdsConfigClearly()
    {
        var provider = new BuiltInCatalogProvider(TestPaths.CatalogRoot);
        var resolver = new WorkspaceResolver(provider.LoadFeatures(), provider.LoadServices(), provider.LoadCapabilities(), provider.LoadKnowledgePacks());
        var resolved = resolver.Resolve(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        });

        var script = new OracleWorkspaceProvisioningScriptGenerator().Generate(resolved);

        Assert.Contains("oracle_required_config=(\"ORACLE_DEPLOYMENT_PROFILE\" \"ORACLE_HOST\" \"ORACLE_PORT\" \"ORACLE_SERVICE_NAME\" \"ORACLE_ADMIN_USER\" \"ORACLE_PASSWORD\" \"ORACLE_DEMO_USERNAME\" \"ORACLE_DEMO_PASSWORD\" \"ORACLE_ORDS_INTERNAL_BASE_URL\" \"ORACLE_ORDS_PUBLIC_USER\" \"ORACLE_ORDS_PUBLIC_PASSWORD\" \"ORACLE_APEX_PUBLIC_USER\" \"ORACLE_APEX_MEDIA_DIR\" \"ORACLE_APEX_MEDIA_PREFERRED_ZIP\")", script, StringComparison.Ordinal);
        Assert.Contains("Missing configuration values: %s", script, StringComparison.Ordinal);
        Assert.Contains("Active deployment profile", script, StringComparison.Ordinal);
        Assert.Contains("Oracle host", script, StringComparison.Ordinal);
        Assert.Contains("Oracle port", script, StringComparison.Ordinal);
        Assert.Contains("Oracle service name", script, StringComparison.Ordinal);
        Assert.Contains("Oracle administrative user", script, StringComparison.Ordinal);
        Assert.Contains("oracle_connection=\"${ORACLE_DEMO_USERNAME}/${ORACLE_DEMO_PASSWORD}@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE_NAME}\"", script, StringComparison.Ordinal);
        Assert.Contains("oracle_sysdba_connection=\"${ORACLE_ADMIN_USER}/${ORACLE_PASSWORD}@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE_NAME} as sysdba\"", script, StringComparison.Ordinal);
        Assert.Contains("ALTER SESSION SET CONTAINER = ${ORACLE_SERVICE_NAME};", script, StringComparison.Ordinal);
        Assert.Contains("ALTER USER ${ORACLE_ORDS_PUBLIC_USER} IDENTIFIED BY \"${ORACLE_ORDS_PUBLIC_PASSWORD}\" ACCOUNT UNLOCK;", script, StringComparison.Ordinal);
        Assert.Contains("oracle_ords_landing_url=\"${ORACLE_ORDS_INTERNAL_BASE_URL}/_/landing\"", script, StringComparison.Ordinal);
        Assert.Contains("Oracle REST Data Services is not installed in the database.", script, StringComparison.Ordinal);
        Assert.Contains("Oracle REST Data Services database user could not be synchronized.", script, StringComparison.Ordinal);
    }

    [Fact]
    public void EnvironmentFileGenerator_IncludesMarimoPortForAnalyticsWorkspace()
    {
        var generator = new EnvironmentFileGenerator();
        var content = generator.Generate(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "analytics-demo" },
            Features = new List<string> { "core", "analytics-reporting" },
            Analytics = new AnalyticsWorkspacePreferences { MarimoPort = 3818 },
        });

        Assert.Contains("MARIMO_PORT=3818", content);
    }

    [Fact]
    public void EnvironmentFileGenerator_UsesLfLineEndingsWithoutCarriageReturns()
    {
        var generator = new EnvironmentFileGenerator();
        var content = generator.Generate(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "Odip Analiza" },
        });

        Assert.DoesNotContain('\r', content);
        Assert.Contains("\nWORKSPACE_NAME=Odip Analiza\n", content, StringComparison.Ordinal);
    }

    [Fact]
    public void ComposeGenerator_ForAnalyticsWorkspace_UsesLoopbackOnlyMarimoPortMapping()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "analytics-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "analytics-reporting" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var compose = generator.Generate(resolved, WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "analytics-demo")));

        Assert.Contains("127.0.0.1:${MARIMO_PORT}:2718", compose);
    }

    [Fact]
    public void ComposeGenerator_ForWorkspaceWithoutAnalytics_DoesNotExposeMarimoPort()
    {
        var generator = new ComposeGenerator();
        var resolved = new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "core-only", Image = "ubuntu:24.04" },
                Features = new List<string> { "core" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var compose = generator.Generate(resolved, WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "core-only")));
        Assert.DoesNotContain("MARIMO_PORT", compose);
        Assert.DoesNotContain("127.0.0.1:${MARIMO_PORT}:2718", compose);
    }

    [Fact]
    public void ProvisioningGenerator_IncludesGeneratedHeaderAndOpenCodeInstall()
    {
        var resolved = new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "demo" },
                Terminal = new TerminalPreferences
                {
                    Prompt = new TerminalPromptPreferences { Provider = "starship" },
                    Utilities = new TerminalUtilityPreferences { Zoxide = true, Fzf = true },
                },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "git", "curl" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };
        var script = new ProvisioningScriptGenerator().Generate(resolved);
        var toolingScript = new WorkspaceImageToolingScriptGenerator().Generate(resolved);
        var initScript = new WorkspaceInitializationScriptGenerator().Generate(resolved);
        var validateScript = new WorkspaceInitializationScriptGenerator().GenerateValidation(resolved);

        Assert.Contains("# Generated by OpenCode Workspace Manager", ReadHeader(script));
        Assert.Contains("bash /opt/opencode-workspace/config/workspace-init.sh", script);
        Assert.Contains("bash /opt/opencode-workspace/config/workspace-validate.sh", script);
        Assert.Contains("apt-get install -y git curl", toolingScript);
        Assert.Contains("https://deb.nodesource.com/setup_22.x", toolingScript);
        Assert.Contains("apt-get remove -y nodejs npm || true", toolingScript);
        Assert.Contains("apt-get install -y nodejs", toolingScript);
        Assert.Contains("npm install -g opencode-ai", toolingScript);
        Assert.Contains("curl -sS https://starship.rs/install.sh | sh -s -- -y", toolingScript);
        Assert.Contains("useradd -m -d /home/opencode -s /bin/bash opencode", initScript);
        Assert.Contains("source /opt/opencode-workspace/config/opencode-shell-init.sh", initScript);
        Assert.Contains("python --version", validateScript);
        Assert.Contains("python3 --version", validateScript);
        Assert.Contains("which python", validateScript);
        Assert.Contains("which python3", validateScript);
        Assert.Contains("node -e \"console.log(process.version)\"", validateScript);
        Assert.Contains("command -v opencode", validateScript);
        Assert.Contains("opencode --version", validateScript);
        Assert.Contains("su -s /bin/bash -c 'command -v opencode && opencode --version' opencode", validateScript);
        Assert.DoesNotContain(". /workspace/.env", script, StringComparison.Ordinal);
        Assert.Contains("env_line=${env_line%$'\\r'}", script, StringComparison.Ordinal);
        Assert.Contains("export \"${env_key}=${env_value}\"", script, StringComparison.Ordinal);
        Assert.Contains("begin_stage()", script);
        Assert.Contains("complete_stage()", script);
        Assert.Contains("fail_stage()", script);
        Assert.Contains("trap 'fail_stage \"Provisioning command failed.\"", script);
        Assert.Contains("begin_stage 'Initializing Workspace'", script);
        Assert.Contains("begin_stage 'Final Validation'", script);
    }

    [Fact]
    public void ProvisioningGenerator_ForOracleWorkspace_UsesDynamicLibaioHelper()
    {
        var workspace = new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-demo" },
                Features = new List<string> { "core", "oracle-demo" },
                Services = new List<string> { "oracle-demo" },
                Terminal = new TerminalPreferences
                {
                    Prompt = new TerminalPromptPreferences { Provider = "starship" },
                    Utilities = new TerminalUtilityPreferences(),
                },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "curl", "rlwrap", "unzip", "libaio1" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };
        var generator = new WorkspaceImageToolingScriptGenerator();
        var script = generator.Generate(workspace);
        var oracleLayer = generator.GenerateLayout(workspace).LayerScripts.Single(layer => string.Equals(layer.CategoryId, WorkspaceImageToolingLayoutBuilder.OracleToolingCategory, StringComparison.OrdinalIgnoreCase)).Content;

        Assert.Contains("Detected Ubuntu version", script);
        Assert.Contains("oracle_log_phase 'Installing Oracle runtime libraries'", script);
        Assert.Contains("oracle_log_phase 'Installing Java'", script);
        Assert.Contains("oracle_log_phase 'Downloading SQLcl'", script);
        Assert.Contains("oracle_log_phase 'Extracting SQLcl'", script);
        Assert.Contains("oracle_log_phase 'Configuring SQLcl'", script);
        Assert.Contains("oracle_log_phase 'Configuring SQLPlus runtime libraries'", script);
        Assert.Contains("oracle_log_phase 'Validating SQLcl'", script);
        Assert.Contains("oracle_log_phase 'Validating SQLPlus'", script);
        Assert.Contains("Selected libaio package", script);
        Assert.Contains("if apt-cache policy libaio1 | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("elif apt-cache policy libaio1t64 | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("dpkg -L \"${oracle_libaio_pkg}\"", script);
        Assert.Contains("ln -sf /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1", script);
        Assert.Contains("ldconfig", script);
        Assert.Contains("Selected Java package", script);
        Assert.Contains("if apt-cache policy openjdk-21-jre-headless | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("elif apt-cache policy openjdk-17-jre-headless | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("No compatible Java runtime package found for SQLcl", script);
        Assert.Contains("oracle_sqlplus_root=/opt/oracle/instantclient", script);
        Assert.Contains("instantclient-basiclite-linux.x64", script);
        Assert.Contains("instantclient-sqlplus-linux.x64", script);
        Assert.Contains("/etc/ld.so.conf.d/oracle-instantclient.conf", script);
        Assert.Contains("export ORACLE_CLIENT_HOME=${oracle_client_home}", script);
        Assert.Contains("oracle_print_directory_listing()", script);
        Assert.Contains("oracle_print_directory_listing \"${oracle_sqlplus_stage}\" 'Extracted Oracle Instant Client directories'", script);
        Assert.Contains("oracle_print_directory_listing \"${oracle_sqlplus_root}\" 'Installed Oracle Instant Client directories'", script);
        Assert.Contains("oracle_client_home=$(oracle_resolve_client_home \"${oracle_sqlplus_root}\")", script);
        Assert.Contains("cat > /usr/local/bin/opencode-oracle-client-home <<'EOF'", script);
        Assert.Contains("oracle_current_link=\"${oracle_sqlplus_root}/current\"", script);
        Assert.Contains("oracle_client_home=$(readlink -f \"${oracle_current_link}\")", script);
        Assert.Contains("Oracle Instant Client libsqlplus.so was not found under %s", script);
        Assert.Contains("Oracle Instant Client libclntsh.so was not found under %s", script);
        Assert.Contains("Located libsqlplus.so files", script);
        Assert.Contains("Discovered Oracle client home", script);
        Assert.Contains("Using libsqlplus.so: ${resolved}/libsqlplus.so", script);
        Assert.Contains("Multiple Oracle client homes were discovered under ${root}", script);
        Assert.Contains("current symlink -> $(readlink -f \"${oracle_sqlplus_root}/current\")", script);
        Assert.Contains("if ls \"${candidate_dir}\"/libclntsh.so* >/dev/null 2>&1; then", script);
        Assert.Contains("cat > /usr/local/bin/sqlplus <<'EOF'", script);
        Assert.Contains("oracle_client_home=$(/usr/local/bin/opencode-oracle-client-home)", script);
        Assert.Contains("export LD_LIBRARY_PATH=\"${oracle_client_home}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}\"", script);
        Assert.Contains("exec \"${oracle_client_home}/sqlplus\" \"$@\"", script);
        Assert.Contains("oracle_sqlcl_extract=/tmp/sqlcl-extract", script);
        Assert.Contains("cp -a \"${oracle_sqlcl_extract}/.\" /opt/sqlcl/", script);
        Assert.Contains("cat > /usr/local/bin/sql <<'EOF'", script);
        Assert.Contains("exec /opt/sqlcl/sqlcl/bin/sql \"$@\"", script);
        Assert.Contains("ln -sf /usr/local/bin/sql /usr/local/bin/sqlcl", script);
        Assert.Contains("oracle_log_validation_context \"${oracle_client_home}\"", script);
        Assert.Contains("[oracle] Validation client home: ${client_home}", script);
        Assert.Contains("[oracle] Validation LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:-<empty>}", script);
        Assert.Contains("[oracle] readlink -f /opt/oracle/instantclient/current", script);
        Assert.Contains("[oracle] ls -la /opt/oracle/instantclient/current", script);
        Assert.Contains("[oracle] ls -la ${client_home}", script);
        Assert.Contains("[oracle] ldd $(command -v sqlplus)", script);
        Assert.Contains("[oracle] Running validation command: sqlplus -version", script);
        Assert.Contains("[oracle] Running validation command: sql -version", script);
        Assert.Contains("[oracle] Running validation command: sqlcl -version", script);
        Assert.Contains("oracle_validate_sqlplus_runtime \"${oracle_client_home}\"", script);
        Assert.Contains("ldconfig output does not list libsqlplus.so", script);
        Assert.Contains("sqlplus still has unresolved shared libraries", script);
        Assert.Contains("SQLcl extraction did not produce", script);
        Assert.Contains("oracle_require_file /opt/sqlcl/sqlcl/bin/sql 'SQLcl launcher'", script);
        Assert.Contains("oracle_require_file /tmp/instantclient-sqlplus.zip 'Oracle Instant Client sqlplus archive'", script);
        Assert.Contains("cp -a \"${oracle_sqlplus_stage}/.\" \"${oracle_sqlplus_root}/\"", script);
        Assert.Contains("Searched for libsqlplus.so under ${root} but did not find any matches", script);
        Assert.Contains("set -Eeuo pipefail", oracleLayer);
        Assert.Contains("trap 'echo \"[oracle] ERROR: command failed on line ${LINENO}: ${BASH_COMMAND}\" >&2' ERR", oracleLayer);
        Assert.Contains("sql -version", script);
        Assert.Contains("sqlcl -version", script);
        Assert.Contains("sqlplus -version", script);
        Assert.Contains("command -v sqlplus", script);
        Assert.Contains("java -version", script);
        Assert.DoesNotContain("find \"${oracle_sqlplus_root}\" -maxdepth 2 -type f -name 'libsqlplus.so'", script);
        Assert.DoesNotContain("apt-get install -y curl rlwrap unzip libaio1", script);
    }

    [Fact]
    public void ProvisioningGenerator_ForOracleApexWorkspace_WaitsForOrdsAndApex()
    {
        var script = new OracleWorkspaceProvisioningScriptGenerator().Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-apex-demo" },
                Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo" },
                Services = new List<string> { "oracle-demo", "oracle-ords" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "curl", "rlwrap", "unzip" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.Contains("ORACLE_ORDS_INTERNAL_BASE_URL", script);
        Assert.Contains("oracle_ords_landing_url=\"${ORACLE_ORDS_INTERNAL_BASE_URL}/_/landing\"", script);
        Assert.Contains("oracle_demo_user_setup_script=/tmp/oracle-demo-user-setup.sql", script);
        Assert.Contains("ensure_demo_user_ready()", script);
        Assert.Contains("apex_registry_status=$(printf '%s' \"${apex_registry}\" | awk -F'|' '{print $3}')", script);
        Assert.Contains("if [ -n \"${apex_registry}\" ] && [ \"${apex_registry_status}\" = 'VALID' ]", script);
        Assert.Contains("[oracle-apex] APEX already installed: ${apex_registry}", script);
        Assert.Contains("ALTER USER ${ORACLE_DEMO_USERNAME} IDENTIFIED BY \"${ORACLE_DEMO_PASSWORD}\" ACCOUNT UNLOCK", script);
        Assert.Contains("Oracle administrator password does not match the running database.", script);
        Assert.Contains("wait_for_ords_runtime()", script);
        Assert.Contains("ensure_ords_public_user_ready()", script);
        Assert.Contains("SELECT COUNT(*) FROM dba_users WHERE username = UPPER('${ORACLE_ORDS_PUBLIC_USER}');", script);
        Assert.Contains("SELECT COUNT(*) FROM dba_users WHERE username = 'ORDS_METADATA';", script);
        Assert.Contains("Oracle REST Data Services is not installed in the database.", script);
        Assert.Contains("ALTER USER ${ORACLE_ORDS_PUBLIC_USER} IDENTIFIED BY \"${ORACLE_ORDS_PUBLIC_PASSWORD}\" ACCOUNT UNLOCK;", script);
        Assert.Contains("oracle_set_stage 'Installing APEX'", script);
        Assert.Contains("oracle_set_stage 'Configuring ORDS'", script);
        Assert.Contains("command -v sqlplus >/dev/null 2>&1", script);
        Assert.Contains("command -v sqlcl >/dev/null 2>&1", script);
        Assert.Contains("SELECT comp_id || '|' || comp_name || '|' || version || '|' || status || '|' || modified FROM dba_registry WHERE comp_id = 'XDB';", script);
        Assert.DoesNotContain("TO_CHAR(modified", script, StringComparison.Ordinal);
        Assert.Contains("Oracle XML Database (XDB) is invalid.", script);
        Assert.Contains("PROMPT __OPENCODE_RESULT_BEGIN__", script);
    }

    [Fact]
    public void ProvisioningGenerator_ForOracleApexlangWorkspace_UsesShellContextForOracleDemoUserTimeout()
    {
        var script = new OracleWorkspaceProvisioningScriptGenerator().Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo" },
                Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
                Services = new List<string> { "oracle-demo", "oracle-ords" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "curl", "rlwrap", "unzip" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.Contains("ensure_demo_user_ready()", script);
        Assert.Contains("local setup_script=/tmp/oracle-demo-user-setup.sql", script);
        Assert.Contains("oracle_set_stage 'Creating Sample Application'", script);
        Assert.Contains("/workspace/scripts/apexlang-hello-world.sh", script);
        Assert.True(script.IndexOf("oracle_set_stage 'Configuring ORDS'", StringComparison.Ordinal) < script.IndexOf("oracle_set_stage 'Creating Sample Application'", StringComparison.Ordinal));
        Assert.True(script.IndexOf("oracle_set_stage 'Creating Sample Application'", StringComparison.Ordinal) < script.IndexOf("oracle_set_stage 'Final Validation'", StringComparison.Ordinal));
    }

    [Fact]
    public void WorkspaceContentGenerator_OrdsBootstrap_UsesManagedDbPasswordSecret()
    {
        var files = new WorkspaceContentGenerator().Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
                Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
                Services = new List<string> { "oracle-demo", "oracle-ords" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.True(files.TryGetValue(Path.Combine("mounts", "config", "ords", "init-ords-config.sh"), out var script));
        Assert.True(files.ContainsKey(Path.Combine("mounts", "config", "ords", "repair-ords-db.sh")));
        Assert.Contains("ords_public_password=\"${ORACLE_ORDS_PUBLIC_PASSWORD}\"", script, StringComparison.Ordinal);
        Assert.Contains("validate_required_ords_config", script, StringComparison.Ordinal);
        Assert.Contains("install --db-only", script, StringComparison.Ordinal);
        Assert.Contains("--proxy-user --password-stdin", script, StringComparison.Ordinal);
        Assert.Contains("config secret --password-stdin db.password", script, StringComparison.Ordinal);
        Assert.Contains("printf '%s\\n' \"${ords_public_password}\"", script, StringComparison.Ordinal);
        Assert.DoesNotContain("chmod -R 777", script, StringComparison.Ordinal);

        var repairScript = files[Path.Combine("mounts", "config", "ords", "repair-ords-db.sh")];
        Assert.Contains("[ords] Effective user: uid=", repairScript, StringComparison.Ordinal);
        Assert.Contains("install repair", repairScript, StringComparison.Ordinal);
        Assert.DoesNotContain("install --db-only", repairScript, StringComparison.Ordinal);
        Assert.DoesNotContain("--proxy-user", repairScript, StringComparison.Ordinal);

        var runtimeSmokeScript = File.ReadAllText(Path.Combine(TestPaths.RepositoryRoot, "scripts", "smoke-oracle-apex-runtime.sh"));
        Assert.Contains("http://localhost:8181/ords/apex", runtimeSmokeScript, StringComparison.Ordinal);
        Assert.DoesNotContain("http://localhost:8181/ords/apex_admin", runtimeSmokeScript, StringComparison.Ordinal);
    }

    [Fact]
    public void ProvisioningGenerator_ForDocumentationWorkspace_IncludesToolingAndFontSetup()
    {
        var script = new WorkspaceImageToolingScriptGenerator().Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "documentation-features" },
                Runtime = new WorkspaceRuntimeDefinition { Default = "default", Node = 24 },
                Features = new List<string> { "core", "document-processing" },
                Terminal = new TerminalPreferences
                {
                    Prompt = new TerminalPromptPreferences { Provider = "starship" },
                    Utilities = new TerminalUtilityPreferences(),
                },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "pandoc", "fonts-crosextra-carlito", "fonts-jetbrains-mono" },
            NpmPackages = new[] { "playwright", "@mermaid-js/mermaid-cli" },
            PipPackages = new[] { "weasyprint", "pypdf", "pymupdf", "reportlab" },
            PostInstallCommands = new[]
            {
                "command -v typst >/dev/null 2>&1 || install /tmp/typst-install/typst-*/typst /usr/local/bin/typst",
                "playwright_browsers_path=/ms-playwright",
                "su -s /bin/bash -c 'export HOME=/home/opencode; export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright; playwright install chromium' opencode",
                "playwright_global_root=$(npm root -g)",
                "export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright",
                "playwright_chromium_path=$(su -s /bin/bash -c 'export HOME=/home/opencode; export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright; export NODE_PATH=$(npm root -g); node -e \"const { chromium } = require(process.env.NODE_PATH + \\\"/playwright\\\"); process.stdout.write(chromium.executablePath());\"' opencode)",
                "echo \"[document-processing] Resolved Playwright Chromium executable: ${playwright_chromium_path}\"",
                "fc-cache -fv",
            },
        });

        Assert.Contains("apt-get install -y pandoc fonts-crosextra-carlito fonts-jetbrains-mono", script);
        Assert.Contains("https://deb.nodesource.com/setup_24.x", script);
        Assert.Contains("apt-get remove -y nodejs npm || true", script);
        Assert.Contains("npm install -g playwright @mermaid-js/mermaid-cli", script);
        Assert.Contains("pip3 install --break-system-packages weasyprint pypdf pymupdf reportlab", script);
        Assert.Contains("command -v typst", script);
        Assert.Contains("playwright install chromium", script);
        Assert.Contains("playwright_browsers_path=/ms-playwright", script);
        Assert.Contains("export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright", script);
        Assert.Contains("export NODE_PATH=$(npm root -g)", script);
        Assert.Contains("Resolved Playwright Chromium executable", script);
        Assert.Contains("fc-cache -fv", script);
    }

    [Fact]
    public void TerminalArtifactsGenerator_CreatesManagedConfigs()
    {
        var generator = new TerminalArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "terminal-demo" },
            Terminal = new TerminalPreferences
            {
                Prompt = new TerminalPromptPreferences { Provider = "starship" },
                Utilities = new TerminalUtilityPreferences { Zoxide = true, Fzf = true },
            },
        };

        var starship = generator.GenerateStarshipConfig(definition);
        var shellInit = generator.GenerateShellInitScript(definition);
        var workspaceShell = generator.GenerateOpencodeWorkspaceShellScript(definition);
        var screenConfig = generator.GenerateScreenConfiguration();

        Assert.Contains("Generated by OpenCode Workspace Manager", ReadHeader(starship));
        Assert.Contains("git_branch", starship);
        Assert.Contains("starship init bash", shellInit);
        Assert.Contains("zoxide init bash", shellInit);
        Assert.Contains("completion.bash", shellInit);
        Assert.Contains("COLORTERM=truecolor", shellInit);
        Assert.Contains("LC_ALL", shellInit);
        Assert.Contains("export JAVA_HOME=", shellInit);
        Assert.Contains("export ORACLE_CLIENT_HOME=${oracle_client_home}", shellInit);
        Assert.Contains("export LD_LIBRARY_PATH=${oracle_client_home}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}", shellInit);
        Assert.Contains("export PATH=${oracle_client_home}:${PATH}", shellInit);
        Assert.Contains("opencode session list", workspaceShell);
        Assert.Contains("opencode --session", workspaceShell);
        Assert.Contains("Found 0 OpenCode sessions. Starting new session.", workspaceShell);
        Assert.Contains("export ORACLE_CLIENT_HOME=${oracle_client_home}", workspaceShell);
        Assert.Contains("cleanup_terminal_state()", workspaceShell);
        Assert.Contains("printf '\\e[?1000l\\e[?1002l\\e[?1003l\\e[?1006l'", workspaceShell);
        Assert.Contains("stty sane || true", workspaceShell);
        Assert.Contains("trap cleanup_terminal_state EXIT", workspaceShell);
        Assert.Contains("export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin${PATH:+:${PATH}}", workspaceShell);
        Assert.Contains("npm_global_prefix=$(npm prefix -g 2>/dev/null || printf '')", workspaceShell);
        Assert.Contains("export PATH=${npm_global_prefix}/bin:${PATH}", workspaceShell);
        Assert.Contains("OpenCode CLI is missing from PATH. Provision or rebuild the workspace runtime before attaching.", workspaceShell);
        Assert.Contains("[attach] npm prefix -g:", workspaceShell);
        Assert.Contains("[attach] npm root -g:", workspaceShell);
        Assert.Contains("[attach] candidate:", workspaceShell);
        Assert.Contains("screen-256color", screenConfig);
        Assert.Contains("defutf8 on", screenConfig);
    }

    [Fact]
    public void TerminalArtifactsGenerator_ForOracleWorkspace_UsesNormalOpenCodeLaunch()
    {
        var generator = new TerminalArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-demo" },
            Services = new List<string> { "oracle-demo" },
        };

        var workspaceShell = generator.GenerateOpencodeWorkspaceShellScript(definition);

        Assert.Contains("run_opencode opencode", workspaceShell);
        Assert.Contains("if run_opencode opencode --session \"$resume_session\"; then", workspaceShell);
        Assert.Contains("cleanup_terminal_state()", workspaceShell);
        Assert.DoesNotContain("oracle_prompt_file=", workspaceShell);
        Assert.DoesNotContain("opencode -p", workspaceShell);
        Assert.DoesNotContain("| opencode", workspaceShell);
    }

    [Fact]
    public void AttachArtifactsGenerator_UsesOpencodeUserAndCreatesSessionWhenMissing()
    {
        var generator = new AttachArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "attach-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        };
        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "attach-demo"));
        var wrapper = generator.GenerateWindowsTerminalWrapper(definition, paths);

        Assert.Contains("$dockerExecArgs = @('exec', '-it', '--user', $attachUser, '-w', $workspaceDirectory", wrapper);
        Assert.Contains("Invoke-DockerCheck", wrapper);
        Assert.Contains("Test-AttachPreconditions", wrapper);
        Assert.Contains("@('exec', $containerName, 'test', '-x', $workspaceShellScript)", wrapper);
        Assert.Contains("Script not found", wrapper);
        Assert.Contains("User $attachUser does not exist.", wrapper);
        Assert.Contains("Working directory missing: $workspaceDirectory", wrapper);
        Assert.Contains("Script is not marked executable", wrapper);
        Assert.Contains("OpenCode CLI is missing from the workspace container PATH.", wrapper);
        Assert.Contains("Verified OpenCode CLI is available in the container PATH.", wrapper);
        Assert.Contains("command -v opencode", wrapper);
        Assert.Contains("npm prefix -g:", wrapper);
        Assert.Contains("printf \"PATH=%s", wrapper);
        Assert.Contains("candidate: %s", wrapper);
        Assert.DoesNotContain("$scriptCheck.Output -notmatch", wrapper);
        Assert.Contains("$attemptedCommand = \"$dockerExe exec -it --user $attachUser -w $workspaceDirectory $containerName bash $workspaceShellScript\"", wrapper);
        Assert.Contains("$attachPrefix = '[attach:attach-demo]'", wrapper);
        Assert.Contains("Write-AttachMessage \"Expected container name: $containerName\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Attempted command: $attemptedCommand\"", wrapper);
        Assert.Contains("Write-AttachMessage \"docker ps:\"", wrapper);
        Assert.Contains("Write-AttachMessage \"docker compose ps:\"", wrapper);
        Assert.Contains("'--profile', 'oracle-demo'", wrapper);
        Assert.Contains("'--profile', 'oracle-ords'", wrapper);
        Assert.Contains(paths.AttachDiagnosticsLogPath, wrapper);
        Assert.Contains(paths.ComposePath, wrapper);
        Assert.Contains("/opt/opencode-workspace/config/opencode-workspace-shell.sh", wrapper);
        Assert.Contains("$disableMouseReporting", wrapper);
        Assert.Contains("[Console]::Write($disableMouseReporting)", wrapper);

        var diagnostics = generator.GenerateTerminalDiagnosticsWrapper(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "attach-demo" },
        });

        Assert.Contains("[attach] Workspace: $workspaceName", diagnostics);
        Assert.Contains("[attach] User: opencode", diagnostics);
        Assert.Contains("[attach] Container: $containerName", diagnostics);
        Assert.Contains("UTF8: ✓ λ € — • │ ─  ", diagnostics);
    }

    [Fact]
    public void AttachPreflight_DoesNotReportFalsePrerequisiteFailures()
    {
        var generator = new AttachArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "odip-analiza" },
        };
        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "odip-analiza"));
        var wrapper = generator.GenerateWindowsTerminalWrapper(definition, paths);

        Assert.Contains("Write-AttachMessage \"Verified script exists: $workspaceShellScript\"", wrapper);
        Assert.Contains("@('exec', $containerName, 'test', '-x', $workspaceShellScript)", wrapper);
        Assert.Contains("Write-AttachMessage \"Verified script is executable: $workspaceShellScript\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Verified user exists: $attachUser\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Verified working directory exists: $workspaceDirectory\"", wrapper);
        Assert.Contains("Write-AttachMessage \"docker exec failed with exit code $ExitCode\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Preflight checks passed.\"", wrapper);
        Assert.DoesNotContain("$scriptCheck.Output -notmatch", wrapper);
        Assert.DoesNotContain("Windows file attributes", wrapper, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void RuntimeGeneratedArtifacts_IncludeRuntimeMetadataHeaders_WithoutPrivateMachineDetails()
    {
        var metadata = GeneratedArtifactRuntimeMetadataBuilder.Create(new ResolvedRuntimePlan
        {
            Runtime = "docker",
            TargetPlatform = "linux/amd64",
            CompatibilityMode = RuntimeCompatibilityMode.Native,
            SupportLevel = SupportLevel.NativeTested,
            IsAvailable = true,
            HostPlatform = new HostPlatformInfo
            {
                OperatingSystem = HostOperatingSystem.Linux,
                Architecture = HostArchitecture.X64,
                NativeContainerPlatform = "linux/amd64",
            },
        }, new DateTimeOffset(2026, 06, 20, 12, 34, 56, TimeSpan.Zero));

        var workspaceDefinition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "header-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core" },
            Terminal = new TerminalPreferences
            {
                Prompt = new TerminalPromptPreferences { Provider = "starship" },
                Utilities = new TerminalUtilityPreferences(),
            },
        };
        var resolvedWorkspace = new ResolvedWorkspace
        {
            Definition = workspaceDefinition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };
        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "header-demo"));

        var artifacts = new[]
        {
            new ComposeGenerator().Generate(resolvedWorkspace, paths, metadata),
            new EnvironmentFileGenerator().Generate(workspaceDefinition, metadata),
            new ProvisioningScriptGenerator().Generate(resolvedWorkspace, metadata),
            new TerminalArtifactsGenerator().GenerateStarshipConfig(workspaceDefinition, metadata),
            new TerminalArtifactsGenerator().GenerateShellInitScript(workspaceDefinition, metadata),
            new TerminalArtifactsGenerator().GenerateOpencodeWorkspaceShellScript(workspaceDefinition, metadata),
            new TerminalArtifactsGenerator().GenerateScreenConfiguration(metadata),
            new AttachArtifactsGenerator().GenerateWindowsTerminalWrapper(workspaceDefinition, paths, metadata),
            new AttachArtifactsGenerator().GenerateTerminalDiagnosticsWrapper(workspaceDefinition, metadata),
        };

        foreach (var artifact in artifacts)
        {
            var header = ReadHeader(artifact);
            Assert.Contains("Generated by OpenCode Workspace Manager", header, StringComparison.Ordinal);
            Assert.Contains("Host OS: Linux", header, StringComparison.Ordinal);
            Assert.Contains("Host Architecture: x64", header, StringComparison.Ordinal);
            Assert.Contains("Runtime: docker", header, StringComparison.Ordinal);
            Assert.Contains("Target Platform: linux/amd64", header, StringComparison.Ordinal);
            Assert.Contains("Compatibility: native", header, StringComparison.Ordinal);
            Assert.Contains("Generated: 2026-06-20T12:34:56.0000000+00:00", header, StringComparison.Ordinal);
            Assert.Contains("Do not edit manually.", header, StringComparison.Ordinal);
            Assert.DoesNotContain(paths.RootPath, header, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("ORACLE_PASSWORD", header, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain(Environment.UserName, header, StringComparison.OrdinalIgnoreCase);
        }

        Assert.Contains("platform: linux/amd64", artifacts[0], StringComparison.Ordinal);
    }

    [Fact]
    public void RuntimeMetadata_FromRecordedState_PreservesRecordedCompatibility()
    {
        var metadata = GeneratedArtifactRuntimeMetadataBuilder.Create(new WorkspaceRuntimeStateRecord
        {
            ResolvedEngine = "docker",
            ResolvedPlatform = "linux/amd64",
            CompatibilityMode = "Native",
            GeneratedArtifactsUtc = new DateTimeOffset(2026, 06, 20, 12, 34, 56, TimeSpan.Zero),
        });

        Assert.Equal("docker", metadata.Runtime);
        Assert.Equal("linux/amd64", metadata.TargetPlatform);
        Assert.Equal("native", metadata.Compatibility);
    }

    private static string ReadHeader(string content)
    {
        var lines = content.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var collected = new List<string>();
        foreach (var line in lines)
        {
            if (!line.StartsWith('#') && !line.StartsWith("#!/", StringComparison.Ordinal))
            {
                break;
            }

            if (line.StartsWith("#!/", StringComparison.Ordinal))
            {
                collected.Add(line);
                continue;
            }

            collected.Add(line);
            if (line.Contains("Do not edit manually.", StringComparison.Ordinal))
            {
                break;
            }
        }

        return string.Join(Environment.NewLine, collected);
    }
}
