using OpenCode.Workspace.Core.Catalog;
using OpenCode.Workspace.Core.Generation;
using OpenCode.Workspace.Core.Models;
using OpenCode.Workspace.Core.Workspaces;

namespace OpenCode.Workspace.Core.Tests;

public sealed class GeneratedArtifactsTests
{
    [Fact]
    public void ComposeGenerator_IncludesGeneratedHeaderAndServices()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Name = "demo-workspace",
                Image = "ubuntu:24.04",
            },
            Features = new List<string> { "core" },
            Services = new List<string> { "postgres", "pgadmin" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = new[]
            {
                new ServiceManifest
                {
                    Id = "postgres",
                    Image = "postgres:17",
                    HostPorts = new List<string> { "15432:5432" },
                    Environment = new Dictionary<string, string> { ["POSTGRES_DB"] = "app" },
                    Volumes = new List<string> { "postgres-data:/var/lib/postgresql/data" },
                },
                new ServiceManifest
                {
                    Id = "pgadmin",
                    Image = "dpage/pgadmin4:9",
                    HostPorts = new List<string> { "18080:80" },
                    DependsOn = new List<string> { "postgres" },
                },
            },
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "demo-workspace"));
        var compose = generator.Generate(resolved, paths);
        var header = ReadHeader(compose);

        Assert.Contains("# Generated by OpenCode Workspace Manager", header);
        Assert.Contains("container_name: demo-workspace-workspace", compose);
        Assert.Contains("  postgres:", compose);
        Assert.Contains("  pgadmin:", compose);
        Assert.Contains("volumes:", compose);
    }

    [Fact]
    public void ComposeGenerator_ForWorkspaceWithoutServices_OmitsWorkspaceDependsOn()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Id = "odip-analiza",
                Name = "Odip Analiza",
                Image = "ubuntu:24.04",
            },
            Provider = new WorkspaceProviderDefinition
            {
                Type = "git",
                Url = "git@ssh.dev.azure.com:v3/KOPA-Projects/ODIP/Analiza",
            },
            Runtime = new WorkspaceRuntimeDefinition
            {
                Default = "default",
            },
            Features = new List<string> { "core", "document-processing", "ocr-processing", "spellcheck" },
            Services = new List<string>(),
            Skills = new List<string>(),
            Mcp = new List<string>(),
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "odip-analiza"));
        var compose = generator.Generate(resolved, paths);

        Assert.DoesNotContain("depends_on:", compose);
    }

    [Fact]
    public void ComposeGenerator_ForSimpleWorkspaceDependencies_UsesArrayForm()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Name = "analiza-with-db",
                Image = "ubuntu:24.04",
            },
            Features = new List<string> { "core" },
            Services = new List<string> { "oracle" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = new[]
            {
                new ServiceManifest
                {
                    Id = "oracle",
                    Image = "gvenzl/oracle-free:23-slim-faststart",
                },
            },
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "analiza-with-db"));
        var compose = generator.Generate(resolved, paths);

        Assert.Contains("    depends_on:", compose);
        Assert.Contains("      - oracle", compose);
        Assert.DoesNotContain("condition:", compose);
    }

    [Fact]
    public void ComposeGenerator_ForConditionalWorkspaceDependencies_UsesObjectForm()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Name = "oracle-demo",
                Image = "ubuntu:24.04",
            },
            Features = new List<string> { "core", "oracle-demo" },
            Services = new List<string> { "oracle-demo" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = new[]
            {
                new ServiceManifest
                {
                    Id = "oracle-demo",
                    Image = "gvenzl/oracle-free:23-slim-faststart",
                    WorkspaceDependsOnCondition = "service_healthy",
                },
            },
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "oracle-demo"));
        var compose = generator.Generate(resolved, paths);

        Assert.Contains("    depends_on:", compose);
        Assert.Contains("      oracle-demo:", compose);
        Assert.Contains("        condition: service_healthy", compose);
    }

    [Fact]
    public void EnvironmentFileGenerator_IncludesOracleDefaultsForOracleDemoWorkspaces()
    {
        var generator = new EnvironmentFileGenerator();
        var content = generator.Generate(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-demo" },
            Services = new List<string> { "oracle-demo" },
        });

        Assert.Contains("ORACLE_PASSWORD=change-on-first-demo", content);
        Assert.Contains("ORACLE_DEMO_SERVICE=FREEPDB1", content);
        Assert.Contains("ORACLE_HOST_PORT=1521", content);
        Assert.Contains("ORACLE_ORDS_BASE_URL=http://localhost:8181/ords", content);
    }

    [Fact]
    public void WorkspaceContentGenerator_OracleApexWorkspace_IncludesOrdsBootstrapScript()
    {
        var provider = new BuiltInCatalogProvider(TestPaths.CatalogRoot);
        var resolver = new WorkspaceResolver(provider.LoadFeatures(), provider.LoadServices(), provider.LoadCapabilities(), provider.LoadKnowledgePacks());
        var resolved = resolver.Resolve(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        });

        var files = new WorkspaceContentGenerator().Generate(resolved);

        Assert.True(files.TryGetValue(Path.Combine("mounts", "config", "ords", "init-ords-config.sh"), out var script));
        Assert.Contains("ords --config \"${config_dir}\" install --config-only", script, StringComparison.Ordinal);
        Assert.Contains("--gateway-user APEX_PUBLIC_USER", script, StringComparison.Ordinal);
        Assert.Contains("exec ords --config \"${config_dir}\" serve --port 8080", script, StringComparison.Ordinal);
    }

    [Fact]
    public void WorkspaceContentGenerator_GeneratesWorkspaceServicesGuide()
    {
        var provider = new BuiltInCatalogProvider(TestPaths.CatalogRoot);
        var resolver = new WorkspaceResolver(provider.LoadFeatures(), provider.LoadServices(), provider.LoadCapabilities(), provider.LoadKnowledgePacks());
        var resolved = resolver.Resolve(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        });

        var files = new WorkspaceContentGenerator().Generate(resolved);

        Assert.True(files.TryGetValue(Path.Combine("docs", "workspace-services.md"), out var guide));
        Assert.Contains("# Available Services", guide, StringComparison.Ordinal);
        Assert.Contains("APEX Builder", guide, StringComparison.Ordinal);
        Assert.Contains("ORDS Landing", guide, StringComparison.Ordinal);
        Assert.Contains("SQLcl", guide, StringComparison.Ordinal);
        Assert.Contains("Development Shell", guide, StringComparison.Ordinal);
    }

    [Fact]
    public void WorkspaceServiceCatalog_GenericWorkspace_ExposesTerminalFolderAndCli()
    {
        var services = WorkspaceServiceCatalog.Build(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "general-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core" },
            Services = new List<string>(),
        }, workspaceRootPath: @"C:\workspaces\general-demo");

        Assert.Contains(services, item => item.Name == "Development Shell");
        Assert.Contains(services, item => item.Name == "Repository Folder");
        Assert.Contains(services, item => item.Name == "OpenCode CLI");
    }

    [Fact]
    public void ProvisioningScriptGenerator_OracleApexWorkspace_ReportsMissingOrdsConfigClearly()
    {
        var provider = new BuiltInCatalogProvider(TestPaths.CatalogRoot);
        var resolver = new WorkspaceResolver(provider.LoadFeatures(), provider.LoadServices(), provider.LoadCapabilities(), provider.LoadKnowledgePacks());
        var resolved = resolver.Resolve(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        });

        var script = new ProvisioningScriptGenerator().Generate(resolved);

        Assert.Contains("Oracle REST Data Services (ORDS) config did not initialize.", script, StringComparison.Ordinal);
        Assert.Contains("Managed ORDS config files were not created under /opt/opencode-workspace/config/ords", script, StringComparison.Ordinal);
    }

    [Fact]
    public void EnvironmentFileGenerator_IncludesMarimoPortForAnalyticsWorkspace()
    {
        var generator = new EnvironmentFileGenerator();
        var content = generator.Generate(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "analytics-demo" },
            Features = new List<string> { "core", "analytics-reporting" },
            Analytics = new AnalyticsWorkspacePreferences { MarimoPort = 3818 },
        });

        Assert.Contains("MARIMO_PORT=3818", content);
    }

    [Fact]
    public void EnvironmentFileGenerator_UsesLfLineEndingsWithoutCarriageReturns()
    {
        var generator = new EnvironmentFileGenerator();
        var content = generator.Generate(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "Odip Analiza" },
        });

        Assert.DoesNotContain('\r', content);
        Assert.Contains("\nWORKSPACE_NAME=Odip Analiza\n", content, StringComparison.Ordinal);
    }

    [Fact]
    public void ComposeGenerator_ForAnalyticsWorkspace_UsesLoopbackOnlyMarimoPortMapping()
    {
        var generator = new ComposeGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "analytics-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core", "analytics-reporting" },
        };

        var resolved = new ResolvedWorkspace
        {
            Definition = definition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var compose = generator.Generate(resolved, WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "analytics-demo")));

        Assert.Contains("127.0.0.1:${MARIMO_PORT}:2718", compose);
    }

    [Fact]
    public void ComposeGenerator_ForWorkspaceWithoutAnalytics_DoesNotExposeMarimoPort()
    {
        var generator = new ComposeGenerator();
        var resolved = new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "core-only", Image = "ubuntu:24.04" },
                Features = new List<string> { "core" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };

        var compose = generator.Generate(resolved, WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "core-only")));
        Assert.DoesNotContain("MARIMO_PORT", compose);
        Assert.DoesNotContain("127.0.0.1:${MARIMO_PORT}:2718", compose);
    }

    [Fact]
    public void ProvisioningGenerator_IncludesGeneratedHeaderAndOpenCodeInstall()
    {
        var generator = new ProvisioningScriptGenerator();
        var script = generator.Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "demo" },
                Terminal = new TerminalPreferences
                {
                    Prompt = new TerminalPromptPreferences { Provider = "starship" },
                    Utilities = new TerminalUtilityPreferences { Zoxide = true, Fzf = true },
                },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "git", "curl" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.Contains("# Generated by OpenCode Workspace Manager", ReadHeader(script));
        Assert.Contains("apt-get install -y git curl", script);
        Assert.Contains("https://deb.nodesource.com/setup_22.x", script);
        Assert.Contains("apt-get remove -y nodejs npm || true", script);
        Assert.Contains("apt-get install -y nodejs", script);
        Assert.Contains("apt-cache policy nodejs | sed -n '1,20p'", script);
        Assert.Contains("useradd -m -d /home/opencode -s /bin/bash opencode", script);
        Assert.Contains("npm --version", script);
        Assert.Contains("python --version", script);
        Assert.Contains("python3 --version", script);
        Assert.Contains("which python", script);
        Assert.Contains("which python3", script);
        Assert.Contains("node -e \"console.log(process.version)\"", script);
        Assert.Contains("npm install -g opencode-ai", script);
        Assert.Contains("opencode_global_prefix=$(npm prefix -g 2>/dev/null || printf '')", script);
        Assert.Contains("export PATH=\"${opencode_global_prefix}/bin:${PATH}\"", script);
        Assert.Contains("curl -sS https://starship.rs/install.sh | sh -s -- -y", script);
        Assert.Contains("source /opt/opencode-workspace/config/opencode-shell-init.sh", script);
        Assert.Contains("command -v opencode", script);
        Assert.Contains("opencode --version", script);
        Assert.Contains("su -s /bin/bash -c 'command -v opencode && opencode --version' opencode", script);
        Assert.DoesNotContain(". /workspace/.env", script, StringComparison.Ordinal);
        Assert.Contains("env_line=${env_line%$'\\r'}", script, StringComparison.Ordinal);
        Assert.Contains("export \"${env_key}=${env_value}\"", script, StringComparison.Ordinal);
        Assert.Contains("begin_stage()", script);
        Assert.Contains("complete_stage()", script);
        Assert.Contains("fail_stage()", script);
        Assert.Contains("run_with_timeout()", script);
        Assert.Contains("wait_for_command()", script);
        Assert.Contains("trap 'fail_stage \"Provisioning command failed.\"", script);
        Assert.Contains("begin_stage 'Initialize workspace user'", script);
        Assert.Contains("begin_stage 'Install base packages'", script);
        Assert.Contains("begin_stage 'Install Node.js runtime'", script);
    }

    [Fact]
    public void ProvisioningGenerator_ForOracleWorkspace_UsesDynamicLibaioHelper()
    {
        var generator = new ProvisioningScriptGenerator();
        var script = generator.Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-demo" },
                Features = new List<string> { "core", "oracle-demo" },
                Services = new List<string> { "oracle-demo" },
                Terminal = new TerminalPreferences
                {
                    Prompt = new TerminalPromptPreferences { Provider = "starship" },
                    Utilities = new TerminalUtilityPreferences(),
                },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "curl", "rlwrap", "unzip", "libaio1" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.Contains("Detected Ubuntu version", script);
        Assert.Contains("Selected libaio package", script);
        Assert.Contains("if apt-cache policy libaio1 | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("elif apt-cache policy libaio1t64 | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("dpkg -L \"${oracle_libaio_pkg}\"", script);
        Assert.Contains("ln -sf /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1", script);
        Assert.Contains("ldconfig", script);
        Assert.Contains("Selected Java package", script);
        Assert.Contains("if apt-cache policy openjdk-21-jre-headless | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("elif apt-cache policy openjdk-17-jre-headless | grep -F \"Candidate:\" | grep -Fvq \"(none)\"; then", script);
        Assert.Contains("No compatible Java runtime package found for SQLcl", script);
        Assert.Contains("oracle_sqlplus_root=/opt/oracle/instantclient", script);
        Assert.Contains("if command -v sqlplus >/dev/null 2>&1 && sqlplus -v; then", script);
        Assert.Contains("SQL*Plus already installed and valid; skipping reinstall.", script);
        Assert.Contains("instantclient-basiclite-linux.x64", script);
        Assert.Contains("instantclient-sqlplus-linux.x64", script);
        Assert.Contains("ldd \"${sqlplus_launcher}\"", script);
        Assert.Contains("/etc/ld.so.conf.d/oracle-instantclient.conf", script);
        Assert.Contains("export ORACLE_CLIENT_HOME=${oracle_client_home}", script);
        Assert.Contains("sqlplus -S \"${oracle_connection}\" @\"${oracle_sqlplus_probe_script}\"", script);
        Assert.Contains("wait_for_command 300 10 'Oracle SQL*Plus readiness'", script);
        Assert.Contains("run_with_timeout 120 'Oracle demo user setup'", script);
        Assert.Contains("local setup_script=/tmp/oracle-demo-user-setup.sql", script);
        Assert.Contains("@\"${setup_script}\"", script);
        Assert.Contains("run_with_timeout 120 'Oracle demo user setup' 'Rebuild Runtime if the Oracle data volume contains stale credentials.' bash -lc \"$(declare -f ensure_demo_user_ready); ensure_demo_user_ready\"", script);
        Assert.DoesNotContain("run_with_timeout 120 'Oracle demo user setup' 'Rebuild Runtime if the Oracle data volume contains stale credentials.' ensure_demo_user_ready", script, StringComparison.Ordinal);
        Assert.Contains("validate_sqlcl_install()", script);
        Assert.Contains("if validate_sqlcl_install /opt/sqlcl; then", script);
        Assert.Contains("SQLcl already installed and valid; skipping reinstall.", script);
        Assert.Contains("Existing SQLcl install missing or invalid. Reinstalling.", script);
        Assert.Contains("oracle_sqlcl_extract=/tmp/sqlcl-extract", script);
        Assert.Contains("Failed to download the official SQLcl zip archive", script);
        Assert.Contains("Unexpected SQLcl layout: staged sqlcl/bin/sql was not created", script);
        Assert.Contains("Diagnostic only: SqlCli.class was not found in staged dbtools-sqlcl.jar", script);
        Assert.Contains("rm -rf /opt/sqlcl", script);
        Assert.Contains("cp -a \"${oracle_sqlcl_extract}/.\" /opt/sqlcl/", script);
        Assert.Contains("sql -v", script);
        Assert.Contains("ln -sf \"${sqlcl_launcher}\" /usr/local/bin/sqlcl", script);
        Assert.Contains("ln -sf /opt/sqlcl/sqlcl/bin/sql /usr/local/bin/sqlcl", script);
        Assert.Contains("sqlcl -v", script);
        Assert.Contains("SELECT 'Connection OK' AS status FROM dual;", script);
        Assert.Contains("wait_for_command 300 10 'Oracle SQLcl readiness'", script);
        Assert.Contains("Staged SQLcl install failed runtime validation", script);
        Assert.Contains("Reinstalled SQLcl failed runtime validation after activation", script);
        Assert.Contains("java -version", script);
        Assert.DoesNotContain("apt-get install -y curl rlwrap unzip libaio1", script);
    }

    [Fact]
    public void ProvisioningGenerator_ForOracleApexWorkspace_WaitsForOrdsAndApex()
    {
        var generator = new ProvisioningScriptGenerator();
        var script = generator.Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-apex-demo" },
                Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo" },
                Services = new List<string> { "oracle-demo", "oracle-ords" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "curl", "rlwrap", "unzip" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.Contains("oracle_ords_url=http://oracle-ords:8080/ords", script);
        Assert.Contains("oracle_ords_landing_url=http://oracle-ords:8080/ords/_/landing", script);
        Assert.Contains("oracle_demo_user_setup_script=/tmp/oracle-demo-user-setup.sql", script);
        Assert.Contains("ensure_demo_user_ready()", script);
        Assert.Contains("bash -lc \"$(declare -f ensure_demo_user_ready); ensure_demo_user_ready\"", script);
        Assert.Contains("apex_registry_status=$(printf '%s' \"${apex_registry}\" | awk -F'|' '{print $3}')", script);
        Assert.Contains("if [ -n \"${apex_registry}\" ] && [ \"${apex_registry_status}\" = 'VALID' ]", script);
        Assert.Contains("[oracle-apex] APEX already installed: ${apex_registry}", script);
        Assert.Contains("Oracle APEX is partially installed or inconsistent.", script);
        Assert.Contains("Rebuild Runtime to recreate the Oracle data volume, or manually repair the Oracle APEX registry before retrying.", script);
        Assert.Contains("ALTER USER demo_user IDENTIFIED BY \"demo_password\" ACCOUNT UNLOCK", script);
        Assert.Contains("[oracle] Oracle administrator password does not match the running database.", script);
        Assert.Contains("[oracle] Recommended action: Rebuild Runtime.", script);
        Assert.True(script.IndexOf("ensure_demo_user_ready", StringComparison.Ordinal) < script.IndexOf("wait_for_command 300 10 'Oracle SQL*Plus readiness'", StringComparison.Ordinal));
        Assert.Contains("wait_for_ords_runtime()", script);
        Assert.Contains("ensure_ords_public_user_ready()", script);
        Assert.Contains("validate_ords_installation()", script);
        Assert.Contains("SELECT COUNT(*) FROM dba_users WHERE username = 'ORDS_PUBLIC_USER';", script);
        Assert.Contains("SELECT COUNT(*) FROM dba_users WHERE username = 'ORDS_METADATA';", script);
        Assert.Contains("Oracle REST Data Services is not installed in the database.", script);
        Assert.Contains("ALTER USER ords_public_user IDENTIFIED BY \"${ords_public_password}\" ACCOUNT UNLOCK;", script);
        Assert.Contains("oracle_set_stage 'Validate ORDS installation'", script);
        Assert.Contains("oracle_set_stage 'Synchronize ORDS credentials'", script);
        Assert.Contains("pool.xml does not use ORDS_PUBLIC_USER for db.username", script);
        Assert.Contains("ORDS returned HTTP 574 DatabaseCredentialError for ORDS_PUBLIC_USER.", script);
        Assert.Contains("Oracle REST Data Services database credentials are invalid.", script);
        Assert.Contains("ords_redirect_location=$(grep -i '^Location:' /tmp/ords-health-headers.txt", script);
        Assert.Contains("if [ \"${ords_http_status}\" = '302' ] && printf '%s' \"${ords_redirect_location}\" | grep -Fq '/ords/_/landing'; then", script);
        Assert.DoesNotContain("/ords/apex_admin", script, StringComparison.Ordinal);
        Assert.True(script.IndexOf("oracle_set_stage 'Validate ORDS installation'", StringComparison.Ordinal) < script.IndexOf("oracle_set_stage 'Synchronize ORDS credentials'", StringComparison.Ordinal));
        Assert.True(script.IndexOf("validate_ords_installation", StringComparison.Ordinal) < script.IndexOf("wait_for_ords_runtime", StringComparison.Ordinal));
        Assert.DoesNotContain("Route ${oracle_apex_url}", script, StringComparison.Ordinal);
        Assert.Contains("validate_oracle_environment()", script);
        Assert.Contains("validate_oracle_prerequisites()", script);
        Assert.Contains("SELECT status FROM dba_registry WHERE comp_id = 'XDB';", script);
        Assert.Contains("recompile_invalid_oracle_components()", script);
        Assert.Contains("ALTER SESSION SET CONTAINER = CDB$ROOT;", script);
        Assert.Contains("EXECUTE dbms_registry_sys.validate_components;", script);
        Assert.Contains("Attempting Oracle component recompile", script);
        Assert.Contains("if [ \"${xdb_status}\" != 'VALID' ]; then", script);
        Assert.Contains("cat /tmp/oracle-utlrp.out >&2 || true", script);
        Assert.True(script.IndexOf("recompile_invalid_oracle_components >/tmp/oracle-utlrp.out 2>&1 || true", StringComparison.Ordinal) < script.IndexOf("oracle_fail \"Oracle XML Database (XDB) is invalid.\"", StringComparison.Ordinal));
        Assert.True(script.IndexOf("oracle_set_stage 'Install APEX'", StringComparison.Ordinal) > script.IndexOf("validate_oracle_prerequisites", StringComparison.Ordinal));
        Assert.Contains("Oracle APEX registry is not valid after installation.", script);
        Assert.Contains("Oracle APEX did not register in the database.", script);
        Assert.Contains("Oracle APEX schema users were not created.", script);
        Assert.Contains("APEX_INSTANCE_ADMIN.CREATE_OR_UPDATE_ADMIN_USER(", script);
        Assert.Contains("APEX_INSTANCE_ADMIN.UNLOCK_USER(", script);
        Assert.Contains("APEX_INSTANCE_ADMIN.SET_PARAMETER('STRONG_SITE_ADMIN_PASSWORD', 'N');", script);
        Assert.Contains("APEX_INSTANCE_ADMIN.SET_PARAMETER('EXPIRE_FND_USER_ACCOUNTS', 'N');", script);
        Assert.Contains("UPDATE apex_260100.wwv_flow_fnd_user", script);
        Assert.DoesNotContain("@apxchpwd.sql", script, StringComparison.Ordinal);
    }

    [Fact]
    public void ProvisioningGenerator_ForOracleApexlangWorkspace_UsesShellContextForOracleDemoUserTimeout()
    {
        var generator = new ProvisioningScriptGenerator();
        var script = generator.Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo" },
                Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
                Services = new List<string> { "oracle-demo", "oracle-ords" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "curl", "rlwrap", "unzip" },
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.Contains("ensure_demo_user_ready()", script);
        Assert.Contains("local setup_script=/tmp/oracle-demo-user-setup.sql", script);
        Assert.Contains("run_with_timeout 120 'Oracle demo user setup' 'Rebuild Runtime if the Oracle data volume contains stale credentials.' bash -lc \"$(declare -f ensure_demo_user_ready); ensure_demo_user_ready\"", script);
        Assert.DoesNotContain("run_with_timeout 120 'Oracle demo user setup' 'Rebuild Runtime if the Oracle data volume contains stale credentials.' ensure_demo_user_ready", script, StringComparison.Ordinal);
        Assert.Contains("oracle_set_stage 'Provision Hello APEXlang'", script);
        Assert.Contains("/workspace/scripts/apexlang-hello-world.sh", script);
        Assert.True(script.IndexOf("oracle_set_stage 'Workspace configuration'", StringComparison.Ordinal) < script.IndexOf("oracle_set_stage 'Provision Hello APEXlang'", StringComparison.Ordinal));
        Assert.True(script.IndexOf("oracle_set_stage 'Provision Hello APEXlang'", StringComparison.Ordinal) < script.IndexOf("oracle_set_stage 'Final verification'", StringComparison.Ordinal));
    }

    [Fact]
    public void WorkspaceContentGenerator_OrdsBootstrap_UsesManagedDbPasswordSecret()
    {
        var files = new WorkspaceContentGenerator().Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-apexlang-demo", Image = "ubuntu:24.04" },
                Features = new List<string> { "core", "oracle-demo", "oracle-apex-demo", "oracle-apexlang-demo" },
                Services = new List<string> { "oracle-demo", "oracle-ords" },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        });

        Assert.True(files.TryGetValue(Path.Combine("mounts", "config", "ords", "init-ords-config.sh"), out var script));
        Assert.True(files.ContainsKey(Path.Combine("mounts", "config", "ords", "repair-ords-db.sh")));
        Assert.Contains("ords_public_password=\"${ORACLE_PWD:-change-on-first-demo}\"", script, StringComparison.Ordinal);
        Assert.Contains("install --db-only", script, StringComparison.Ordinal);
        Assert.Contains("--proxy-user --password-stdin", script, StringComparison.Ordinal);
        Assert.Contains("config secret --password-stdin db.password", script, StringComparison.Ordinal);
        Assert.Contains("printf '%s\\n' \"${ords_public_password}\"", script, StringComparison.Ordinal);

        var repairScript = files[Path.Combine("mounts", "config", "ords", "repair-ords-db.sh")];
        Assert.Contains("install repair", repairScript, StringComparison.Ordinal);
        Assert.DoesNotContain("install --db-only", repairScript, StringComparison.Ordinal);
        Assert.DoesNotContain("--proxy-user", repairScript, StringComparison.Ordinal);

        var runtimeSmokeScript = File.ReadAllText(Path.Combine(TestPaths.RepositoryRoot, "scripts", "smoke-oracle-apex-runtime.sh"));
        Assert.Contains("http://localhost:8181/ords/apex", runtimeSmokeScript, StringComparison.Ordinal);
        Assert.DoesNotContain("http://localhost:8181/ords/apex_admin", runtimeSmokeScript, StringComparison.Ordinal);
    }

    [Fact]
    public void ProvisioningGenerator_ForDocumentationWorkspace_IncludesToolingAndFontSetup()
    {
        var generator = new ProvisioningScriptGenerator();
        var script = generator.Generate(new ResolvedWorkspace
        {
            Definition = new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "documentation-features" },
                Runtime = new WorkspaceRuntimeDefinition { Default = "default", Node = 24 },
                Features = new List<string> { "core", "document-processing" },
                Terminal = new TerminalPreferences
                {
                    Prompt = new TerminalPromptPreferences { Provider = "starship" },
                    Utilities = new TerminalUtilityPreferences(),
                },
            },
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = new[] { "pandoc", "fonts-crosextra-carlito", "fonts-jetbrains-mono" },
            NpmPackages = new[] { "playwright", "@mermaid-js/mermaid-cli" },
            PipPackages = new[] { "weasyprint", "pypdf", "pymupdf", "reportlab" },
            PostInstallCommands = new[]
            {
                "command -v typst >/dev/null 2>&1 || install /tmp/typst-install/typst-*/typst /usr/local/bin/typst",
                "playwright_browsers_path=/ms-playwright",
                "su -s /bin/bash -c 'export HOME=/home/opencode; export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright; playwright install chromium' opencode",
                "playwright_global_root=$(npm root -g)",
                "export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright",
                "playwright_chromium_path=$(su -s /bin/bash -c 'export HOME=/home/opencode; export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright; export NODE_PATH=$(npm root -g); node -e \"const { chromium } = require(process.env.NODE_PATH + \\\"/playwright\\\"); process.stdout.write(chromium.executablePath());\"' opencode)",
                "echo \"[document-processing] Resolved Playwright Chromium executable: ${playwright_chromium_path}\"",
                "fc-cache -fv",
            },
        });

        Assert.Contains("apt-get install -y pandoc fonts-crosextra-carlito fonts-jetbrains-mono", script);
        Assert.Contains("https://deb.nodesource.com/setup_24.x", script);
        Assert.Contains("apt-get remove -y nodejs npm || true", script);
        Assert.Contains("npm install -g playwright @mermaid-js/mermaid-cli", script);
        Assert.Contains("pip3 install --break-system-packages weasyprint pypdf pymupdf reportlab", script);
        Assert.Contains("command -v typst", script);
        Assert.Contains("playwright install chromium", script);
        Assert.Contains("playwright_browsers_path=/ms-playwright", script);
        Assert.Contains("export PLAYWRIGHT_BROWSERS_PATH=/ms-playwright", script);
        Assert.Contains("export NODE_PATH=$(npm root -g)", script);
        Assert.Contains("Resolved Playwright Chromium executable", script);
        Assert.Contains("fc-cache -fv", script);
    }

    [Fact]
    public void TerminalArtifactsGenerator_CreatesManagedConfigs()
    {
        var generator = new TerminalArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "terminal-demo" },
            Terminal = new TerminalPreferences
            {
                Prompt = new TerminalPromptPreferences { Provider = "starship" },
                Utilities = new TerminalUtilityPreferences { Zoxide = true, Fzf = true },
            },
        };

        var starship = generator.GenerateStarshipConfig(definition);
        var shellInit = generator.GenerateShellInitScript(definition);
        var workspaceShell = generator.GenerateOpencodeWorkspaceShellScript(definition);
        var screenConfig = generator.GenerateScreenConfiguration();

        Assert.Contains("Generated by OpenCode Workspace Manager", ReadHeader(starship));
        Assert.Contains("git_branch", starship);
        Assert.Contains("starship init bash", shellInit);
        Assert.Contains("zoxide init bash", shellInit);
        Assert.Contains("completion.bash", shellInit);
        Assert.Contains("COLORTERM=truecolor", shellInit);
        Assert.Contains("LC_ALL", shellInit);
        Assert.Contains("export JAVA_HOME=", shellInit);
        Assert.Contains("export ORACLE_CLIENT_HOME=${oracle_client_home}", shellInit);
        Assert.Contains("export LD_LIBRARY_PATH=${oracle_client_home}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}", shellInit);
        Assert.Contains("export PATH=${oracle_client_home}:${PATH}", shellInit);
        Assert.Contains("opencode session list", workspaceShell);
        Assert.Contains("opencode --session", workspaceShell);
        Assert.Contains("Found 0 OpenCode sessions. Starting new session.", workspaceShell);
        Assert.Contains("export ORACLE_CLIENT_HOME=${oracle_client_home}", workspaceShell);
        Assert.Contains("cleanup_terminal_state()", workspaceShell);
        Assert.Contains("printf '\\e[?1000l\\e[?1002l\\e[?1003l\\e[?1006l'", workspaceShell);
        Assert.Contains("stty sane || true", workspaceShell);
        Assert.Contains("trap cleanup_terminal_state EXIT", workspaceShell);
        Assert.Contains("export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin${PATH:+:${PATH}}", workspaceShell);
        Assert.Contains("npm_global_prefix=$(npm prefix -g 2>/dev/null || printf '')", workspaceShell);
        Assert.Contains("export PATH=${npm_global_prefix}/bin:${PATH}", workspaceShell);
        Assert.Contains("OpenCode CLI is missing from PATH. Provision or rebuild the workspace runtime before attaching.", workspaceShell);
        Assert.Contains("[attach] npm prefix -g:", workspaceShell);
        Assert.Contains("[attach] npm root -g:", workspaceShell);
        Assert.Contains("[attach] candidate:", workspaceShell);
        Assert.Contains("screen-256color", screenConfig);
        Assert.Contains("defutf8 on", screenConfig);
    }

    [Fact]
    public void TerminalArtifactsGenerator_ForOracleWorkspace_UsesNormalOpenCodeLaunch()
    {
        var generator = new TerminalArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "oracle-demo" },
            Services = new List<string> { "oracle-demo" },
        };

        var workspaceShell = generator.GenerateOpencodeWorkspaceShellScript(definition);

        Assert.Contains("run_opencode opencode", workspaceShell);
        Assert.Contains("if run_opencode opencode --session \"$resume_session\"; then", workspaceShell);
        Assert.Contains("cleanup_terminal_state()", workspaceShell);
        Assert.DoesNotContain("oracle_prompt_file=", workspaceShell);
        Assert.DoesNotContain("opencode -p", workspaceShell);
        Assert.DoesNotContain("| opencode", workspaceShell);
    }

    [Fact]
    public void AttachArtifactsGenerator_UsesOpencodeUserAndCreatesSessionWhenMissing()
    {
        var generator = new AttachArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "attach-demo" },
            Services = new List<string> { "oracle-demo", "oracle-ords" },
        };
        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "attach-demo"));
        var wrapper = generator.GenerateWindowsTerminalWrapper(definition, paths);

        Assert.Contains("$dockerExecArgs = @('exec', '-it', '--user', $attachUser, '-w', $workspaceDirectory", wrapper);
        Assert.Contains("Invoke-DockerCheck", wrapper);
        Assert.Contains("Test-AttachPreconditions", wrapper);
        Assert.Contains("@('exec', $containerName, 'test', '-x', $workspaceShellScript)", wrapper);
        Assert.Contains("Script not found", wrapper);
        Assert.Contains("User $attachUser does not exist.", wrapper);
        Assert.Contains("Working directory missing: $workspaceDirectory", wrapper);
        Assert.Contains("Script is not marked executable", wrapper);
        Assert.Contains("OpenCode CLI is missing from the workspace container PATH.", wrapper);
        Assert.Contains("Verified OpenCode CLI is available in the container PATH.", wrapper);
        Assert.Contains("command -v opencode", wrapper);
        Assert.Contains("npm prefix -g:", wrapper);
        Assert.Contains("printf \"PATH=%s", wrapper);
        Assert.Contains("candidate: %s", wrapper);
        Assert.DoesNotContain("$scriptCheck.Output -notmatch", wrapper);
        Assert.Contains("$attemptedCommand = \"$dockerExe exec -it --user $attachUser -w $workspaceDirectory $containerName bash $workspaceShellScript\"", wrapper);
        Assert.Contains("$attachPrefix = '[attach:attach-demo]'", wrapper);
        Assert.Contains("Write-AttachMessage \"Expected container name: $containerName\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Attempted command: $attemptedCommand\"", wrapper);
        Assert.Contains("Write-AttachMessage \"docker ps:\"", wrapper);
        Assert.Contains("Write-AttachMessage \"docker compose ps:\"", wrapper);
        Assert.Contains("'--profile', 'oracle-demo'", wrapper);
        Assert.Contains("'--profile', 'oracle-ords'", wrapper);
        Assert.Contains(paths.AttachDiagnosticsLogPath, wrapper);
        Assert.Contains(paths.ComposePath, wrapper);
        Assert.Contains("/opt/opencode-workspace/config/opencode-workspace-shell.sh", wrapper);
        Assert.Contains("$disableMouseReporting", wrapper);
        Assert.Contains("[Console]::Write($disableMouseReporting)", wrapper);

        var diagnostics = generator.GenerateTerminalDiagnosticsWrapper(new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "attach-demo" },
        });

        Assert.Contains("[attach] Workspace: $workspaceName", diagnostics);
        Assert.Contains("[attach] User: opencode", diagnostics);
        Assert.Contains("[attach] Container: $containerName", diagnostics);
        Assert.Contains("UTF8: ✓ λ € — • │ ─  ", diagnostics);
    }

    [Fact]
    public void AttachPreflight_DoesNotReportFalsePrerequisiteFailures()
    {
        var generator = new AttachArtifactsGenerator();
        var definition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "odip-analiza" },
        };
        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "odip-analiza"));
        var wrapper = generator.GenerateWindowsTerminalWrapper(definition, paths);

        Assert.Contains("Write-AttachMessage \"Verified script exists: $workspaceShellScript\"", wrapper);
        Assert.Contains("@('exec', $containerName, 'test', '-x', $workspaceShellScript)", wrapper);
        Assert.Contains("Write-AttachMessage \"Verified script is executable: $workspaceShellScript\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Verified user exists: $attachUser\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Verified working directory exists: $workspaceDirectory\"", wrapper);
        Assert.Contains("Write-AttachMessage \"docker exec failed with exit code $ExitCode\"", wrapper);
        Assert.Contains("Write-AttachMessage \"Preflight checks passed.\"", wrapper);
        Assert.DoesNotContain("$scriptCheck.Output -notmatch", wrapper);
        Assert.DoesNotContain("Windows file attributes", wrapper, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void RuntimeGeneratedArtifacts_IncludeRuntimeMetadataHeaders_WithoutPrivateMachineDetails()
    {
        var metadata = GeneratedArtifactRuntimeMetadataBuilder.Create(new ResolvedRuntimePlan
        {
            Runtime = "docker",
            TargetPlatform = "linux/amd64",
            CompatibilityMode = RuntimeCompatibilityMode.Native,
            SupportLevel = SupportLevel.NativeTested,
            IsAvailable = true,
            HostPlatform = new HostPlatformInfo
            {
                OperatingSystem = HostOperatingSystem.Linux,
                Architecture = HostArchitecture.X64,
                NativeContainerPlatform = "linux/amd64",
            },
        }, new DateTimeOffset(2026, 06, 20, 12, 34, 56, TimeSpan.Zero));

        var workspaceDefinition = new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata { Name = "header-demo", Image = "ubuntu:24.04" },
            Features = new List<string> { "core" },
            Terminal = new TerminalPreferences
            {
                Prompt = new TerminalPromptPreferences { Provider = "starship" },
                Utilities = new TerminalUtilityPreferences(),
            },
        };
        var resolvedWorkspace = new ResolvedWorkspace
        {
            Definition = workspaceDefinition,
            Features = Array.Empty<FeatureManifest>(),
            Capabilities = Array.Empty<CapabilityManifest>(),
            Services = Array.Empty<ServiceManifest>(),
            AptPackages = Array.Empty<string>(),
            NpmPackages = Array.Empty<string>(),
            PipPackages = Array.Empty<string>(),
            PostInstallCommands = Array.Empty<string>(),
        };
        var paths = WorkspacePathBuilder.Build(Path.Combine(Path.GetTempPath(), "header-demo"));

        var artifacts = new[]
        {
            new ComposeGenerator().Generate(resolvedWorkspace, paths, metadata),
            new EnvironmentFileGenerator().Generate(workspaceDefinition, metadata),
            new ProvisioningScriptGenerator().Generate(resolvedWorkspace, metadata),
            new TerminalArtifactsGenerator().GenerateStarshipConfig(workspaceDefinition, metadata),
            new TerminalArtifactsGenerator().GenerateShellInitScript(workspaceDefinition, metadata),
            new TerminalArtifactsGenerator().GenerateOpencodeWorkspaceShellScript(workspaceDefinition, metadata),
            new TerminalArtifactsGenerator().GenerateScreenConfiguration(metadata),
            new AttachArtifactsGenerator().GenerateWindowsTerminalWrapper(workspaceDefinition, paths, metadata),
            new AttachArtifactsGenerator().GenerateTerminalDiagnosticsWrapper(workspaceDefinition, metadata),
        };

        foreach (var artifact in artifacts)
        {
            var header = ReadHeader(artifact);
            Assert.Contains("Generated by OpenCode Workspace Manager", header, StringComparison.Ordinal);
            Assert.Contains("Host OS: Linux", header, StringComparison.Ordinal);
            Assert.Contains("Host Architecture: x64", header, StringComparison.Ordinal);
            Assert.Contains("Runtime: docker", header, StringComparison.Ordinal);
            Assert.Contains("Target Platform: linux/amd64", header, StringComparison.Ordinal);
            Assert.Contains("Compatibility: native", header, StringComparison.Ordinal);
            Assert.Contains("Generated: 2026-06-20T12:34:56.0000000+00:00", header, StringComparison.Ordinal);
            Assert.Contains("Do not edit manually.", header, StringComparison.Ordinal);
            Assert.DoesNotContain(paths.RootPath, header, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("ORACLE_PASSWORD", header, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain(Environment.UserName, header, StringComparison.OrdinalIgnoreCase);
        }

        Assert.Contains("platform: linux/amd64", artifacts[0], StringComparison.Ordinal);
    }

    private static string ReadHeader(string content)
    {
        var lines = content.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var collected = new List<string>();
        foreach (var line in lines)
        {
            if (!line.StartsWith('#') && !line.StartsWith("#!/", StringComparison.Ordinal))
            {
                break;
            }

            if (line.StartsWith("#!/", StringComparison.Ordinal))
            {
                collected.Add(line);
                continue;
            }

            collected.Add(line);
            if (line.Contains("Do not edit manually.", StringComparison.Ordinal))
            {
                break;
            }
        }

        return string.Join(Environment.NewLine, collected);
    }
}
