using System.Diagnostics;
using System.IO.Compression;
using OpenCode.Workspace.Core.Catalog;
using OpenCode.Workspace.Core.Generation;
using OpenCode.Workspace.Core.Models;
using OpenCode.Workspace.Core.Runtime;
using OpenCode.Workspace.Core.Workspaces;

namespace OpenCode.Workspace.Core.Tests;

public sealed class WorkspaceOrchestratorTests
{
    [Fact]
    public void CreateWorkspace_WritesCanonicalAndGeneratedFiles()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core", "document-processing"));

            Assert.True(File.Exists(snapshot.Paths.WorkspaceYamlPath));
            Assert.True(File.Exists(snapshot.Paths.ComposePath));
            Assert.True(File.Exists(snapshot.Paths.EnvironmentFilePath));
            Assert.True(File.Exists(snapshot.Paths.ProvisionScriptPath));
            Assert.True(File.Exists(snapshot.Paths.StarshipConfigPath));
            Assert.True(File.Exists(snapshot.Paths.ShellInitScriptPath));
            Assert.True(File.Exists(snapshot.Paths.OpencodeWorkspaceShellPath));
            Assert.True(File.Exists(snapshot.Paths.ScreenConfigPath));
            Assert.True(File.Exists(snapshot.Paths.AttachWrapperScriptPath));
            Assert.True(File.Exists(snapshot.Paths.TerminalDiagnosticsScriptPath));
            Assert.True(Directory.Exists(Path.Combine(tempRoot, ".git")));
            Assert.True(File.Exists(snapshot.Paths.TimelinePath));
            Assert.True(File.Exists(snapshot.Paths.CheckpointIndexPath));
            Assert.Contains("workspace-created", File.ReadAllText(snapshot.Paths.TimelinePath));
            Assert.Contains("Generated by OpenCode Workspace Manager", File.ReadAllText(snapshot.Paths.ComposePath));
            Assert.Contains("npm install -g opencode-ai", File.ReadAllText(snapshot.Paths.ProvisionScriptPath));
            Assert.Contains("/home/opencode/.local/share/opencode/log", File.ReadAllText(snapshot.Paths.ProvisionScriptPath));
            Assert.Contains("Initializing OpenCode user directories", File.ReadAllText(snapshot.Paths.OpencodeWorkspaceShellPath));
            Assert.Equal(WorkspaceSafetyLevel.AtRisk, snapshot.Safety.OverallStatus);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void CreateWorkspace_ForOracleDemo_WritesTutorialAndSkillFiles()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, new WorkspaceDefinition
            {
                Workspace = new WorkspaceMetadata { Name = "oracle-demo-workspace", Image = "ubuntu:24.04" },
                Features = ["core", "oracle-demo"],
                Services = ["oracle-demo"],
            });

            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "oracle-demo.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "ORACLE-DEMO.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, ".opencode", "context", "oracle-demo.json")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "tutorial", "workspace-tutorial.json")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "tutorial", "oracle", "init", "01-create-demo-user.sql")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "tutorial", "oracle", "START-HERE-ORACLE.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "tutorial", "oracle", "opencode-start.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "verify-oracle-demo.sh")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "knowledge", "skills", "oracle-explain-procedure.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, ".local", "oracle", "network", "admin", "README.md")));

            var topLevelGuide = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "ORACLE-DEMO.md"));
            var agentContext = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, ".opencode", "context", "oracle-demo.json"));
            var startHere = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "tutorial", "oracle", "START-HERE-ORACLE.md"));
            var openCodeStart = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "tutorial", "oracle", "opencode-start.md"));
            var verifyScript = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "scripts", "verify-oracle-demo.sh"));

            Assert.Contains("# Oracle Demo Connection", topLevelGuide);
            Assert.Contains("sqlplus -S demo_user/demo_password@//oracle-demo:1521/FREEPDB1", topLevelGuide);
            Assert.Contains("Run:", topLevelGuide);
            Assert.Contains("scripts/verify-oracle-demo.sh", topLevelGuide);
            Assert.Contains("Do not inspect `.env` for normal demo verification.", topLevelGuide);
            Assert.Contains("\"kind\": \"oracle-demo-connection\"", agentContext);
            Assert.Contains("\"connectString\": \"demo_user/demo_password@//oracle-demo:1521/FREEPDB1\"", agentContext);
            Assert.Contains("\"verifyScript\": \"scripts/verify-oracle-demo.sh\"", agentContext);
            Assert.Contains("demo_user/demo_password@//oracle-demo:1521/FREEPDB1", startHere);
            Assert.Contains("Before asking for connection details, read `ORACLE-DEMO.md` or `.opencode/context/oracle-demo.json`.", startHere);
            Assert.Contains("Use the known local demo connection. Do not ask for credentials.", startHere);
            Assert.Contains("scripts/verify-oracle-demo.sh", startHere);
            Assert.Contains("Start Oracle first", openCodeStart);
            Assert.Contains("Before asking for connection details, read `ORACLE-DEMO.md` or `.opencode/context/oracle-demo.json`.", openCodeStart);
            Assert.Contains("demo_user/demo_password@//oracle-demo:1521/FREEPDB1", openCodeStart);
            Assert.Contains("Do not ask for credentials", openCodeStart);
            Assert.Contains("Run scripts/verify-oracle-demo.sh", openCodeStart);
            Assert.Contains("sqlplus -S demo_user/demo_password@//oracle-demo:1521/FREEPDB1 <<'EOF'", verifyScript);

            if (OperatingSystem.IsLinux() || OperatingSystem.IsMacOS())
            {
                var mode = File.GetUnixFileMode(Path.Combine(snapshot.Paths.RootPath, "scripts", "verify-oracle-demo.sh"));
                Assert.True(mode.HasFlag(UnixFileMode.UserExecute));
            }
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void CreateWorkspace_ForDocumentProcessing_WritesDocumentationGuidesAndScripts()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core", "document-processing"));

            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "documentation-features.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "DOCUMENTATION-FEATURES.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "validate-documentation-tooling.sh")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "demo-documentation-workflows.sh")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "samples", "documentation", "report.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "samples", "documentation", "report.html")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "samples", "documentation", "architecture.mmd")));

            var quickGuide = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "DOCUMENTATION-FEATURES.md"));
            var validationScript = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "scripts", "validate-documentation-tooling.sh"));
            var demoScript = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "scripts", "demo-documentation-workflows.sh"));

            Assert.Contains("scripts/validate-documentation-tooling.sh", quickGuide);
            Assert.Contains("scripts/demo-documentation-workflows.sh", quickGuide);
            Assert.Contains("require_command pandoc", validationScript);
            Assert.Contains("require_command node", validationScript);
            Assert.Contains("node -e \"console.log(process.version)\"", validationScript);
            Assert.Contains("fc-list | sort", validationScript);
            Assert.Contains("fc-match Calibri", validationScript);
            Assert.Contains("pandoc \"${workspace_root}/samples/documentation/report.md\"", demoScript);
            Assert.Contains("weasyprint \"${workspace_root}/samples/documentation/report.html\"", demoScript);
            Assert.Contains("mmdc -p \"${output_dir}/mermaid-puppeteer.json\" -i \"${workspace_root}/samples/documentation/architecture.mmd\"", demoScript);
            Assert.Contains("pdfinfo \"${output_dir}/markdown-report.pdf\"", demoScript);

            if (OperatingSystem.IsLinux() || OperatingSystem.IsMacOS())
            {
                var validationMode = File.GetUnixFileMode(Path.Combine(snapshot.Paths.RootPath, "scripts", "validate-documentation-tooling.sh"));
                var demoMode = File.GetUnixFileMode(Path.Combine(snapshot.Paths.RootPath, "scripts", "demo-documentation-workflows.sh"));
                Assert.True(validationMode.HasFlag(UnixFileMode.UserExecute));
                Assert.True(demoMode.HasFlag(UnixFileMode.UserExecute));
            }
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void CreateWorkspace_ForAnalyticsReporting_WritesExamplesValidationAndOnboarding()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core", "analytics-reporting", "education-knowledge-pack", "analytics-sample-data-pack"));

            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "analytics", "README.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "analytics", "analysis.py")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "analytics", "sample-data", "customers.json")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "analytics", "sample-data", "sales.csv")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "validate-analytics-tooling.sh")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "smoke-marimo.sh")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "reference", "education-knowledge-map.yaml")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "reference", "agent-onboarding", "analytics.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "reference", "agent-onboarding", "education.md")));

            var env = File.ReadAllText(snapshot.Paths.EnvironmentFilePath);
            var compose = File.ReadAllText(snapshot.Paths.ComposePath);
            var analyticsReadme = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "examples", "analytics", "README.md"));
            var agents = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "AGENTS.md"));
            var smokeScript = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "scripts", "smoke-marimo.sh"));
            var workbookPath = Path.Combine(snapshot.Paths.RootPath, "examples", "analytics", "sample-data", "kpis.xlsx");

            Assert.Contains("MARIMO_PORT=2718", env);
            Assert.Contains("127.0.0.1:${MARIMO_PORT}:2718", compose);
            Assert.Contains("marimo edit examples/analytics/analysis.py", analyticsReadme);
            Assert.Contains("The Trick That Makes Open LLMs Viable for Python", analyticsReadme);
            Assert.Contains("docs/reference/agent-onboarding/analytics.md", agents);
            Assert.Contains("docs/reference/agent-onboarding/education.md", agents);
            Assert.DoesNotContain("docs/reference/agent-onboarding/publishing.md", agents);
            var analysisPy = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "examples", "analytics", "analysis.py"));
            Assert.Contains("pd.read_excel(", analysisPy);
            Assert.DoesNotContain("kpis.xlsx\").read_text", analysisPy, StringComparison.Ordinal);
            Assert.Contains("--host 0.0.0.0", smokeScript);
            Assert.Contains("--port \"${port}\"", smokeScript);
            Assert.Contains("curl -fsS \"http://127.0.0.1:${port}\"", smokeScript);
            Assert.Contains("trap cleanup EXIT", smokeScript);
            Assert.Contains("kill \"${pid}\"", smokeScript);

            using var workbook = ZipFile.OpenRead(workbookPath);
            Assert.Contains(workbook.Entries, entry => entry.FullName == "xl/workbook.xml");
            Assert.Contains(workbook.Entries, entry => entry.FullName == "xl/worksheets/sheet1.xml");
            Assert.Contains(workbook.Entries, entry => entry.FullName == "xl/sharedStrings.xml");
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void CreateWorkspace_ForPublishingTex_WritesExamplesValidationAndOnboarding()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core", "publishing-tex", "publishing-knowledge-pack"));

            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "publishing", "README.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "publishing", "report.typ")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "publishing", "paper.tex")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "validate-publishing-tooling.sh")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "demo-publishing-workflows.sh")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "reference", "publishing-knowledge-map.yaml")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "reference", "agent-onboarding", "publishing.md")));

            var readme = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "examples", "publishing", "README.md"));
            var validation = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "scripts", "validate-publishing-tooling.sh"));
            var demo = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "scripts", "demo-publishing-workflows.sh"));
            var agents = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "AGENTS.md"));
            var provision = File.ReadAllText(snapshot.Paths.ProvisionScriptPath);

            Assert.Contains("1. Markdown", readme);
            Assert.Contains("2. Typst", readme);
            Assert.Contains("3. LaTeX", readme);
            Assert.Contains("source -> build -> validate -> inspect", readme);
            Assert.Contains("qpdf --check", validation);
            Assert.Contains("typst --version", validation);
            Assert.Contains("pandoc", validation);
            Assert.Contains("latexmk", validation);
            Assert.Contains("pdflatex", validation);
            Assert.Contains("biber", validation);
            Assert.Contains("rsvg-convert", validation);
            Assert.Contains("pdftotext", validation);
            Assert.Contains("pandoc", demo);
            Assert.Contains("latexmk -pdf", demo);
            Assert.Contains("qpdf --check", demo);
            Assert.Contains("pdftotext", demo);
            Assert.Contains("rsvg-convert", demo);
            Assert.Contains("typst compile", demo);
            Assert.Contains("docs/reference/agent-onboarding/publishing.md", agents);
            Assert.DoesNotContain("docs/reference/agent-onboarding/education.md", agents);
            Assert.Contains("command -v typst", provision);
            Assert.Contains("install /tmp/typst-install/typst-*/typst /usr/local/bin/typst", provision);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void CreateWorkspace_ForEducationStemDemo_WritesFeaturedLearningEnvironment()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var provider = new BuiltInCatalogProvider(Path.Combine(TestPaths.RepositoryRoot, "catalog"));
            var template = provider.LoadTemplates().Single(item => item.Id == "education-stem-demo");
            var definition = new TemplateExpander().Expand("education-demo", template);
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, definition);

            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "README.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "education-stem-demo.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "learning-path.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "projects.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "educator-guide.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "parent-guide.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "docs", "example-prompts.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "survey-analysis", "survey.csv")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "survey-analysis", "analysis.py")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "survey-analysis", "analysis-notebook.py")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "climate-dashboard", "dashboard.py")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "probability-lab", "dice.py")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "probability-lab", "coin-flips.py")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "machine-learning-intro", "model.py")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "examples", "science-report", "report.typ")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "skills", "analytics", "excel-analysis.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "skills", "education", "lesson-plan.md")));
            Assert.True(File.Exists(Path.Combine(snapshot.Paths.RootPath, "reports", "README.md")));

            var readme = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "README.md"));
            var learningPath = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "docs", "learning-path.md"));
            var educatorGuide = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "docs", "educator-guide.md"));
            var parentGuide = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "docs", "parent-guide.md"));
            var examplePrompts = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "docs", "example-prompts.md"));
            var agents = File.ReadAllText(Path.Combine(snapshot.Paths.RootPath, "AGENTS.md"));

            Assert.Contains("Curiosity", readme);
            Assert.Contains("Repository", readme);
            Assert.Contains("Workspace Discovery", readme);
            Assert.Contains("Survey Analysis", learningPath);
            Assert.Contains("Machine Learning Intro", learningPath);
            Assert.Contains("middle school", educatorGuide, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("high school", educatorGuide, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("introductory university", educatorGuide, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("You do not need to be a programmer", parentGuide);
            Assert.Contains("Explain this Python script in beginner-friendly language.", examplePrompts);
            Assert.Contains("What assumptions should I verify before trusting these results?", examplePrompts);
            Assert.Contains("docs/education-stem-demo.md", agents);
            Assert.Contains("docs/learning-path.md", agents);
            Assert.Contains("docs/example-prompts.md", agents);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void CreateWorkspace_WithoutAnalytics_DoesNotGenerateMarimoArtifacts()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));

            Assert.False(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "smoke-marimo.sh")));
            Assert.False(File.Exists(Path.Combine(snapshot.Paths.RootPath, "scripts", "validate-analytics-tooling.sh")));

            var env = File.ReadAllText(snapshot.Paths.EnvironmentFilePath);
            var compose = File.ReadAllText(snapshot.Paths.ComposePath);
            Assert.DoesNotContain("MARIMO_PORT=", env);
            Assert.DoesNotContain("127.0.0.1:${MARIMO_PORT}:2718", compose);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task Regenerate_ForAnalyticsWorkspace_DoesNotDuplicateMarimoPortMappings()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = await orchestrator.CreateWorkspaceAsync(tempRoot, CreateDefinition("core", "analytics-reporting"), includeRuntimeInspection: false);

            await orchestrator.RegenerateAsync(snapshot);
            await orchestrator.RegenerateAsync(snapshot);

            var compose = File.ReadAllText(snapshot.Paths.ComposePath);
            Assert.Equal(1, compose.Split('\n').Count(line => line.Contains("127.0.0.1:${MARIMO_PORT}:2718", StringComparison.Ordinal)));
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void WriteAppliedState_WritesAppliedStateFile()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));

            orchestrator.WriteAppliedState(snapshot);

            Assert.True(File.Exists(snapshot.Paths.AppliedStatePath));
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_AfterAppliedState_DoesNotRequireUpdate()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));
            orchestrator.WriteAppliedState(snapshot);

            var reloaded = orchestrator.LoadSnapshot(tempRoot);

            Assert.False(reloaded.UpdateRequired);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_AfterRuntimeOnlyReload_DoesNotRequireUpdate()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));
            orchestrator.WriteAppliedState(snapshot);

            var reloaded = orchestrator.LoadSnapshot(tempRoot);
            var runtimeOnlySnapshot = new WorkspaceSnapshot
            {
                Record = reloaded.Record,
                Definition = reloaded.Definition,
                Paths = reloaded.Paths,
                ConfigurationPath = reloaded.ConfigurationPath,
                RuntimeState = WorkspaceRuntimeState.Running,
                Safety = reloaded.Safety,
                Session = reloaded.Session,
                AppliedState = reloaded.AppliedState,
                UpdateRequired = reloaded.UpdateRequired,
            };

            Assert.False(runtimeOnlySnapshot.UpdateRequired);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_WhenWorkspaceYamlChanges_RequiresUpdate()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));
            orchestrator.WriteAppliedState(snapshot);

            File.WriteAllText(snapshot.Paths.WorkspaceYamlPath, File.ReadAllText(snapshot.Paths.WorkspaceYamlPath).Replace("ubuntu:24.04", "ubuntu:22.04", StringComparison.Ordinal));

            var reloaded = orchestrator.LoadSnapshot(tempRoot);

            Assert.True(reloaded.UpdateRequired);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_WhenSelectedFeaturesChange_RequiresUpdate()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));
            orchestrator.WriteAppliedState(snapshot);

            var updatedDefinition = CreateDefinition("core", "document-processing");
            File.WriteAllText(snapshot.Paths.WorkspaceYamlPath, new WorkspaceYamlService().Write(updatedDefinition));

            var reloaded = orchestrator.LoadSnapshot(tempRoot);

            Assert.True(reloaded.UpdateRequired);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_WhenRelevantCatalogPlanChanges_RequiresUpdate()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var originalResolver = CreateResolver();
            var originalOrchestrator = CreateOrchestrator(tempRoot, originalResolver);
            var snapshot = originalOrchestrator.CreateWorkspace(tempRoot, CreateDefinition("core", "document-processing"));
            originalOrchestrator.WriteAppliedState(snapshot);

            var changedResolver = CreateResolver(additionalDocumentProcessingAptPackage: "tesseract-ocr");
            var changedOrchestrator = CreateOrchestrator(tempRoot, changedResolver);

            var reloaded = changedOrchestrator.LoadSnapshot(tempRoot);

            Assert.True(reloaded.UpdateRequired);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void CreatePermissionRepairArguments_UsesHelperContainerAndTargetMount()
    {
        var arguments = DockerService.CreatePermissionRepairArguments("C:\\Workspaces\\Demo");

        Assert.Equal("run", arguments[0]);
        Assert.Contains("ubuntu:24.04", arguments);
        Assert.Contains("C:\\Workspaces\\Demo:/target", arguments);
        Assert.Contains("chmod -R u+rwX,go+rwX /target || true", arguments[^1]);
    }

    [Fact]
    public void OpenFolderAsWorkspace_InitializesGitAndCreatesWorkspaceWithoutBlockingSavePoint()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            Directory.CreateDirectory(tempRoot);
            File.WriteAllText(Path.Combine(tempRoot, "notes.txt"), "draft notes");
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());

            var snapshot = orchestrator.OpenFolderAsWorkspace(tempRoot);

            Assert.True(File.Exists(snapshot.Paths.WorkspaceYamlPath));
            Assert.True(Directory.Exists(Path.Combine(tempRoot, ".git")));
            Assert.Null(snapshot.Safety.LocalRecovery.LatestSavePointUtc);
            Assert.Equal(WorkspaceSafetyLevel.AtRisk, snapshot.Safety.OverallStatus);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task PublishAsync_RecordsBlockedPublishInTimeline()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var timelineService = new WorkspaceTimelineService();
            var orchestrator = CreateOrchestratorWithProvider(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), timelineService);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));

            var review = await orchestrator.PublishAsync(snapshot);
            var timeline = timelineService.Load(snapshot.Paths.TimelinePath);

            Assert.True(review.IsBlocked);
            Assert.Contains(timeline.Events, item => item.Type == "publish-attempted");
            Assert.Contains(timeline.Events, item => item.Type == "publish-blocked");
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_WhenUnknownHiddenFolderExists_ReturnsNeedsReview()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));
            Directory.CreateDirectory(Path.Combine(tempRoot, ".foo"));
            File.WriteAllText(Path.Combine(tempRoot, ".foo", "state.json"), "{}");

            var reloaded = orchestrator.LoadSnapshot(tempRoot);

            Assert.Equal(WorkspaceSafetyLevel.NeedsReview, reloaded.Safety.OverallStatus);
            Assert.True(reloaded.Safety.IgnorePolicy.HasUnknownHiddenFolders);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_WhenSecretCandidateExists_ReturnsAtRisk()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));
            File.WriteAllText(Path.Combine(tempRoot, ".env"), "API_KEY=secret");

            var reloaded = orchestrator.LoadSnapshot(tempRoot);

            Assert.Equal(WorkspaceSafetyLevel.AtRisk, reloaded.Safety.OverallStatus);
            Assert.True(reloaded.Safety.IgnorePolicy.HasSecretCandidates);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public void LoadSnapshot_WhenTimelineIsIgnored_ReturnsNeedsReview()
    {
        Assert.True(CanRunGit(), "Git is required for workspace persistence tests.");
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            orchestrator.CreateWorkspace(tempRoot, CreateDefinition("core"));
            File.AppendAllText(Path.Combine(tempRoot, ".gitignore"), "history/*.yaml\n");

            var reloaded = orchestrator.LoadSnapshot(tempRoot);

            Assert.Equal(WorkspaceSafetyLevel.NeedsReview, reloaded.Safety.OverallStatus);
            Assert.True(reloaded.Safety.IgnorePolicy.HasDurableIgnoreConflicts);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task ManagedWorkspaceOperations_RegenerateStaleComposeBeforeDockerComposeDownAndUp()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var dockerRunner = new ComposeGuardProcessRunner();
            var orchestrator = CreateOrchestratorWithProviderAndDocker(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), new DockerService(dockerRunner), new WorkspaceTimelineService());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());
            var logEntries = new List<CommandLogEntry>();

            WriteInvalidWorkspaceDependsOnCompose(snapshot.Paths.ComposePath);
            Assert.Contains("condition: service_healthy", File.ReadAllText(snapshot.Paths.ComposePath));

            await orchestrator.RemoveDockerResourcesAsync(snapshot, entry => logEntries.Add(entry));

            var repairedAfterRemove = File.ReadAllText(snapshot.Paths.ComposePath);
            Assert.DoesNotContain("condition: service_healthy", repairedAfterRemove);
            Assert.DoesNotContain("oracle:", repairedAfterRemove);
            Assert.DoesNotContain("depends_on:", repairedAfterRemove);

            WriteInvalidWorkspaceDependsOnCompose(snapshot.Paths.ComposePath);
            Assert.Contains("condition: service_healthy", File.ReadAllText(snapshot.Paths.ComposePath));

            await orchestrator.StartAsync(snapshot, entry => logEntries.Add(entry));

            var repairedAfterStart = File.ReadAllText(snapshot.Paths.ComposePath);
            Assert.DoesNotContain("condition: service_healthy", repairedAfterStart);
            Assert.DoesNotContain("oracle:", repairedAfterStart);
            Assert.DoesNotContain("depends_on:", repairedAfterStart);
            Assert.Contains(logEntries, entry => entry.Message.Contains("Stale compose detected for this managed workspace.", StringComparison.Ordinal));
            Assert.Contains(logEntries, entry => entry.Message.Contains("Compose regenerated/repaired.", StringComparison.Ordinal));
            Assert.True(logEntries.Count(entry => entry.Message.Contains("Regenerated stale compose.yaml before Docker operation", StringComparison.Ordinal)) >= 2);
            Assert.DoesNotContain(logEntries, entry => entry.Message.Contains("Docker Compose validation failed.", StringComparison.Ordinal));
            Assert.Contains(dockerRunner.Commands, command => command.Contains(" compose ", StringComparison.Ordinal) && command.Contains(" config", StringComparison.Ordinal));
            Assert.Contains(dockerRunner.Commands, command => command.Contains(" down ", StringComparison.Ordinal));
            Assert.Contains(dockerRunner.Commands, command => command.Contains(" up -d", StringComparison.Ordinal));
            Assert.Equal(0, dockerRunner.StaleComposeObservedCount);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task RecoverWorkspace_RegeneratesStaleComposeBeforeDockerComposeConfig()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var dockerRunner = new ComposeGuardProcessRunner();
            var orchestrator = CreateOrchestratorWithProviderAndDocker(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), new DockerService(dockerRunner), new WorkspaceTimelineService());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());
            var logEntries = new List<CommandLogEntry>();

            WriteInvalidWorkspaceDependsOnCompose(snapshot.Paths.ComposePath);
            Assert.Contains("condition: service_healthy", File.ReadAllText(snapshot.Paths.ComposePath));

            await orchestrator.RecoverAsync(snapshot, entry => logEntries.Add(entry));

            var repairedCompose = File.ReadAllText(snapshot.Paths.ComposePath);
            Assert.DoesNotContain("condition: service_healthy", repairedCompose);
            Assert.DoesNotContain("oracle:", repairedCompose);
            Assert.DoesNotContain("depends_on:", repairedCompose);
            Assert.Contains(logEntries, entry => entry.Message.Contains("Compose regenerated/repaired.", StringComparison.Ordinal));
            Assert.Contains(logEntries, entry => entry.Message.Contains("Regenerated stale compose.yaml before Docker operation.", StringComparison.Ordinal));
            Assert.Contains(dockerRunner.Commands, command => command.Contains(" config", StringComparison.Ordinal));
            Assert.Equal(0, dockerRunner.StaleComposeObservedCount);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task RecoverWorkspace_RegeneratesAttachScriptFromFixedTemplate()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var dockerRunner = new ComposeGuardProcessRunner();
            var orchestrator = CreateOrchestratorWithProviderAndDocker(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), new DockerService(dockerRunner), new WorkspaceTimelineService());
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());

            var createdScript = File.ReadAllText(snapshot.Paths.OpencodeWorkspaceShellPath);
            Assert.Contains("set -euo pipefail", createdScript);
            Assert.DoesNotContain("Failed at line $LINENO", createdScript, StringComparison.Ordinal);
            var createdGuardIndex = createdScript.IndexOf("if [ -d /opt/oracle/instantclient ]; then", StringComparison.Ordinal);
            var createdProbeIndex = createdScript.IndexOf("oracle_client_home=$(find /opt/oracle/instantclient", StringComparison.Ordinal);
            Assert.True(createdGuardIndex >= 0 && createdProbeIndex > createdGuardIndex);

            var userOwnedFilePath = Path.Combine(snapshot.Paths.RootPath, "notes.txt");
            const string userOwnedContents = "keep me";
            File.WriteAllText(userOwnedFilePath, userOwnedContents);

            File.WriteAllText(snapshot.Paths.OpencodeWorkspaceShellPath, string.Join("\n", new[]
            {
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "oracle_client_home=$(find /opt/oracle/instantclient -maxdepth 2 -type f -name 'libsqlplus.so' -printf '%h\\n' 2>/dev/null | while read -r dir; do if ls \"$dir\"/libclntsh.so* >/dev/null 2>&1; then printf '%s\\n' \"$dir\"; break; fi; done)",
                string.Empty,
            }));

            await orchestrator.RecoverAsync(snapshot);

            var regeneratedScript = File.ReadAllText(snapshot.Paths.OpencodeWorkspaceShellPath);
            Assert.Contains("set -euo pipefail", regeneratedScript);
            Assert.DoesNotContain("Failed at line $LINENO", regeneratedScript, StringComparison.Ordinal);
            var guardIndex = regeneratedScript.IndexOf("if [ -d /opt/oracle/instantclient ]; then", StringComparison.Ordinal);
            var probeIndex = regeneratedScript.IndexOf("oracle_client_home=$(find /opt/oracle/instantclient", StringComparison.Ordinal);
            Assert.True(guardIndex >= 0 && probeIndex > guardIndex);
            Assert.NotEqual(string.Join("\n", new[]
            {
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "oracle_client_home=$(find /opt/oracle/instantclient -maxdepth 2 -type f -name 'libsqlplus.so' -printf '%h\\n' 2>/dev/null | while read -r dir; do if ls \"$dir\"/libclntsh.so* >/dev/null 2>&1; then printf '%s\\n' \"$dir\"; break; fi; done)",
                string.Empty,
            }), regeneratedScript);
            Assert.Equal(userOwnedContents, File.ReadAllText(userOwnedFilePath));
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task AttachAsync_WhenWorkspaceContainerIsNotRunning_DoesNotLaunchTerminal()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var terminalLauncher = new RecordingTerminalLauncher();
            var dockerRunner = new MissingContainerProcessRunner();
            var orchestrator = CreateOrchestratorWithProviderAndDocker(
                tempRoot,
                CreateResolver(),
                new FakeWorkspaceProvider(),
                new DockerService(dockerRunner),
                new WorkspaceTimelineService(),
                terminalLauncher: terminalLauncher);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());
            var logEntries = new List<CommandLogEntry>();

            var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => orchestrator.AttachAsync(snapshot, entry => logEntries.Add(entry)));

            Assert.Contains("Container 'odip-analiza-workspace' is not running", exception.Message, StringComparison.Ordinal);
            Assert.Equal(0, terminalLauncher.LaunchCount);
            Assert.Contains(logEntries, entry => entry.Message.Contains("Checking for the expected workspace container", StringComparison.Ordinal));
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task LaunchAttachForRunningWorkspaceAsync_WhenOpencodeUserIsMissing_ProvisionsBeforeAttachInitialization()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var terminalLauncher = new RecordingTerminalLauncher();
            var dockerRunner = new ProvisionBeforeAttachProcessRunner();
            var orchestrator = CreateOrchestratorWithProviderAndDocker(
                tempRoot,
                CreateResolver(),
                new FakeWorkspaceProvider(),
                new DockerService(dockerRunner),
                new WorkspaceTimelineService(),
                terminalLauncher: terminalLauncher);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());
            var logEntries = new List<CommandLogEntry>();

            await orchestrator.LaunchAttachForRunningWorkspaceAsync(snapshot, entry => logEntries.Add(entry));

            Assert.True(dockerRunner.ProvisioningRan);
            Assert.True(dockerRunner.DirectoryInitializationRanAfterProvisioning);
            Assert.Equal(1, terminalLauncher.LaunchCount);
            Assert.Contains(logEntries, entry => entry.Message.Contains("Workspace container is running but not provisioned. Running provisioning before attach.", StringComparison.Ordinal));
            Assert.DoesNotContain(logEntries, entry => entry.Message.Contains("Run Prepare Workspace or Repair Runtime", StringComparison.Ordinal));
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task LoadSnapshotAsync_WhenRuntimeStateIsCorrupted_IgnoresMachineLocalState()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var orchestrator = CreateOrchestrator(tempRoot, CreateResolver());
            var created = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());
            Directory.CreateDirectory(Path.GetDirectoryName(created.Paths.RuntimeStatePath)!);
            File.WriteAllText(created.Paths.RuntimeStatePath, "resolvedEngine: [broken\n");

            var loaded = await orchestrator.LoadSnapshotAsync(tempRoot);

            Assert.Null(loaded.LocalRuntimeState);
            Assert.Equal(created.Definition.Workspace.Name, loaded.Definition.Workspace.Name);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task ProvisionAsync_WritesRuntimeStateWithoutRewritingWorkspaceConfigurationIntent()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var runtime = new StubContainerRuntime();
            var orchestrator = CreateOrchestratorWithRuntimeAbstractions(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), runtime);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());
            var yamlBefore = new WorkspaceYamlService().Read(snapshot.Paths.WorkspaceYamlPath);

            await orchestrator.ProvisionAsync(snapshot);

            var yamlAfter = new WorkspaceYamlService().Read(snapshot.Paths.WorkspaceYamlPath);
            var runtimeState = new WorkspaceRuntimeStateService().Read(snapshot.Paths.RuntimeStatePath);

            Assert.Equal(yamlBefore.Workspace.Name, yamlAfter.Workspace.Name);
            Assert.Equal(yamlBefore.Runtime.Default, yamlAfter.Runtime.Default);
            Assert.Equal(yamlBefore.Runtime.GetEffectiveNodeMajorVersion(), yamlAfter.Runtime.GetEffectiveNodeMajorVersion());
            Assert.DoesNotContain("resolvedEngine", File.ReadAllText(snapshot.Paths.WorkspaceYamlPath), StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("resolvedPlatform", File.ReadAllText(snapshot.Paths.WorkspaceYamlPath), StringComparison.OrdinalIgnoreCase);
            Assert.NotNull(runtimeState);
            Assert.Equal("docker", runtimeState.ResolvedEngine);
            Assert.Equal("linux/amd64", runtimeState.ResolvedPlatform);
            Assert.Equal("Native", runtimeState.CompatibilityMode);
            Assert.NotNull(runtimeState.LastSuccessfulProvision);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task ProvisionAsync_WhenRuntimeStateFileIsDeleted_RegeneratesIt()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var runtime = new StubContainerRuntime();
            var orchestrator = CreateOrchestratorWithRuntimeAbstractions(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), runtime);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());

            await orchestrator.ProvisionAsync(snapshot);
            File.Delete(snapshot.Paths.RuntimeStatePath);

            await orchestrator.ProvisionAsync(snapshot);

            Assert.True(File.Exists(snapshot.Paths.RuntimeStatePath));
            var runtimeState = new WorkspaceRuntimeStateService().Read(snapshot.Paths.RuntimeStatePath);
            Assert.NotNull(runtimeState);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task ProvisionAsync_WhenProvisioningFails_DoesNotWriteRuntimeState()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var runtime = new StubContainerRuntime
            {
                ProvisionScriptResultFactory = () => Failure("docker exec provision", "provision failed"),
            };
            var orchestrator = CreateOrchestratorWithRuntimeAbstractions(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), runtime);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());

            await Assert.ThrowsAsync<InvalidOperationException>(() => orchestrator.ProvisionAsync(snapshot));

            Assert.False(File.Exists(snapshot.Paths.RuntimeStatePath));
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task ProvisionAsync_WhenPostProvisionValidationFails_DoesNotWriteRuntimeState()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var runtime = new StubContainerRuntime
            {
                ToolValidationResultFactory = () => Failure("docker exec tool-check", "opencode missing"),
            };
            var orchestrator = CreateOrchestratorWithRuntimeAbstractions(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), runtime);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());

            await Assert.ThrowsAsync<InvalidOperationException>(() => orchestrator.ProvisionAsync(snapshot));

            Assert.False(File.Exists(snapshot.Paths.RuntimeStatePath));
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    [Fact]
    public async Task LaunchAttachForRunningWorkspaceAsync_WhenProvisioningSucceeds_WritesRuntimeState()
    {
        var tempRoot = CreateTempRoot();

        try
        {
            var runtime = new StubContainerRuntime { UserExistsInitially = false };
            var terminalLauncher = new RecordingTerminalLauncher();
            var orchestrator = CreateOrchestratorWithRuntimeAbstractions(tempRoot, CreateResolver(), new FakeWorkspaceProvider(), runtime, terminalLauncher: terminalLauncher);
            var snapshot = orchestrator.CreateWorkspace(tempRoot, CreateAnalizaDefinition());

            await orchestrator.LaunchAttachForRunningWorkspaceAsync(snapshot);

            Assert.Equal(1, terminalLauncher.LaunchCount);
            Assert.True(File.Exists(snapshot.Paths.RuntimeStatePath));
            var runtimeState = new WorkspaceRuntimeStateService().Read(snapshot.Paths.RuntimeStatePath);
            Assert.NotNull(runtimeState);
            Assert.Equal("docker", runtimeState.ResolvedEngine);
        }
        finally
        {
            DeleteTempRoot(tempRoot);
        }
    }

    private static WorkspaceDefinition CreateDefinition(params string[] features)
    {
        return new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Name = "smoke-workspace",
                Image = "ubuntu:24.04",
            },
            Features = features.ToList(),
            Services = new List<string> { "postgres", "pgadmin" },
            Skills = new List<string>(),
            Mcp = new List<string>(),
        };
    }

    private static WorkspaceDefinition CreateAnalizaDefinition()
    {
        return new WorkspaceDefinition
        {
            Workspace = new WorkspaceMetadata
            {
                Id = "odip-analiza",
                Name = "Odip Analiza",
                Image = "ubuntu:24.04",
            },
            Provider = new WorkspaceProviderDefinition
            {
                Type = "git",
                Url = "git@ssh.dev.azure.com:v3/KOPA-Projects/ODIP/Analiza",
            },
            Runtime = new WorkspaceRuntimeDefinition
            {
                Default = "default",
                Node = 22,
            },
            Features = new List<string> { "core", "document-processing", "ocr-processing", "spellcheck" },
            Services = new List<string>(),
            Skills = new List<string>(),
            Mcp = new List<string>(),
        };
    }

    private static void WriteInvalidWorkspaceDependsOnCompose(string composePath)
    {
        File.WriteAllText(composePath, string.Join("\n", new[]
        {
            "services:",
            "  workspace:",
            "    image: ubuntu:24.04",
            "    depends_on:",
            "      oracle:",
            "        condition: service_healthy",
            string.Empty,
        }));
    }

    private static WorkspaceResolver CreateResolver(string? additionalDocumentProcessingAptPackage = null)
    {
        var documentPackages = new List<string>
        {
            "pandoc",
            "poppler-utils",
            "graphviz",
            "plantuml",
            "libreoffice",
            "fonts-dejavu",
            "fonts-liberation",
            "fonts-crosextra-carlito",
            "fonts-crosextra-caladea",
            "fonts-noto",
            "fonts-noto-cjk",
            "fonts-noto-extra",
            "fonts-noto-color-emoji",
            "fonts-roboto",
            "fonts-inter",
            "fonts-firacode",
            "fonts-jetbrains-mono",
        };
        if (!string.IsNullOrWhiteSpace(additionalDocumentProcessingAptPackage))
        {
            documentPackages.Add(additionalDocumentProcessingAptPackage);
        }

        return new WorkspaceResolver(
            new[]
            {
                new FeatureManifest
                {
                    Id = "core",
                    AlwaysEnabled = true,
                    Dependencies = new DependencySet { Apt = new List<string> { "git", "curl" } },
                },
                new FeatureManifest
                {
                    Id = "document-processing",
                    Dependencies = new DependencySet
                    {
                        Apt = documentPackages,
                        Npm = new List<string> { "playwright", "@mermaid-js/mermaid-cli" },
                        Pip = new List<string> { "weasyprint", "markdown-it-py", "pypdf", "pymupdf", "reportlab" },
                    },
                    PostInstall =
                    [
                        "command -v typst >/dev/null 2>&1 || install /tmp/typst-install/typst-*/typst /usr/local/bin/typst",
                        "playwright install chromium",
                        "fc-cache -fv",
                    ],
                },
                new FeatureManifest
                {
                    Id = "ocr-processing",
                    Dependencies = new DependencySet(),
                },
                new FeatureManifest
                {
                    Id = "spellcheck",
                    Dependencies = new DependencySet(),
                },
                new FeatureManifest
                {
                    Id = "oracle-demo",
                    KnowledgePacks = new List<string> { "oracle-documentation-pack" },
                    Dependencies = new DependencySet { Apt = new List<string> { "curl", "unzip" } },
                },
                new FeatureManifest
                {
                    Id = "analytics-reporting",
                    KnowledgePacks = new List<string> { "education-knowledge-pack" },
                    Dependencies = new DependencySet
                    {
                        Apt = new List<string> { "csvkit", "graphviz", "jq", "miller", "p7zip-full", "poppler-utils", "qpdf", "yq" },
                        Pip = new List<string> { "marimo", "pandas", "numpy", "openpyxl", "xlsxwriter", "matplotlib", "plotly", "pypdf", "pymupdf", "scipy", "sympy", "scikit-learn", "statsmodels", "seaborn", "jupyterlab", "ipywidgets", "networkx", "folium", "tabulate" },
                    },
                },
                new FeatureManifest
                {
                    Id = "education-knowledge-pack",
                    KnowledgePacks = new List<string> { "education-knowledge-pack" },
                    Dependencies = new DependencySet(),
                },
                new FeatureManifest
                {
                    Id = "publishing-tex",
                    KnowledgePacks = new List<string> { "publishing-knowledge-pack" },
                    Dependencies = new DependencySet { Apt = new List<string> { "pandoc", "latexmk", "biber", "qpdf", "poppler-utils", "librsvg2-bin", "inkscape", "ghostscript", "texlive-latex-recommended", "texlive-latex-extra", "texlive-fonts-recommended", "texlive-science" } },
                    PostInstall = ["command -v typst >/dev/null 2>&1 || install /tmp/typst-install/typst-*/typst /usr/local/bin/typst"],
                },
                new FeatureManifest
                {
                    Id = "publishing-knowledge-pack",
                    KnowledgePacks = new List<string> { "publishing-knowledge-pack" },
                    Dependencies = new DependencySet(),
                },
                new FeatureManifest
                {
                    Id = "analytics-sample-data-pack",
                    Dependencies = new DependencySet(),
                },
                new FeatureManifest
                {
                    Id = "education-stem-demo",
                    Dependencies = new DependencySet(),
                },
            },
            new[]
            {
                new ServiceManifest
                {
                    Id = "postgres",
                    Image = "postgres:17",
                    HostPorts = new List<string> { "15432:5432" },
                    Volumes = new List<string> { "postgres-data:/var/lib/postgresql/data" },
                },
                new ServiceManifest
                {
                    Id = "pgadmin",
                    Image = "dpage/pgadmin4:9",
                    HostPorts = new List<string> { "18080:80" },
                    DependsOn = new List<string> { "postgres" },
                },
                new ServiceManifest
                {
                    Id = "oracle-demo",
                    Image = "gvenzl/oracle-free:23-slim-faststart",
                    HostPorts = new List<string> { "1521:1521" },
                    Profiles = new List<string> { "oracle-demo" },
                    WorkspaceDependsOnCondition = "service_healthy",
                    Volumes = new List<string> { "oracle-demo-data:/opt/oracle/oradata", "${WORKSPACE_TUTORIAL_DOCKER_PATH}/oracle/init:/container-entrypoint-initdb.d" },
                },
            },
            Array.Empty<CapabilityManifest>(),
            new[]
            {
                new KnowledgePackManifest
                {
                    Id = "oracle-documentation-pack",
                    Title = "Oracle Documentation Pack",
                    Onboarding = new List<string> { "docs/reference/agent-onboarding/oracle.md" },
                    WorkspacePaths = new KnowledgePackWorkspacePathsManifest
                    {
                        KnowledgeMap = "docs/reference/oracle-knowledge-map.yaml",
                        SourceIndex = "docs/reference/oracle-database-index.md",
                    },
                },
                new KnowledgePackManifest
                {
                    Id = "education-knowledge-pack",
                    Title = "Education Knowledge Pack",
                    Onboarding = new List<string> { "docs/reference/agent-onboarding/analytics.md", "docs/reference/agent-onboarding/education.md" },
                    WorkspacePaths = new KnowledgePackWorkspacePathsManifest
                    {
                        KnowledgeMap = "docs/reference/education-knowledge-map.yaml",
                        SourceIndex = "docs/reference/education-knowledge-index.md",
                    },
                },
                new KnowledgePackManifest
                {
                    Id = "publishing-knowledge-pack",
                    Title = "Publishing Knowledge Pack",
                    Onboarding = new List<string> { "docs/reference/agent-onboarding/publishing.md" },
                    WorkspacePaths = new KnowledgePackWorkspacePathsManifest
                    {
                        KnowledgeMap = "docs/reference/publishing-knowledge-map.yaml",
                        SourceIndex = "docs/reference/publishing-knowledge-index.md",
                    },
                },
            });
    }

    private static WorkspaceOrchestrator CreateOrchestrator(string tempRoot, WorkspaceResolver resolver)
    {
        var ignorePolicyService = new WorkspaceIgnorePolicyService();
        return CreateOrchestratorWithProvider(tempRoot, resolver, new GitWorkspaceProvider(new ProcessRunner(), ignorePolicyService), new WorkspaceTimelineService(), ignorePolicyService);
    }

    private static WorkspaceOrchestrator CreateOrchestratorWithProviderAndDocker(string tempRoot, WorkspaceResolver resolver, IWorkspaceProvider provider, DockerService dockerService, WorkspaceTimelineService timelineService, WorkspaceIgnorePolicyService? ignorePolicyService = null, ITerminalLauncher? terminalLauncher = null)
    {
        return new WorkspaceOrchestrator(
            new WorkspaceYamlService(),
            new WorkspaceDiscoveryService(),
            new WorkspaceRepository(GetAppDataRoot(tempRoot)),
            resolver,
            new ComposeGenerator(),
            new EnvironmentFileGenerator(),
            new ProvisioningScriptGenerator(),
            new TerminalArtifactsGenerator(),
            new AttachArtifactsGenerator(),
            new WorkspaceContentGenerator(),
            new WorkspaceAppliedStateService(),
            new WorkspaceCheckpointService(),
            timelineService,
            new WorkspaceSafetyService(),
            ignorePolicyService ?? new WorkspaceIgnorePolicyService(),
            provider,
            dockerService,
            terminalLauncher ?? new NoOpTerminalLauncher());
    }

    private static WorkspaceOrchestrator CreateOrchestratorWithProvider(string tempRoot, WorkspaceResolver resolver, IWorkspaceProvider provider, WorkspaceTimelineService timelineService, WorkspaceIgnorePolicyService? ignorePolicyService = null)
    {
        return new WorkspaceOrchestrator(
            new WorkspaceYamlService(),
            new WorkspaceDiscoveryService(),
            new WorkspaceRepository(GetAppDataRoot(tempRoot)),
            resolver,
            new ComposeGenerator(),
            new EnvironmentFileGenerator(),
            new ProvisioningScriptGenerator(),
            new TerminalArtifactsGenerator(),
            new AttachArtifactsGenerator(),
            new WorkspaceContentGenerator(),
            new WorkspaceAppliedStateService(),
            new WorkspaceCheckpointService(),
            timelineService,
            new WorkspaceSafetyService(),
            ignorePolicyService ?? new WorkspaceIgnorePolicyService(),
            provider,
            new DockerService(new ProcessRunner()),
            new NoOpTerminalLauncher());
    }

    private static WorkspaceOrchestrator CreateOrchestratorWithRuntimeAbstractions(string tempRoot, WorkspaceResolver resolver, IWorkspaceProvider provider, IContainerRuntime containerRuntime, WorkspaceTimelineService? timelineService = null, WorkspaceIgnorePolicyService? ignorePolicyService = null, ITerminalLauncher? terminalLauncher = null)
    {
        return new WorkspaceOrchestrator(
            new WorkspaceYamlService(),
            new WorkspaceDiscoveryService(),
            new WorkspaceRepository(GetAppDataRoot(tempRoot)),
            resolver,
            new ComposeGenerator(),
            new EnvironmentFileGenerator(),
            new ProvisioningScriptGenerator(),
            new TerminalArtifactsGenerator(),
            new AttachArtifactsGenerator(),
            new WorkspaceContentGenerator(),
            new WorkspaceAppliedStateService(),
            new WorkspaceCheckpointService(),
            timelineService ?? new WorkspaceTimelineService(),
            new WorkspaceSafetyService(),
            ignorePolicyService ?? new WorkspaceIgnorePolicyService(),
            new WorkspaceRuntimeStateService(),
            provider,
            containerRuntime,
            new FixedPlatformDetector(),
            new FixedRuntimeResolver(),
            terminalLauncher ?? new NoOpTerminalLauncher());
    }

    private static string CreateTempRoot() => Path.Combine(Path.GetTempPath(), $"opencode-workspace-manager-{Guid.NewGuid():N}");

    private static void DeleteTempRoot(string tempRoot)
    {
        var appDataRoot = GetAppDataRoot(tempRoot);
        if (Directory.Exists(tempRoot))
        {
            TestFileSystem.DeleteDirectoryIfExists(tempRoot);
        }

        if (Directory.Exists(appDataRoot))
        {
            TestFileSystem.DeleteDirectoryIfExists(appDataRoot);
        }
    }

    private static string GetAppDataRoot(string tempRoot)
        => Path.Combine(Path.GetDirectoryName(tempRoot) ?? Path.GetTempPath(), $"{Path.GetFileName(tempRoot)}-appdata");

    private static bool CanRunGit()
    {
        try
        {
            using var process = Process.Start(new System.Diagnostics.ProcessStartInfo
            {
                FileName = "git",
                Arguments = "--version",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            });

            process?.WaitForExit(5000);
            return process is not null && process.ExitCode == 0;
        }
        catch
        {
            return false;
        }
    }

    private sealed class NoOpTerminalLauncher : ITerminalLauncher
    {
        public Task LaunchAttachSessionAsync(WorkspaceSnapshot snapshot, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.CompletedTask;
    }

    private sealed class RecordingTerminalLauncher : ITerminalLauncher
    {
        public int LaunchCount { get; private set; }

        public Task LaunchAttachSessionAsync(WorkspaceSnapshot snapshot, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
        {
            LaunchCount++;
            return Task.CompletedTask;
        }
    }

    private sealed class FakeWorkspaceProvider : IWorkspaceProvider
    {
        public string Type => "git";

        public Task InitializeWorkspaceAsync(WorkspacePaths paths, WorkspaceDefinition definition, bool createInitialSavePoint, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.CompletedTask;

        public Task<WorkspaceGitState> GetGitStateAsync(WorkspacePaths paths, WorkspaceDefinition definition, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(new WorkspaceGitState
            {
                IsRepository = true,
                WorkingCopyName = "users/test/demo-20260613-1542",
                CurrentBranch = "users/test/demo-20260613-1542",
                LatestCommitSha = "abc123",
                LatestCommitUtc = DateTimeOffset.UtcNow.AddMinutes(-5),
                IsSafeWorkingCopy = true,
                StatusSummary = "clean",
            });
        }

        public Task<bool> CreateSavePointAsync(WorkspacePaths paths, WorkspaceDefinition definition, string message, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(true);

        public Task<WorkspacePublishReview> PublishAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(new WorkspacePublishReview
            {
                IsBlocked = true,
                Message = "Your local work is safe. The remote workspace changed and needs review before publishing.",
                WorkingCopyName = "users/test/demo-20260613-1542",
                RemoteName = "origin",
                RemoteBranch = "origin/users/test/demo-20260613-1542",
                AheadCount = 1,
                BehindCount = 1,
                LatestCommitSha = "abc123",
                LatestSavePointUtc = DateTimeOffset.UtcNow.AddMinutes(-5),
            });
        }

        public Task<WorkspacePublishReview> UpdateWorkingCopyAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(new WorkspacePublishReview { Message = "Updated." });

        public Task<WorkspacePublishReview> PublishToReviewWorkingCopyAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(new WorkspacePublishReview { Message = "Published review Working Copy." });

        public Task<string> ExportPatchAsync(WorkspacePaths paths, WorkspaceDefinition definition, string outputPath, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(outputPath);
    }

    private sealed class ComposeGuardProcessRunner : IProcessRunner
    {
        public List<string> Commands { get; } = new();

        public int StaleComposeObservedCount { get; private set; }

        public Task<ProcessResult> RunAsync(string fileName, IEnumerable<string> arguments, string? workingDirectory = null, Action<bool, string>? onOutput = null, CancellationToken cancellationToken = default, TimeSpan? timeout = null, Action<string>? onDiagnostic = null)
        {
            var argumentList = arguments.ToList();
            var command = string.Join(' ', new[] { fileName }.Concat(argumentList));
            Commands.Add(command);

            if (string.Equals(fileName, "docker", StringComparison.OrdinalIgnoreCase))
            {
                var composePath = TryGetComposePath(argumentList);
                if (composePath is not null && File.Exists(composePath))
                {
                    var compose = File.ReadAllText(composePath);
                    if (compose.Contains("condition: service_healthy", StringComparison.Ordinal)
                        || compose.Contains("      oracle:", StringComparison.Ordinal))
                    {
                        StaleComposeObservedCount++;
                        return Task.FromResult(CreateResult(command, 1, standardError: "stale invalid compose.yaml reached DockerService"));
                    }
                }

                if (argumentList.Contains("ps") && argumentList.Contains("--status"))
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: "workspace"));
                }

                if (argumentList.Count > 0 && argumentList[0] == "ps")
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: "odip-analiza-workspace"));
                }

                return Task.FromResult(CreateResult(command, 0));
            }

            return Task.FromResult(CreateResult(command, 0));
        }

        private static string? TryGetComposePath(IReadOnlyList<string> argumentList)
        {
            for (var index = 0; index < argumentList.Count - 1; index++)
            {
                if (string.Equals(argumentList[index], "--file", StringComparison.Ordinal))
                {
                    return argumentList[index + 1];
                }
            }

            return null;
        }

        private static ProcessResult CreateResult(string command, int exitCode, string standardOutput = "", string standardError = "")
        {
            return new ProcessResult
            {
                Command = command,
                ExitCode = exitCode,
                StandardOutput = standardOutput,
                StandardError = standardError,
                StandardOutputLines = string.IsNullOrWhiteSpace(standardOutput) ? Array.Empty<string>() : standardOutput.Split(Environment.NewLine),
                StandardErrorLines = string.IsNullOrWhiteSpace(standardError) ? Array.Empty<string>() : standardError.Split(Environment.NewLine),
                Duration = TimeSpan.FromMilliseconds(10),
            };
        }
    }

    private sealed class MissingContainerProcessRunner : IProcessRunner
    {
        public Task<ProcessResult> RunAsync(string fileName, IEnumerable<string> arguments, string? workingDirectory = null, Action<bool, string>? onOutput = null, CancellationToken cancellationToken = default, TimeSpan? timeout = null, Action<string>? onDiagnostic = null)
        {
            var argumentList = arguments.ToList();
            var command = string.Join(' ', new[] { fileName }.Concat(argumentList));

            if (string.Equals(fileName, "docker", StringComparison.OrdinalIgnoreCase))
            {
                if (argumentList.Contains("config", StringComparer.Ordinal))
                {
                    return Task.FromResult(CreateResult(command, 0));
                }

                if (argumentList.Contains("up", StringComparer.Ordinal))
                {
                    return Task.FromResult(CreateResult(command, 0));
                }

                if (argumentList.Contains("ps", StringComparer.Ordinal) && argumentList.Contains("--services", StringComparer.Ordinal))
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: "workspace"));
                }

                if (argumentList.Count > 0 && argumentList[0] == "ps")
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: string.Empty));
                }
            }

            return Task.FromResult(CreateResult(command, 0));
        }
    }

    private sealed class ProvisionBeforeAttachProcessRunner : IProcessRunner
    {
        public bool ProvisioningRan { get; private set; }

        public bool DirectoryInitializationRanAfterProvisioning { get; private set; }

        public Task<ProcessResult> RunAsync(string fileName, IEnumerable<string> arguments, string? workingDirectory = null, Action<bool, string>? onOutput = null, CancellationToken cancellationToken = default, TimeSpan? timeout = null, Action<string>? onDiagnostic = null)
        {
            var argumentList = arguments.ToList();
            var command = string.Join(' ', new[] { fileName }.Concat(argumentList));

            if (string.Equals(fileName, "docker", StringComparison.OrdinalIgnoreCase))
            {
                if (argumentList.Contains("ps", StringComparer.Ordinal) && argumentList.Contains("--services", StringComparer.Ordinal))
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: "workspace"));
                }

                if (argumentList.Count > 0 && argumentList[0] == "ps")
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: "odip-analiza-workspace"));
                }

                if (argumentList.Count >= 4 && argumentList[0] == "exec" && argumentList[^2] == "id" && argumentList[^1] == "opencode")
                {
                    return Task.FromResult(ProvisioningRan
                        ? CreateResult(command, 0, standardOutput: "uid=1001(opencode) gid=1001(opencode) groups=1001(opencode)")
                        : CreateResult(command, 1, standardError: "id: 'opencode': no such user"));
                }

                if (argumentList.Count >= 4 && argumentList[0] == "inspect" && argumentList[^1] == "{{.Image}}")
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: "sha256:test-image"));
                }

                if (argumentList.Count >= 4 && argumentList[0] == "inspect" && argumentList[^1] == "{{json .RepoTags}}")
                {
                    return Task.FromResult(CreateResult(command, 0, standardOutput: "[\"ubuntu:24.04\"]"));
                }

                if (argumentList.Count >= 4 && argumentList[0] == "exec" && argumentList[2] == "bash" && argumentList[3] == "/opt/opencode-workspace/config/provision.sh")
                {
                    ProvisioningRan = true;
                    return Task.FromResult(CreateResult(command, 0));
                }

                if (argumentList.Count >= 5 && argumentList[0] == "exec" && argumentList[2] == "bash" && argumentList[3] == "-lc")
                {
                    var shellCommand = argumentList[4];
                    if (shellCommand.Contains("which node && node --version && which npm && npm --version", StringComparison.Ordinal))
                    {
                        return Task.FromResult(ProvisioningRan
                            ? CreateResult(command, 0, standardOutput: string.Join(Environment.NewLine, "/usr/bin/node", "v22.15.0", "/usr/bin/npm", "10.9.2"))
                            : CreateResult(command, 1, standardError: "node: command not found"));
                    }

                    if (shellCommand.Contains("apt-cache policy nodejs", StringComparison.Ordinal))
                    {
                        return Task.FromResult(CreateResult(command, 0, standardOutput: "nodejs:\n  Installed: 22.15.0-1nodesource1"));
                    }

                    if (shellCommand.Contains("cat /etc/os-release", StringComparison.Ordinal))
                    {
                        return Task.FromResult(CreateResult(command, 0, standardOutput: "PRETTY_NAME=\"Ubuntu 24.04 LTS\""));
                    }

                    if (shellCommand.Contains("command -v opencode && command -v screen && command -v node && command -v npm && getent passwd opencode", StringComparison.Ordinal))
                    {
                        return Task.FromResult(ProvisioningRan
                            ? CreateResult(command, 0, standardOutput: string.Join(Environment.NewLine, "/usr/bin/opencode", "/usr/bin/screen", "/usr/bin/node", "/usr/bin/npm", "opencode:x:1001:1001::/home/opencode:/bin/bash"))
                            : CreateResult(command, 1, standardError: "Workspace container is running but not provisioned. Run Prepare Workspace or Repair Runtime."));
                    }

                    DirectoryInitializationRanAfterProvisioning = ProvisioningRan;
                    return Task.FromResult(ProvisioningRan
                        ? CreateResult(command, 0)
                        : CreateResult(command, 1, standardError: "Workspace container is running but not provisioned. Run Prepare Workspace or Repair Runtime."));
                }

                if (argumentList.Contains("config", StringComparer.Ordinal) || argumentList.Contains("up", StringComparer.Ordinal))
                {
                    return Task.FromResult(CreateResult(command, 0));
                }
            }

            return Task.FromResult(CreateResult(command, 0));
        }
    }

    private sealed class FixedPlatformDetector : IPlatformDetector
    {
        public Task<HostPlatformInfo> DetectAsync(CancellationToken cancellationToken = default)
        {
            return Task.FromResult(new HostPlatformInfo
            {
                OperatingSystem = HostOperatingSystem.Windows,
                Architecture = HostArchitecture.X64,
                HostDescription = "Windows X64",
                NativeContainerPlatform = "linux/amd64",
                Docker = new ContainerRuntimeAvailability
                {
                    EngineId = "docker",
                    CliAvailable = true,
                    EngineReachable = true,
                    BuildxAvailable = true,
                    SupportedPlatforms = ["linux/amd64", "linux/arm64"],
                },
            });
        }
    }

    private sealed class FixedRuntimeResolver : IRuntimeResolver
    {
        public Task<ResolvedRuntimePlan> ResolveAsync(WorkspaceDefinition definition, HostPlatformInfo hostPlatform, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(new ResolvedRuntimePlan
            {
                Runtime = "docker",
                TargetPlatform = "linux/amd64",
                CompatibilityMode = RuntimeCompatibilityMode.Native,
                SupportLevel = SupportLevel.NativeTested,
                IsAvailable = true,
                DiagnosticExplanation = "Test runtime plan.",
                HostPlatform = hostPlatform,
            });
        }
    }

    private sealed class StubContainerRuntime : IContainerRuntime
    {
        private bool _provisioned;

        public string RuntimeId => "docker";

        public bool UserExistsInitially { get; init; } = true;

        public Func<ProcessResult>? ProvisionScriptResultFactory { get; init; }

        public Func<ProcessResult>? ToolValidationResultFactory { get; init; }

        public string GetWorkspaceContainerName(WorkspaceDefinition definition) => DockerService.GetWorkspaceContainerName(definition);

        public IReadOnlyList<string> CreatePermissionRepairArguments(string workspaceRootPath) => DockerService.CreatePermissionRepairArguments(workspaceRootPath);

        public Task<ProcessResult> StartAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default, Func<CancellationToken, Task<bool>>? repairComposeAsync = null)
            => Task.FromResult(Success("docker compose up"));

        public Task<ProcessResult> ValidateAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default, Func<CancellationToken, Task<bool>>? repairComposeAsync = null)
            => Task.FromResult(Success("docker compose config"));

        public Task<ProcessResult> StopAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker compose down"));

        public Task<ProcessResult> RemoveAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default, Func<CancellationToken, Task<bool>>? repairComposeAsync = null)
            => Task.FromResult(Success("docker compose rm"));

        public Task<ProcessResult> ResetAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default, Func<CancellationToken, Task<bool>>? repairComposeAsync = null)
            => Task.FromResult(Success("docker compose reset"));

        public Task<ProcessResult> GetPsAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker compose ps", "workspace"));

        public Task<ProcessResult> GetComposePsAsync(WorkspacePaths paths, WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker compose ps"));

        public Task<ProcessResult> GetServiceLogsAsync(WorkspacePaths paths, WorkspaceDefinition definition, string serviceName, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker compose logs"));

        public Task<ProcessResult> RunProvisionScriptAsync(WorkspaceDefinition definition, WorkspacePaths paths, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
        {
            var result = ProvisionScriptResultFactory?.Invoke() ?? Success("docker exec provision");
            if (result.IsSuccess)
            {
                _provisioned = true;
            }

            return Task.FromResult(result);
        }

        public Task<ProcessResult> InspectContainerImageAsync(WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker inspect image", "sha256:test-image"));

        public Task<ProcessResult> InspectImageRepoTagsAsync(string imageId, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker inspect tags", "[\"ubuntu:24.04\"]"));

        public Task<ProcessResult> GetNodeToolDiagnosticsAsync(WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker exec node", "/usr/bin/node\nv22.15.0\n/usr/bin/npm\n10.9.2"));

        public Task<ProcessResult> GetNodeAptPolicyAsync(WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker exec apt-cache", "nodejs:\n  Installed: 22.15.0-1nodesource1"));

        public Task<ProcessResult> GetOsReleaseAsync(WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker exec os-release", "PRETTY_NAME=Ubuntu 24.04 LTS"));

        public Task<ProcessResult> CheckOpencodeUserAsync(WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
        {
            var userExists = _provisioned || UserExistsInitially;
            return Task.FromResult(userExists
                ? Success("docker exec id", "uid=1001(opencode)")
                : Failure("docker exec id", "id: 'opencode': no such user"));
        }

        public Task<ProcessResult> EnsureOpencodeUserDirectoriesAsync(WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker exec ensure-directories"));

        public Task<ProcessResult> NormalizeWorkspaceFilePermissionsAsync(string workspaceRootPath, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker run chmod-helper"));

        public Task<ProcessResult> RunSimpleDockerCommandAsync(IEnumerable<string> arguments, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
        {
            var argumentList = arguments.ToList();
            if (argumentList.Count > 0 && argumentList[0] == "ps")
            {
                return Task.FromResult(Success("docker ps", "odip-analiza-workspace"));
            }

            if (argumentList.Count >= 5 && argumentList[0] == "exec" && argumentList[3] == "-lc")
            {
                var shellCommand = argumentList[4];
                if (shellCommand.Contains("command -v opencode && command -v screen && command -v node && command -v npm && getent passwd opencode", StringComparison.Ordinal))
                {
                    return Task.FromResult(ToolValidationResultFactory?.Invoke() ?? Success("docker exec tool-check", "/usr/local/bin/opencode\n/usr/bin/screen\n/usr/bin/node\n/usr/bin/npm\nopencode:x:1001:1001::/home/opencode:/bin/bash"));
                }

                if (shellCommand.Contains("command -v starship", StringComparison.Ordinal))
                {
                    return Task.FromResult(Success("docker exec starship", "starship 1.0.0"));
                }
            }

            return Task.FromResult(Success("docker command"));
        }

        public Task<ProcessResult> ListOpenCodeSessionsAsync(WorkspaceDefinition definition, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker exec opencode session list"));

        public Task<ProcessResult> ExportOpenCodeSessionAsync(WorkspaceDefinition definition, string sessionId, Action<CommandLogEntry>? log = null, CancellationToken cancellationToken = default)
            => Task.FromResult(Success("docker exec opencode session export"));
    }

    private static ProcessResult Success(string command, string standardOutput = "")
        => new()
        {
            Command = command,
            ExitCode = 0,
            StandardOutput = standardOutput,
            StandardError = string.Empty,
            StandardOutputLines = string.IsNullOrWhiteSpace(standardOutput) ? Array.Empty<string>() : standardOutput.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries),
            StandardErrorLines = Array.Empty<string>(),
            Duration = TimeSpan.FromMilliseconds(10),
        };

    private static ProcessResult Failure(string command, string standardError)
        => new()
        {
            Command = command,
            ExitCode = 1,
            StandardOutput = string.Empty,
            StandardError = standardError,
            StandardOutputLines = Array.Empty<string>(),
            StandardErrorLines = [standardError],
            Duration = TimeSpan.FromMilliseconds(10),
        };

    private static ProcessResult CreateResult(string command, int exitCode, string standardOutput = "", string standardError = "")
    {
        return new ProcessResult
        {
            Command = command,
            ExitCode = exitCode,
            StandardOutput = standardOutput,
            StandardError = standardError,
            StandardOutputLines = string.IsNullOrWhiteSpace(standardOutput) ? Array.Empty<string>() : standardOutput.Split(Environment.NewLine),
            StandardErrorLines = string.IsNullOrWhiteSpace(standardError) ? Array.Empty<string>() : standardError.Split(Environment.NewLine),
            Duration = TimeSpan.FromMilliseconds(10),
        };
    }
}
